local M = {}

M.ErrorCode = {
    InvalidGraphArn = "INVALID_GRAPH_ARN",
    InvalidRequestBody = "INVALID_REQUEST_BODY",
    InternalError = "INTERNAL_ERROR",
}

M.DatasourcePackage = {
    DETECTIVE_CORE = "DETECTIVE_CORE",
    EKS_AUDIT = "EKS_AUDIT",
    ASFF_SECURITYHUB_FINDING = "ASFF_SECURITYHUB_FINDING",
}

M.DatasourcePackageIngestState = {
    STARTED = "STARTED",
    STOPPED = "STOPPED",
    DISABLED = "DISABLED",
}

M.MemberDisabledReason = {
    VOLUME_TOO_HIGH = "VOLUME_TOO_HIGH",
    VOLUME_UNKNOWN = "VOLUME_UNKNOWN",
}

M.InvitationType = {
    INVITATION = "INVITATION",
    ORGANIZATION = "ORGANIZATION",
}

M.MemberStatus = {
    INVITED = "INVITED",
    VERIFICATION_IN_PROGRESS = "VERIFICATION_IN_PROGRESS",
    VERIFICATION_FAILED = "VERIFICATION_FAILED",
    ENABLED = "ENABLED",
    ACCEPTED_BUT_DISABLED = "ACCEPTED_BUT_DISABLED",
}

M.EntityType = {
    IAM_ROLE = "IAM_ROLE",
    IAM_USER = "IAM_USER",
}

M.Severity = {
    INFORMATIONAL = "INFORMATIONAL",
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH",
    CRITICAL = "CRITICAL",
}

M.State = {
    ACTIVE = "ACTIVE",
    ARCHIVED = "ARCHIVED",
}

M.Status = {
    RUNNING = "RUNNING",
    FAILED = "FAILED",
    SUCCESSFUL = "SUCCESSFUL",
}

M.IndicatorType = {
    TTP_OBSERVED = "TTP_OBSERVED",
    IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL",
    FLAGGED_IP_ADDRESS = "FLAGGED_IP_ADDRESS",
    NEW_GEOLOCATION = "NEW_GEOLOCATION",
    NEW_ASO = "NEW_ASO",
    NEW_USER_AGENT = "NEW_USER_AGENT",
    RELATED_FINDING = "RELATED_FINDING",
    RELATED_FINDING_GROUP = "RELATED_FINDING_GROUP",
}

M.Reason = {
    AWS_THREAT_INTELLIGENCE = "AWS_THREAT_INTELLIGENCE",
}

M.Field = {
    SEVERITY = "SEVERITY",
    STATUS = "STATUS",
    CREATED_TIME = "CREATED_TIME",
}

M.SortOrder = {
    ASC = "ASC",
    DESC = "DESC",
}

return M
