local record M
    pages_list_linked_whats_app_business_accounts: function(client: table, input: table): function(): table, table
    items_list_linked_whats_app_business_accounts: function(client: table, input: table): function(): any
    pages_list_whats_app_message_templates: function(client: table, input: table): function(): table, table
    items_list_whats_app_message_templates: function(client: table, input: table): function(): any
    pages_list_whats_app_template_library: function(client: table, input: table): function(): table, table
    items_list_whats_app_template_library: function(client: table, input: table): function(): any
end

return M
