local record M
    pages_describe_topic_partitions: function(client: table, input: table): function(): table, table
    items_describe_topic_partitions: function(client: table, input: table): function(): any
    pages_list_client_vpc_connections: function(client: table, input: table): function(): table, table
    items_list_client_vpc_connections: function(client: table, input: table): function(): any
    pages_list_cluster_operations: function(client: table, input: table): function(): table, table
    items_list_cluster_operations: function(client: table, input: table): function(): any
    pages_list_cluster_operations_v2: function(client: table, input: table): function(): table, table
    items_list_cluster_operations_v2: function(client: table, input: table): function(): any
    pages_list_clusters: function(client: table, input: table): function(): table, table
    items_list_clusters: function(client: table, input: table): function(): any
    pages_list_clusters_v2: function(client: table, input: table): function(): table, table
    items_list_clusters_v2: function(client: table, input: table): function(): any
    pages_list_configuration_revisions: function(client: table, input: table): function(): table, table
    items_list_configuration_revisions: function(client: table, input: table): function(): any
    pages_list_configurations: function(client: table, input: table): function(): table, table
    items_list_configurations: function(client: table, input: table): function(): any
    pages_list_kafka_versions: function(client: table, input: table): function(): table, table
    items_list_kafka_versions: function(client: table, input: table): function(): any
    pages_list_nodes: function(client: table, input: table): function(): table, table
    items_list_nodes: function(client: table, input: table): function(): any
    pages_list_replicators: function(client: table, input: table): function(): table, table
    items_list_replicators: function(client: table, input: table): function(): any
    pages_list_scram_secrets: function(client: table, input: table): function(): table, table
    items_list_scram_secrets: function(client: table, input: table): function(): any
    pages_list_topics: function(client: table, input: table): function(): table, table
    items_list_topics: function(client: table, input: table): function(): any
    pages_list_vpc_connections: function(client: table, input: table): function(): table, table
    items_list_vpc_connections: function(client: table, input: table): function(): any
end

return M
