-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("iotmanagedintegrations.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("iotmanagedintegrations.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "IotManagedIntegrations"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "iotmanagedintegrations", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateAccountAssociation, input, options)
end

function Client:createCloudConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCloudConnector, input, options)
end

function Client:createConnectorDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConnectorDestination, input, options)
end

function Client:createCredentialLocker(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCredentialLocker, input, options)
end

function Client:createDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateDestination, input, options)
end

function Client:createEventLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateEventLogConfiguration, input, options)
end

function Client:createManagedThing(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateManagedThing, input, options)
end

function Client:createNotificationConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateNotificationConfiguration, input, options)
end

function Client:createOtaTask(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateOtaTask, input, options)
end

function Client:createOtaTaskConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateOtaTaskConfiguration, input, options)
end

function Client:createProvisioningProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateProvisioningProfile, input, options)
end

function Client:deleteAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAccountAssociation, input, options)
end

function Client:deleteCloudConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCloudConnector, input, options)
end

function Client:deleteConnectorDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConnectorDestination, input, options)
end

function Client:deleteCredentialLocker(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCredentialLocker, input, options)
end

function Client:deleteDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteDestination, input, options)
end

function Client:deleteEventLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteEventLogConfiguration, input, options)
end

function Client:deleteManagedThing(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteManagedThing, input, options)
end

function Client:deleteNotificationConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteNotificationConfiguration, input, options)
end

function Client:deleteOtaTask(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteOtaTask, input, options)
end

function Client:deleteOtaTaskConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteOtaTaskConfiguration, input, options)
end

function Client:deleteProvisioningProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteProvisioningProfile, input, options)
end

function Client:deregisterAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeregisterAccountAssociation, input, options)
end

function Client:getAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetAccountAssociation, input, options)
end

function Client:getCloudConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCloudConnector, input, options)
end

function Client:getConnectorDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetConnectorDestination, input, options)
end

function Client:getCredentialLocker(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCredentialLocker, input, options)
end

function Client:getCustomEndpoint(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCustomEndpoint, input, options)
end

function Client:getDefaultEncryptionConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetDefaultEncryptionConfiguration, input, options)
end

function Client:getDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetDestination, input, options)
end

function Client:getDeviceDiscovery(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetDeviceDiscovery, input, options)
end

function Client:getEventLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetEventLogConfiguration, input, options)
end

function Client:getHubConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHubConfiguration, input, options)
end

function Client:getManagedThing(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThing, input, options)
end

function Client:getManagedThingCapabilities(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThingCapabilities, input, options)
end

function Client:getManagedThingCertificate(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThingCertificate, input, options)
end

function Client:getManagedThingConnectivityData(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThingConnectivityData, input, options)
end

function Client:getManagedThingMetaData(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThingMetaData, input, options)
end

function Client:getManagedThingState(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetManagedThingState, input, options)
end

function Client:getNotificationConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetNotificationConfiguration, input, options)
end

function Client:getOtaTask(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetOtaTask, input, options)
end

function Client:getOtaTaskConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetOtaTaskConfiguration, input, options)
end

function Client:getProvisioningProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetProvisioningProfile, input, options)
end

function Client:getRuntimeLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetRuntimeLogConfiguration, input, options)
end

function Client:getSchemaVersion(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetSchemaVersion, input, options)
end

function Client:listAccountAssociations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAccountAssociations, input, options)
end

function Client:listCloudConnectors(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCloudConnectors, input, options)
end

function Client:listConnectorDestinations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConnectorDestinations, input, options)
end

function Client:listCredentialLockers(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCredentialLockers, input, options)
end

function Client:listDestinations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListDestinations, input, options)
end

function Client:listDeviceDiscoveries(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListDeviceDiscoveries, input, options)
end

function Client:listDiscoveredDevices(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListDiscoveredDevices, input, options)
end

function Client:listEventLogConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListEventLogConfigurations, input, options)
end

function Client:listManagedThingAccountAssociations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListManagedThingAccountAssociations, input, options)
end

function Client:listManagedThings(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListManagedThings, input, options)
end

function Client:listManagedThingSchemas(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListManagedThingSchemas, input, options)
end

function Client:listNotificationConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListNotificationConfigurations, input, options)
end

function Client:listOtaTaskConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListOtaTaskConfigurations, input, options)
end

function Client:listOtaTaskExecutions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListOtaTaskExecutions, input, options)
end

function Client:listOtaTasks(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListOtaTasks, input, options)
end

function Client:listProvisioningProfiles(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListProvisioningProfiles, input, options)
end

function Client:listSchemaVersions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListSchemaVersions, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:putDefaultEncryptionConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutDefaultEncryptionConfiguration, input, options)
end

function Client:putHubConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutHubConfiguration, input, options)
end

function Client:putRuntimeLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutRuntimeLogConfiguration, input, options)
end

function Client:registerAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.RegisterAccountAssociation, input, options)
end

function Client:registerCustomEndpoint(input, options)
    return self:invokeOperation(schemas.Service, schemas.RegisterCustomEndpoint, input, options)
end

function Client:resetRuntimeLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.ResetRuntimeLogConfiguration, input, options)
end

function Client:sendConnectorEvent(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendConnectorEvent, input, options)
end

function Client:sendManagedThingCommand(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendManagedThingCommand, input, options)
end

function Client:startAccountAssociationRefresh(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartAccountAssociationRefresh, input, options)
end

function Client:startDeviceDiscovery(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartDeviceDiscovery, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateAccountAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateAccountAssociation, input, options)
end

function Client:updateCloudConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateCloudConnector, input, options)
end

function Client:updateConnectorDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateConnectorDestination, input, options)
end

function Client:updateDestination(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateDestination, input, options)
end

function Client:updateEventLogConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateEventLogConfiguration, input, options)
end

function Client:updateManagedThing(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateManagedThing, input, options)
end

function Client:updateNotificationConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateNotificationConfiguration, input, options)
end

function Client:updateOtaTask(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateOtaTask, input, options)
end

return M
