local M = {}

M.AbortCriteriaAction = {
    CANCEL = "CANCEL",
}

M.AbortCriteriaFailureType = {
    FAILED = "FAILED",
    REJECTED = "REJECTED",
    TIMED_OUT = "TIMED_OUT",
    ALL = "ALL",
}

M.AssociationState = {
    ASSOCIATION_IN_PROGRESS = "ASSOCIATION_IN_PROGRESS",
    ASSOCIATION_FAILED = "ASSOCIATION_FAILED",
    ASSOCIATION_SUCCEEDED = "ASSOCIATION_SUCCEEDED",
    ASSOCIATION_DELETING = "ASSOCIATION_DELETING",
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
}

M.TokenEndpointAuthenticationScheme = {
    HTTP_BASIC = "HTTP_BASIC",
    REQUEST_BODY_CREDENTIALS = "REQUEST_BODY_CREDENTIALS",
}

M.AuthMaterialType = {
    CUSTOM_PROTOCOL_QR_BAR_CODE = "CUSTOM_PROTOCOL_QR_BAR_CODE",
    WIFI_SETUP_QR_BAR_CODE = "WIFI_SETUP_QR_BAR_CODE",
    ZWAVE_QR_BAR_CODE = "ZWAVE_QR_BAR_CODE",
    ZIGBEE_QR_BAR_CODE = "ZIGBEE_QR_BAR_CODE",
    DISCOVERED_DEVICE = "DISCOVERED_DEVICE",
    PRE_ONBOARDED_CLOUD = "PRE_ONBOARDED_CLOUD",
}

M.AuthType = {
    OAUTH = "OAUTH",
}

M.SchemaVersionFormat = {
    AWS = "AWS",
    ZCL = "ZCL",
    CONNECTOR = "CONNECTOR",
}

M.EndpointType = {
    LAMBDA = "LAMBDA",
}

M.CloudConnectorType = {
    LISTED = "LISTED",
    UNLISTED = "UNLISTED",
}

M.ConfigurationState = {
    ENABLED = "ENABLED",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.ConnectorEventOperation = {
    DEVICE_COMMAND_RESPONSE = "DEVICE_COMMAND_RESPONSE",
    DEVICE_DISCOVERY = "DEVICE_DISCOVERY",
    DEVICE_EVENT = "DEVICE_EVENT",
    DEVICE_COMMAND_REQUEST = "DEVICE_COMMAND_REQUEST",
}

M.DeliveryDestinationType = {
    KINESIS = "KINESIS",
}

M.LogLevel = {
    DEBUG = "DEBUG",
    ERROR = "ERROR",
    INFO = "INFO",
    WARN = "WARN",
}

M.Role = {
    CONTROLLER = "CONTROLLER",
    DEVICE = "DEVICE",
}

M.EventType = {
    DEVICE_COMMAND = "DEVICE_COMMAND",
    DEVICE_COMMAND_REQUEST = "DEVICE_COMMAND_REQUEST",
    DEVICE_DISCOVERY_STATUS = "DEVICE_DISCOVERY_STATUS",
    DEVICE_EVENT = "DEVICE_EVENT",
    DEVICE_LIFE_CYCLE = "DEVICE_LIFE_CYCLE",
    DEVICE_STATE = "DEVICE_STATE",
    DEVICE_OTA = "DEVICE_OTA",
    DEVICE_WSS = "DEVICE_WSS",
    CONNECTOR_ASSOCIATION = "CONNECTOR_ASSOCIATION",
    ACCOUNT_ASSOCIATION = "ACCOUNT_ASSOCIATION",
    CONNECTOR_ERROR_REPORT = "CONNECTOR_ERROR_REPORT",
}

M.OtaMechanism = {
    PUSH = "PUSH",
}

M.SchedulingConfigEndBehavior = {
    STOP_ROLLOUT = "STOP_ROLLOUT",
    CANCEL = "CANCEL",
    FORCE_CANCEL = "FORCE_CANCEL",
}

M.RetryCriteriaFailureType = {
    FAILED = "FAILED",
    TIMED_OUT = "TIMED_OUT",
    ALL = "ALL",
}

M.OtaType = {
    ONE_TIME = "ONE_TIME",
    CONTINUOUS = "CONTINUOUS",
}

M.OtaProtocol = {
    HTTP = "HTTP",
}

M.ProvisioningType = {
    FLEET_PROVISIONING = "FLEET_PROVISIONING",
    JITR = "JITR",
}

M.ProvisioningProfileStatus = {
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_FAILED = "CREATE_FAILED",
    CREATED = "CREATED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    DELETE_FAILED = "DELETE_FAILED",
}

M.DiscoveryType = {
    ZWAVE = "ZWAVE",
    ZIGBEE = "ZIGBEE",
    CLOUD = "CLOUD",
    CUSTOM = "CUSTOM",
    CONTROLLER_CAPABILITY_REDISCOVERY = "CONTROLLER_CAPABILITY_REDISCOVERY",
}

M.DeviceDiscoveryStatus = {
    RUNNING = "RUNNING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    TIMED_OUT = "TIMED_OUT",
}

M.DiscoveryModification = {
    DISCOVERED = "DISCOVERED",
    UPDATED = "UPDATED",
    NO_CHANGE = "NO_CHANGE",
}

M.DiscoveryAuthMaterialType = {
    ZWAVE_INSTALL_CODE = "ZWAVE_INSTALL_CODE",
}

M.ProtocolType = {
    ZWAVE = "ZWAVE",
    ZIGBEE = "ZIGBEE",
    CUSTOM = "CUSTOM",
}

M.DisconnectReasonValue = {
    AUTH_ERROR = "AUTH_ERROR",
    CLIENT_INITIATED_DISCONNECT = "CLIENT_INITIATED_DISCONNECT",
    CLIENT_ERROR = "CLIENT_ERROR",
    CONNECTION_LOST = "CONNECTION_LOST",
    DUPLICATE_CLIENTID = "DUPLICATE_CLIENTID",
    FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS",
    MQTT_KEEP_ALIVE_TIMEOUT = "MQTT_KEEP_ALIVE_TIMEOUT",
    SERVER_ERROR = "SERVER_ERROR",
    SERVER_INITIATED_DISCONNECT = "SERVER_INITIATED_DISCONNECT",
    THROTTLED = "THROTTLED",
    WEBSOCKET_TTL_EXPIRATION = "WEBSOCKET_TTL_EXPIRATION",
    CUSTOMAUTH_TTL_EXPIRATION = "CUSTOMAUTH_TTL_EXPIRATION",
    UNKNOWN = "UNKNOWN",
    NONE = "NONE",
}

M.EncryptionType = {
    MANAGED_INTEGRATIONS_DEFAULT_ENCRYPTION = "MANAGED_INTEGRATIONS_DEFAULT_ENCRYPTION",
    CUSTOMER_KEY_ENCRYPTION = "CUSTOMER_KEY_ENCRYPTION",
}

M.HubNetworkMode = {
    STANDARD = "STANDARD",
    NETWORK_WIDE_EXCLUSION = "NETWORK_WIDE_EXCLUSION",
}

M.ProvisioningStatus = {
    UNASSOCIATED = "UNASSOCIATED",
    PRE_ASSOCIATED = "PRE_ASSOCIATED",
    DISCOVERED = "DISCOVERED",
    ACTIVATED = "ACTIVATED",
    DELETION_FAILED = "DELETION_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    ISOLATED = "ISOLATED",
    DELETED = "DELETED",
}

M.OtaStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    CANCELED = "CANCELED",
    COMPLETED = "COMPLETED",
    DELETION_IN_PROGRESS = "DELETION_IN_PROGRESS",
    SCHEDULED = "SCHEDULED",
}

M.SchemaVersionType = {
    CAPABILITY = "capability",
    DEFINITION = "definition",
}

M.SchemaVersionVisibility = {
    PUBLIC = "PUBLIC",
    PRIVATE = "PRIVATE",
}

M.ManagedThingAssociationStatus = {
    PRE_ASSOCIATED = "PRE_ASSOCIATED",
    ASSOCIATED = "ASSOCIATED",
}

M.OtaTaskExecutionStatus = {
    QUEUED = "QUEUED",
    IN_PROGRESS = "IN_PROGRESS",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    TIMED_OUT = "TIMED_OUT",
    REJECTED = "REJECTED",
    REMOVED = "REMOVED",
    CANCELED = "CANCELED",
}

return M
