-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.MonitorLocalResourceType = {
    AWS_VPC = "AWS::EC2::VPC",
    AWS_AZ = "AWS::AvailabilityZone",
    AWS_SUBNET = "AWS::EC2::Subnet",
    AWS_REGION = "AWS::Region",
    EKS_CLUSTER = "AWS::EKS::Cluster",
}

M.MonitorRemoteResourceType = {
    AWS_VPC = "AWS::EC2::VPC",
    AWS_AZ = "AWS::AvailabilityZone",
    AWS_SUBNET = "AWS::EC2::Subnet",
    AWS_SERVICE = "AWS::AWSService",
    AWS_REGION = "AWS::Region",
}

M.MonitorStatus = {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    ERROR = "ERROR",
    DELETING = "DELETING",
}

M.TargetType = {
    ACCOUNT = "ACCOUNT",
}

M.ScopeStatus = {
    SUCCEEDED = "SUCCEEDED",
    IN_PROGRESS = "IN_PROGRESS",
    FAILED = "FAILED",
    DEACTIVATING = "DEACTIVATING",
    DEACTIVATED = "DEACTIVATED",
}

M.DestinationCategory = {
    INTRA_AZ = "INTRA_AZ",
    INTER_AZ = "INTER_AZ",
    INTER_VPC = "INTER_VPC",
    UNCLASSIFIED = "UNCLASSIFIED",
    AMAZON_S3 = "AMAZON_S3",
    AMAZON_DYNAMODB = "AMAZON_DYNAMODB",
    INTER_REGION = "INTER_REGION",
}

M.MetricUnit = {
    SECONDS = "Seconds",
    MICROSECONDS = "Microseconds",
    MILLISECONDS = "Milliseconds",
    BYTES = "Bytes",
    KILOBYTES = "Kilobytes",
    MEGABYTES = "Megabytes",
    GIGABYTES = "Gigabytes",
    TERABYTES = "Terabytes",
    BITS = "Bits",
    KILOBITS = "Kilobits",
    MEGABITS = "Megabits",
    GIGABITS = "Gigabits",
    TERABITS = "Terabits",
    PERCENT = "Percent",
    COUNT = "Count",
    BYTES_PER_SECOND = "Bytes/Second",
    KILOBYTES_PER_SECOND = "Kilobytes/Second",
    MEGABYTES_PER_SECOND = "Megabytes/Second",
    GIGABYTES_PER_SECOND = "Gigabytes/Second",
    TERABYTES_PER_SECOND = "Terabytes/Second",
    BITS_PER_SECOND = "Bits/Second",
    KILOBITS_PER_SECOND = "Kilobits/Second",
    MEGABITS_PER_SECOND = "Megabits/Second",
    GIGABITS_PER_SECOND = "Gigabits/Second",
    TERABITS_PER_SECOND = "Terabits/Second",
    COUNT_PER_SECOND = "Count/Second",
    NONE = "None",
}

M.QueryStatus = {
    QUEUED = "QUEUED",
    RUNNING = "RUNNING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
}

M.MonitorMetric = {
    ROUND_TRIP_TIME = "ROUND_TRIP_TIME",
    TIMEOUTS = "TIMEOUTS",
    RETRANSMISSIONS = "RETRANSMISSIONS",
    DATA_TRANSFERRED = "DATA_TRANSFERRED",
}

M.WorkloadInsightsMetric = {
    TIMEOUTS = "TIMEOUTS",
    RETRANSMISSIONS = "RETRANSMISSIONS",
    DATA_TRANSFERRED = "DATA_TRANSFERRED",
}

return M
