-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("route53recoveryreadiness.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("route53recoveryreadiness.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "Route53RecoveryReadiness"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "route53-recovery-readiness", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createCell(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCell, input, options)
end

function Client:createCrossAccountAuthorization(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCrossAccountAuthorization, input, options)
end

function Client:createReadinessCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateReadinessCheck, input, options)
end

function Client:createRecoveryGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateRecoveryGroup, input, options)
end

function Client:createResourceSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateResourceSet, input, options)
end

function Client:deleteCell(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCell, input, options)
end

function Client:deleteCrossAccountAuthorization(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCrossAccountAuthorization, input, options)
end

function Client:deleteReadinessCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteReadinessCheck, input, options)
end

function Client:deleteRecoveryGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteRecoveryGroup, input, options)
end

function Client:deleteResourceSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteResourceSet, input, options)
end

function Client:getArchitectureRecommendations(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetArchitectureRecommendations, input, options)
end

function Client:getCell(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCell, input, options)
end

function Client:getCellReadinessSummary(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCellReadinessSummary, input, options)
end

function Client:getReadinessCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetReadinessCheck, input, options)
end

function Client:getReadinessCheckResourceStatus(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetReadinessCheckResourceStatus, input, options)
end

function Client:getReadinessCheckStatus(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetReadinessCheckStatus, input, options)
end

function Client:getRecoveryGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetRecoveryGroup, input, options)
end

function Client:getRecoveryGroupReadinessSummary(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetRecoveryGroupReadinessSummary, input, options)
end

function Client:getResourceSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetResourceSet, input, options)
end

function Client:listCells(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCells, input, options)
end

function Client:listCrossAccountAuthorizations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCrossAccountAuthorizations, input, options)
end

function Client:listReadinessChecks(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListReadinessChecks, input, options)
end

function Client:listRecoveryGroups(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListRecoveryGroups, input, options)
end

function Client:listResourceSets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListResourceSets, input, options)
end

function Client:listRules(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListRules, input, options)
end

function Client:listTagsForResources(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResources, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateCell(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateCell, input, options)
end

function Client:updateReadinessCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateReadinessCheck, input, options)
end

function Client:updateRecoveryGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateRecoveryGroup, input, options)
end

function Client:updateResourceSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateResourceSet, input, options)
end

return M
