local record M
    pages_get_behavior_model_training_summaries: function(client: table, input: table): function(): table, table
    items_get_behavior_model_training_summaries: function(client: table, input: table): function(): any
    pages_list_active_violations: function(client: table, input: table): function(): table, table
    items_list_active_violations: function(client: table, input: table): function(): any
    pages_list_attached_policies: function(client: table, input: table): function(): table, table
    items_list_attached_policies: function(client: table, input: table): function(): any
    pages_list_audit_findings: function(client: table, input: table): function(): table, table
    items_list_audit_findings: function(client: table, input: table): function(): any
    pages_list_audit_mitigation_actions_executions: function(client: table, input: table): function(): table, table
    items_list_audit_mitigation_actions_executions: function(client: table, input: table): function(): any
    pages_list_audit_mitigation_actions_tasks: function(client: table, input: table): function(): table, table
    items_list_audit_mitigation_actions_tasks: function(client: table, input: table): function(): any
    pages_list_audit_suppressions: function(client: table, input: table): function(): table, table
    items_list_audit_suppressions: function(client: table, input: table): function(): any
    pages_list_audit_tasks: function(client: table, input: table): function(): table, table
    items_list_audit_tasks: function(client: table, input: table): function(): any
    pages_list_authorizers: function(client: table, input: table): function(): table, table
    items_list_authorizers: function(client: table, input: table): function(): any
    pages_list_billing_groups: function(client: table, input: table): function(): table, table
    items_list_billing_groups: function(client: table, input: table): function(): any
    pages_list_c_a_certificates: function(client: table, input: table): function(): table, table
    items_list_c_a_certificates: function(client: table, input: table): function(): any
    pages_list_certificates: function(client: table, input: table): function(): table, table
    items_list_certificates: function(client: table, input: table): function(): any
    pages_list_certificates_by_c_a: function(client: table, input: table): function(): table, table
    items_list_certificates_by_c_a: function(client: table, input: table): function(): any
    pages_list_command_executions: function(client: table, input: table): function(): table, table
    items_list_command_executions: function(client: table, input: table): function(): any
    pages_list_commands: function(client: table, input: table): function(): table, table
    items_list_commands: function(client: table, input: table): function(): any
    pages_list_custom_metrics: function(client: table, input: table): function(): table, table
    items_list_custom_metrics: function(client: table, input: table): function(): any
    pages_list_detect_mitigation_actions_executions: function(client: table, input: table): function(): table, table
    items_list_detect_mitigation_actions_executions: function(client: table, input: table): function(): any
    pages_list_detect_mitigation_actions_tasks: function(client: table, input: table): function(): table, table
    items_list_detect_mitigation_actions_tasks: function(client: table, input: table): function(): any
    pages_list_dimensions: function(client: table, input: table): function(): table, table
    items_list_dimensions: function(client: table, input: table): function(): any
    pages_list_domain_configurations: function(client: table, input: table): function(): table, table
    items_list_domain_configurations: function(client: table, input: table): function(): any
    pages_list_fleet_metrics: function(client: table, input: table): function(): table, table
    items_list_fleet_metrics: function(client: table, input: table): function(): any
    pages_list_indices: function(client: table, input: table): function(): table, table
    items_list_indices: function(client: table, input: table): function(): any
    pages_list_job_executions_for_job: function(client: table, input: table): function(): table, table
    items_list_job_executions_for_job: function(client: table, input: table): function(): any
    pages_list_job_executions_for_thing: function(client: table, input: table): function(): table, table
    items_list_job_executions_for_thing: function(client: table, input: table): function(): any
    pages_list_job_templates: function(client: table, input: table): function(): table, table
    items_list_job_templates: function(client: table, input: table): function(): any
    pages_list_jobs: function(client: table, input: table): function(): table, table
    items_list_jobs: function(client: table, input: table): function(): any
    pages_list_managed_job_templates: function(client: table, input: table): function(): table, table
    items_list_managed_job_templates: function(client: table, input: table): function(): any
    pages_list_metric_values: function(client: table, input: table): function(): table, table
    items_list_metric_values: function(client: table, input: table): function(): any
    pages_list_mitigation_actions: function(client: table, input: table): function(): table, table
    items_list_mitigation_actions: function(client: table, input: table): function(): any
    pages_list_o_t_a_updates: function(client: table, input: table): function(): table, table
    items_list_o_t_a_updates: function(client: table, input: table): function(): any
    pages_list_outgoing_certificates: function(client: table, input: table): function(): table, table
    items_list_outgoing_certificates: function(client: table, input: table): function(): any
    pages_list_package_versions: function(client: table, input: table): function(): table, table
    items_list_package_versions: function(client: table, input: table): function(): any
    pages_list_packages: function(client: table, input: table): function(): table, table
    items_list_packages: function(client: table, input: table): function(): any
    pages_list_policies: function(client: table, input: table): function(): table, table
    items_list_policies: function(client: table, input: table): function(): any
    pages_list_policy_principals: function(client: table, input: table): function(): table, table
    items_list_policy_principals: function(client: table, input: table): function(): any
    pages_list_principal_policies: function(client: table, input: table): function(): table, table
    items_list_principal_policies: function(client: table, input: table): function(): any
    pages_list_principal_things: function(client: table, input: table): function(): table, table
    items_list_principal_things: function(client: table, input: table): function(): any
    pages_list_principal_things_v2: function(client: table, input: table): function(): table, table
    items_list_principal_things_v2: function(client: table, input: table): function(): any
    pages_list_provisioning_template_versions: function(client: table, input: table): function(): table, table
    items_list_provisioning_template_versions: function(client: table, input: table): function(): any
    pages_list_provisioning_templates: function(client: table, input: table): function(): table, table
    items_list_provisioning_templates: function(client: table, input: table): function(): any
    pages_list_related_resources_for_audit_finding: function(client: table, input: table): function(): table, table
    items_list_related_resources_for_audit_finding: function(client: table, input: table): function(): any
    pages_list_role_aliases: function(client: table, input: table): function(): table, table
    items_list_role_aliases: function(client: table, input: table): function(): any
    pages_list_sbom_validation_results: function(client: table, input: table): function(): table, table
    items_list_sbom_validation_results: function(client: table, input: table): function(): any
    pages_list_scheduled_audits: function(client: table, input: table): function(): table, table
    items_list_scheduled_audits: function(client: table, input: table): function(): any
    pages_list_security_profiles: function(client: table, input: table): function(): table, table
    items_list_security_profiles: function(client: table, input: table): function(): any
    pages_list_security_profiles_for_target: function(client: table, input: table): function(): table, table
    items_list_security_profiles_for_target: function(client: table, input: table): function(): any
    pages_list_streams: function(client: table, input: table): function(): table, table
    items_list_streams: function(client: table, input: table): function(): any
    pages_list_tags_for_resource: function(client: table, input: table): function(): table, table
    items_list_tags_for_resource: function(client: table, input: table): function(): any
    pages_list_targets_for_policy: function(client: table, input: table): function(): table, table
    items_list_targets_for_policy: function(client: table, input: table): function(): any
    pages_list_targets_for_security_profile: function(client: table, input: table): function(): table, table
    items_list_targets_for_security_profile: function(client: table, input: table): function(): any
    pages_list_thing_groups: function(client: table, input: table): function(): table, table
    items_list_thing_groups: function(client: table, input: table): function(): any
    pages_list_thing_groups_for_thing: function(client: table, input: table): function(): table, table
    items_list_thing_groups_for_thing: function(client: table, input: table): function(): any
    pages_list_thing_principals: function(client: table, input: table): function(): table, table
    items_list_thing_principals: function(client: table, input: table): function(): any
    pages_list_thing_principals_v2: function(client: table, input: table): function(): table, table
    items_list_thing_principals_v2: function(client: table, input: table): function(): any
    pages_list_thing_registration_task_reports: function(client: table, input: table): function(): table, table
    items_list_thing_registration_task_reports: function(client: table, input: table): function(): any
    pages_list_thing_registration_tasks: function(client: table, input: table): function(): table, table
    items_list_thing_registration_tasks: function(client: table, input: table): function(): any
    pages_list_thing_types: function(client: table, input: table): function(): table, table
    items_list_thing_types: function(client: table, input: table): function(): any
    pages_list_things: function(client: table, input: table): function(): table, table
    items_list_things: function(client: table, input: table): function(): any
    pages_list_things_in_billing_group: function(client: table, input: table): function(): table, table
    items_list_things_in_billing_group: function(client: table, input: table): function(): any
    pages_list_things_in_thing_group: function(client: table, input: table): function(): table, table
    items_list_things_in_thing_group: function(client: table, input: table): function(): any
    pages_list_topic_rule_destinations: function(client: table, input: table): function(): table, table
    items_list_topic_rule_destinations: function(client: table, input: table): function(): any
    pages_list_topic_rules: function(client: table, input: table): function(): table, table
    items_list_topic_rules: function(client: table, input: table): function(): any
    pages_list_v2_logging_levels: function(client: table, input: table): function(): table, table
    items_list_v2_logging_levels: function(client: table, input: table): function(): any
    pages_list_violation_events: function(client: table, input: table): function(): table, table
    items_list_violation_events: function(client: table, input: table): function(): any
end

return M
