local M = {}

M.AccessDeniedExceptionErrorCode = {
    INCOMPATIBLE_BENEFIT_AWS_PARTNER_STATE = "INCOMPATIBLE_BENEFIT_AWS_PARTNER_STATE",
}

M.ValidationExceptionErrorCode = {
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING",
    INVALID_ENUM_VALUE = "INVALID_ENUM_VALUE",
    INVALID_STRING_FORMAT = "INVALID_STRING_FORMAT",
    INVALID_VALUE = "INVALID_VALUE",
    NOT_ENOUGH_VALUES = "NOT_ENOUGH_VALUES",
    TOO_MANY_VALUES = "TOO_MANY_VALUES",
    INVALID_RESOURCE_STATE = "INVALID_RESOURCE_STATE",
    DUPLICATE_KEY_VALUE = "DUPLICATE_KEY_VALUE",
    VALUE_OUT_OF_RANGE = "VALUE_OUT_OF_RANGE",
    ACTION_NOT_PERMITTED = "ACTION_NOT_PERMITTED",
}

M.ValidationExceptionReason = {
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED",
    BUSINESS_VALIDATION_FAILED = "BUSINESS_VALIDATION_FAILED",
}

M.CountryCode = {
    US = "US",
    AF = "AF",
    AX = "AX",
    AL = "AL",
    DZ = "DZ",
    AS = "AS",
    AD = "AD",
    AO = "AO",
    AI = "AI",
    AQ = "AQ",
    AG = "AG",
    AR = "AR",
    AM = "AM",
    AW = "AW",
    AU = "AU",
    AT = "AT",
    AZ = "AZ",
    BS = "BS",
    BH = "BH",
    BD = "BD",
    BB = "BB",
    BY = "BY",
    BE = "BE",
    BZ = "BZ",
    BJ = "BJ",
    BM = "BM",
    BT = "BT",
    BO = "BO",
    BQ = "BQ",
    BA = "BA",
    BW = "BW",
    BV = "BV",
    BR = "BR",
    IO = "IO",
    BN = "BN",
    BG = "BG",
    BF = "BF",
    BI = "BI",
    KH = "KH",
    CM = "CM",
    CA = "CA",
    CV = "CV",
    KY = "KY",
    CF = "CF",
    TD = "TD",
    CL = "CL",
    CN = "CN",
    CX = "CX",
    CC = "CC",
    CO = "CO",
    KM = "KM",
    CG = "CG",
    CK = "CK",
    CR = "CR",
    CI = "CI",
    HR = "HR",
    CU = "CU",
    CW = "CW",
    CY = "CY",
    CZ = "CZ",
    CD = "CD",
    DK = "DK",
    DJ = "DJ",
    DM = "DM",
    DO = "DO",
    EC = "EC",
    EG = "EG",
    SV = "SV",
    GQ = "GQ",
    ER = "ER",
    EE = "EE",
    ET = "ET",
    FK = "FK",
    FO = "FO",
    FJ = "FJ",
    FI = "FI",
    FR = "FR",
    GF = "GF",
    PF = "PF",
    TF = "TF",
    GA = "GA",
    GM = "GM",
    GE = "GE",
    DE = "DE",
    GH = "GH",
    GI = "GI",
    GR = "GR",
    GL = "GL",
    GD = "GD",
    GP = "GP",
    GU = "GU",
    GT = "GT",
    GG = "GG",
    GN = "GN",
    GW = "GW",
    GY = "GY",
    HT = "HT",
    HM = "HM",
    VA = "VA",
    HN = "HN",
    HK = "HK",
    HU = "HU",
    IS = "IS",
    IN = "IN",
    ID = "ID",
    IR = "IR",
    IQ = "IQ",
    IE = "IE",
    IM = "IM",
    IL = "IL",
    IT = "IT",
    JM = "JM",
    JP = "JP",
    JE = "JE",
    JO = "JO",
    KZ = "KZ",
    KE = "KE",
    KI = "KI",
    KR = "KR",
    KW = "KW",
    KG = "KG",
    LA = "LA",
    LV = "LV",
    LB = "LB",
    LS = "LS",
    LR = "LR",
    LY = "LY",
    LI = "LI",
    LT = "LT",
    LU = "LU",
    MO = "MO",
    MK = "MK",
    MG = "MG",
    MW = "MW",
    MY = "MY",
    MV = "MV",
    ML = "ML",
    MT = "MT",
    MH = "MH",
    MQ = "MQ",
    MR = "MR",
    MU = "MU",
    YT = "YT",
    MX = "MX",
    FM = "FM",
    MD = "MD",
    MC = "MC",
    MN = "MN",
    ME = "ME",
    MS = "MS",
    MA = "MA",
    MZ = "MZ",
    MM = "MM",
    NA = "NA",
    NR = "NR",
    NP = "NP",
    NL = "NL",
    AN = "AN",
    NC = "NC",
    NZ = "NZ",
    NI = "NI",
    NE = "NE",
    NG = "NG",
    NU = "NU",
    NF = "NF",
    MP = "MP",
    NO = "NO",
    OM = "OM",
    PK = "PK",
    PW = "PW",
    PS = "PS",
    PA = "PA",
    PG = "PG",
    PY = "PY",
    PE = "PE",
    PH = "PH",
    PN = "PN",
    PL = "PL",
    PT = "PT",
    PR = "PR",
    QA = "QA",
    RE = "RE",
    RO = "RO",
    RU = "RU",
    RW = "RW",
    BL = "BL",
    SH = "SH",
    KN = "KN",
    LC = "LC",
    MF = "MF",
    PM = "PM",
    VC = "VC",
    WS = "WS",
    SM = "SM",
    ST = "ST",
    SA = "SA",
    SN = "SN",
    RS = "RS",
    SC = "SC",
    SL = "SL",
    SG = "SG",
    SX = "SX",
    SK = "SK",
    SI = "SI",
    SB = "SB",
    SO = "SO",
    ZA = "ZA",
    GS = "GS",
    SS = "SS",
    ES = "ES",
    LK = "LK",
    SD = "SD",
    SR = "SR",
    SJ = "SJ",
    SZ = "SZ",
    SE = "SE",
    CH = "CH",
    SY = "SY",
    TW = "TW",
    TJ = "TJ",
    TZ = "TZ",
    TH = "TH",
    TL = "TL",
    TG = "TG",
    TK = "TK",
    TO = "TO",
    TT = "TT",
    TN = "TN",
    TR = "TR",
    TM = "TM",
    TC = "TC",
    TV = "TV",
    UG = "UG",
    UA = "UA",
    AE = "AE",
    GB = "GB",
    UM = "UM",
    UY = "UY",
    UZ = "UZ",
    VU = "VU",
    VE = "VE",
    VN = "VN",
    VG = "VG",
    VI = "VI",
    WF = "WF",
    EH = "EH",
    YE = "YE",
    ZM = "ZM",
    ZW = "ZW",
}

M.Industry = {
    AEROSPACE_SATELLITE = "Aerospace",
    AGRICULTURE = "Agriculture",
    AUTOMOTIVE = "Automotive",
    COMPUTERS_ELECTRONICS = "Computers and Electronics",
    CONSUMER_GOODS = "Consumer Goods",
    EDUCATION = "Education",
    ENERGY_OIL_GAS = "Energy - Oil and Gas",
    ENERGY_POWER_UTILITIES = "Energy - Power and Utilities",
    FINANCIAL_SERVICES = "Financial Services",
    GAMING = "Gaming",
    GOVERNMENT = "Government",
    HEALTHCARE = "Healthcare",
    HOSPITALITY = "Hospitality",
    LIFE_SCIENCES = "Life Sciences",
    MANUFACTURING = "Manufacturing",
    MARKETING_ADVERTISING = "Marketing and Advertising",
    MEDIA_ENTERTAINMENT = "Media and Entertainment",
    MINING = "Mining",
    NON_PROFIT_ORGANIZATION = "Non-Profit Organization",
    PROFESSIONAL_SERVICES = "Professional Services",
    REALESTATE_CONSTRUCTION = "Real Estate and Construction",
    RETAIL = "Retail",
    SOFTWARE_INTERNET = "Software and Internet",
    TELECOMMUNICATIONS = "Telecommunications",
    TRANSPORTATION_LOGISTICS = "Transportation and Logistics",
    TRAVEL = "Travel",
    WHOLESALE_DISTRIBUTION = "Wholesale and Distribution",
    OTHER = "Other",
}

M.RelatedEntityType = {
    SOLUTIONS = "Solutions",
    AWS_PRODUCTS = "AwsProducts",
    AWS_MARKETPLACE_OFFERS = "AwsMarketplaceOffers",
    AWS_MARKETPLACE_OFFER_SETS = "AwsMarketplaceOfferSets",
}

M.AwsClosedLostReason = {
    ADMINISTRATIVE = "Administrative",
    BUSINESS_ASSOCIATE_AGREEMENT = "Business Associate Agreement",
    COMPANY_ACQUIRED_DISSOLVED = "Company Acquired/Dissolved",
    COMPETITIVE_OFFERING = "Competitive Offering",
    CUSTOMER_DATA_REQUIREMENT = "Customer Data Requirement",
    CUSTOMER_DEFICIENCY = "Customer Deficiency",
    CUSTOMER_EXPERIENCE = "Customer Experience",
    DELAY_CANCELLATION_OF_PROJECT = "Delay / Cancellation of Project",
    DUPLICATE = "Duplicate",
    DUPLICATE_OPPORTUNITY = "Duplicate Opportunity",
    EXECUTIVE_BLOCKER = "Executive Blocker",
    FAILED_VETTING = "Failed Vetting",
    FEATURE_LIMITATION = "Feature Limitation",
    FINANCIAL_COMMERCIAL = "Financial/Commercial",
    INSUFFICIENT_AMAZON_VALUE = "Insufficient Amazon Value",
    INSUFFICIENT_AWS_VALUE = "Insufficient AWS Value",
    INTERNATIONAL_CONSTRAINTS = "International Constraints",
    LEGAL_TAX_REGULATORY = "Legal / Tax / Regulatory",
    LEGAL_TERMS_AND_CONDITIONS = "Legal Terms and Conditions",
    LOST_TO_COMPETITOR = "Lost to Competitor",
    LOST_TO_COMPETITOR_GOOGLE = "Lost to Competitor - Google",
    LOST_TO_COMPETITOR_MICROSOFT = "Lost to Competitor - Microsoft",
    LOST_TO_COMPETITOR_OTHER = "Lost to Competitor - Other",
    LOST_TO_COMPETITOR_RACKSPACE = "Lost to Competitor - Rackspace",
    LOST_TO_COMPETITOR_SOFTLAYER = "Lost to Competitor - SoftLayer",
    LOST_TO_COMPETITOR_VMWARE = "Lost to Competitor - VMWare",
    NO_CUSTOMER_REFERENCE = "No Customer Reference",
    NO_INTEGRATION_RESOURCES = "No Integration Resources",
    NO_OPPORTUNITY = "No Opportunity",
    NO_PERCEIVED_VALUE_OF_MP = "No Perceived Value of MP",
    NO_RESPONSE = "No Response",
    NOT_COMMITTED_TO_AWS = "Not Committed to AWS",
    NO_UPDATE = "No Update",
    ON_PREMISES_DEPLOYMENT = "On Premises Deployment",
    OTHER = "Other",
    OTHER_DETAILS_IN_DESCRIPTION = "Other (Details in Description)",
    PARTNER_GAP = "Partner Gap",
    PAST_DUE = "Past Due",
    PEOPLE_RELATIONSHIP_GOVERNANCE = "People/Relationship/Governance",
    PLATFORM_TECHNOLOGY_LIMITATION = "Platform Technology Limitation",
    PREFERENCE_FOR_COMPETITOR = "Preference for Competitor",
    PRICE = "Price",
    PRODUCT_TECHNOLOGY = "Product/Technology",
    PRODUCT_NOT_ON_AWS = "Product Not on AWS",
    SECURITY_COMPLIANCE = "Security / Compliance",
    SELF_SERVICE = "Self-Service",
    TECHNICAL_LIMITATIONS = "Technical Limitations",
    TERM_SHEET_IMPASSE = "Term Sheet Impasse",
}

M.AwsFundingUsed = {
    YES = "Yes",
    NO = "No",
}

M.AwsMemberBusinessTitle = {
    AWS_SALES_REP = "AWSSalesRep",
    AWS_ACCOUNT_OWNER = "AWSAccountOwner",
    WWPSPDM = "WWPSPDM",
    PDM = "PDM",
    PSM = "PSM",
    ISVSM = "ISVSM",
}

M.CurrencyCode = {
    USD = "USD",
    EUR = "EUR",
    GBP = "GBP",
    AUD = "AUD",
    CAD = "CAD",
    CNY = "CNY",
    NZD = "NZD",
    INR = "INR",
    JPY = "JPY",
    CHF = "CHF",
    SEK = "SEK",
    AED = "AED",
    AFN = "AFN",
    ALL = "ALL",
    AMD = "AMD",
    ANG = "ANG",
    AOA = "AOA",
    ARS = "ARS",
    AWG = "AWG",
    AZN = "AZN",
    BAM = "BAM",
    BBD = "BBD",
    BDT = "BDT",
    BGN = "BGN",
    BHD = "BHD",
    BIF = "BIF",
    BMD = "BMD",
    BND = "BND",
    BOB = "BOB",
    BOV = "BOV",
    BRL = "BRL",
    BSD = "BSD",
    BTN = "BTN",
    BWP = "BWP",
    BYN = "BYN",
    BZD = "BZD",
    CDF = "CDF",
    CHE = "CHE",
    CHW = "CHW",
    CLF = "CLF",
    CLP = "CLP",
    COP = "COP",
    COU = "COU",
    CRC = "CRC",
    CUC = "CUC",
    CUP = "CUP",
    CVE = "CVE",
    CZK = "CZK",
    DJF = "DJF",
    DKK = "DKK",
    DOP = "DOP",
    DZD = "DZD",
    EGP = "EGP",
    ERN = "ERN",
    ETB = "ETB",
    FJD = "FJD",
    FKP = "FKP",
    GEL = "GEL",
    GHS = "GHS",
    GIP = "GIP",
    GMD = "GMD",
    GNF = "GNF",
    GTQ = "GTQ",
    GYD = "GYD",
    HKD = "HKD",
    HNL = "HNL",
    HRK = "HRK",
    HTG = "HTG",
    HUF = "HUF",
    IDR = "IDR",
    ILS = "ILS",
    IQD = "IQD",
    IRR = "IRR",
    ISK = "ISK",
    JMD = "JMD",
    JOD = "JOD",
    KES = "KES",
    KGS = "KGS",
    KHR = "KHR",
    KMF = "KMF",
    KPW = "KPW",
    KRW = "KRW",
    KWD = "KWD",
    KYD = "KYD",
    KZT = "KZT",
    LAK = "LAK",
    LBP = "LBP",
    LKR = "LKR",
    LRD = "LRD",
    LSL = "LSL",
    LYD = "LYD",
    MAD = "MAD",
    MDL = "MDL",
    MGA = "MGA",
    MKD = "MKD",
    MMK = "MMK",
    MNT = "MNT",
    MOP = "MOP",
    MRU = "MRU",
    MUR = "MUR",
    MVR = "MVR",
    MWK = "MWK",
    MXN = "MXN",
    MXV = "MXV",
    MYR = "MYR",
    MZN = "MZN",
    NAD = "NAD",
    NGN = "NGN",
    NIO = "NIO",
    NOK = "NOK",
    NPR = "NPR",
    OMR = "OMR",
    PAB = "PAB",
    PEN = "PEN",
    PGK = "PGK",
    PHP = "PHP",
    PKR = "PKR",
    PLN = "PLN",
    PYG = "PYG",
    QAR = "QAR",
    RON = "RON",
    RSD = "RSD",
    RUB = "RUB",
    RWF = "RWF",
    SAR = "SAR",
    SBD = "SBD",
    SCR = "SCR",
    SDG = "SDG",
    SGD = "SGD",
    SHP = "SHP",
    SLL = "SLL",
    SOS = "SOS",
    SRD = "SRD",
    SSP = "SSP",
    STN = "STN",
    SVC = "SVC",
    SYP = "SYP",
    SZL = "SZL",
    THB = "THB",
    TJS = "TJS",
    TMT = "TMT",
    TND = "TND",
    TOP = "TOP",
    TRY = "TRY",
    TTD = "TTD",
    TWD = "TWD",
    TZS = "TZS",
    UAH = "UAH",
    UGX = "UGX",
    USN = "USN",
    UYI = "UYI",
    UYU = "UYU",
    UZS = "UZS",
    VEF = "VEF",
    VND = "VND",
    VUV = "VUV",
    WST = "WST",
    XAF = "XAF",
    XCD = "XCD",
    XDR = "XDR",
    XOF = "XOF",
    XPF = "XPF",
    XSU = "XSU",
    XUA = "XUA",
    YER = "YER",
    ZAR = "ZAR",
    ZMW = "ZMW",
    ZWL = "ZWL",
}

M.PaymentFrequency = {
    MONTHLY = "Monthly",
}

M.EngagementScore = {
    HIGH = "High",
    MEDIUM = "Medium",
    LOW = "Low",
}

M.AwsOpportunityStage = {
    NOT_STARTED = "Not Started",
    IN_PROGRESS = "In Progress",
    PROSPECT = "Prospect",
    ENGAGED = "Engaged",
    IDENTIFIED = "Identified",
    QUALIFY = "Qualify",
    RESEARCH = "Research",
    SELLER_ENGAGED = "Seller Engaged",
    EVALUATING = "Evaluating",
    SELLER_REGISTERED = "Seller Registered",
    TERM_SHEET_NEGOTIATION = "Term Sheet Negotiation",
    CONTRACT_NEGOTIATION = "Contract Negotiation",
    ONBOARDING = "Onboarding",
    BUILDING_INTEGRATION = "Building Integration",
    QUALIFIED = "Qualified",
    ON_HOLD = "On-hold",
    TECHNICAL_VALIDATION = "Technical Validation",
    BUSINESS_VALIDATION = "Business Validation",
    COMMITTED = "Committed",
    LAUNCHED = "Launched",
    DEFERRED_TO_PARTNER = "Deferred to Partner",
    CLOSED_LOST = "Closed Lost",
    COMPLETED = "Completed",
    CLOSED_INCOMPLETE = "Closed Incomplete",
}

M.AwsPartition = {
    AWS_EUSC = "aws-eusc",
}

M.SalesInvolvementType = {
    FOR_VISIBILITY_ONLY = "For Visibility Only",
    CO_SELL = "Co-Sell",
}

M.InvolvementTypeChangeReason = {
    EXPANSION_OPPORTUNITY = "Expansion Opportunity",
    CHANGE_IN_DEAL_INFORMATION = "Change in Deal Information",
    CUSTOMER_REQUESTED = "Customer Requested",
    TECHNICAL_COMPLEXITY = "Technical Complexity",
    RISK_MITIGATION = "Risk Mitigation",
}

M.OpportunityOrigin = {
    AWS_REFERRAL = "AWS Referral",
    PARTNER_REFERRAL = "Partner Referral",
}

M.Visibility = {
    FULL = "Full",
    LIMITED = "Limited",
}

M.MarketSegment = {
    ENTERPRISE = "Enterprise",
    LARGE = "Large",
    MEDIUM = "Medium",
    SMALL = "Small",
    MICRO = "Micro",
}

M.EngagementContextType = {
    CUSTOMER_PROJECT = "CustomerProject",
    LEAD = "Lead",
}

M.EngagementSortName = {
    CreatedDate = "CreatedDate",
}

M.SortOrder = {
    ASCENDING = "ASCENDING",
    DESCENDING = "DESCENDING",
}

M.ListTasksSortName = {
    START_TIME = "StartTime",
}

M.TaskStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETE = "COMPLETE",
    FAILED = "FAILED",
}

M.ReasonCode = {
    INVITATION_ACCESS_DENIED = "InvitationAccessDenied",
    INVITATION_VALIDATION_FAILED = "InvitationValidationFailed",
    ENGAGEMENT_ACCESS_DENIED = "EngagementAccessDenied",
    OPPORTUNITY_ACCESS_DENIED = "OpportunityAccessDenied",
    RESOURCE_SNAPSHOT_JOB_ACCESS_DENIED = "ResourceSnapshotJobAccessDenied",
    RESOURCE_SNAPSHOT_JOB_VALIDATION_FAILED = "ResourceSnapshotJobValidationFailed",
    RESOURCE_SNAPSHOT_JOB_CONFLICT = "ResourceSnapshotJobConflict",
    ENGAGEMENT_VALIDATION_FAILED = "EngagementValidationFailed",
    ENGAGEMENT_CONFLICT = "EngagementConflict",
    OPPORTUNITY_SUBMISSION_FAILED = "OpportunitySubmissionFailed",
    ENGAGEMENT_INVITATION_CONFLICT = "EngagementInvitationConflict",
    INTERNAL_ERROR = "InternalError",
    OPPORTUNITY_VALIDATION_FAILED = "OpportunityValidationFailed",
    OPPORTUNITY_CONFLICT = "OpportunityConflict",
    RESOURCE_SNAPSHOT_ACCESS_DENIED = "ResourceSnapshotAccessDenied",
    RESOURCE_SNAPSHOT_VALIDATION_FAILED = "ResourceSnapshotValidationFailed",
    RESOURCE_SNAPSHOT_CONFLICT = "ResourceSnapshotConflict",
    SERVICE_QUOTA_EXCEEDED = "ServiceQuotaExceeded",
    REQUEST_THROTTLED = "RequestThrottled",
    CONTEXT_NOT_FOUND = "ContextNotFound",
    CUSTOMER_PROJECT_CONTEXT_NOT_PERMITTED = "CustomerProjectContextNotPermitted",
    DISQUALIFIED_LEAD_NOT_PERMITTED = "DisqualifiedLeadNotPermitted",
}

M.ReceiverResponsibility = {
    DISTRIBUTOR = "Distributor",
    RESELLER = "Reseller",
    HARDWARE_PARTNER = "Hardware Partner",
    MANAGED_SERVICE_PROVIDER = "Managed Service Provider",
    SOFTWARE_PARTNER = "Software Partner",
    SERVICES_PARTNER = "Services Partner",
    TRAINING_PARTNER = "Training Partner",
    CO_SELL_FACILITATOR = "Co-Sell Facilitator",
    FACILITATOR = "Facilitator",
}

M.EngagementInvitationPayloadType = {
    OPPORTUNITY_INVITATION = "OpportunityInvitation",
    LEAD_INVITATION = "LeadInvitation",
}

M.InvitationStatus = {
    ACCEPTED = "ACCEPTED",
    PENDING = "PENDING",
    REJECTED = "REJECTED",
    EXPIRED = "EXPIRED",
}

M.ParticipantType = {
    SENDER = "SENDER",
    RECEIVER = "RECEIVER",
}

M.OpportunityEngagementInvitationSortName = {
    INVITATION_DATE = "InvitationDate",
}

M.ClosedLostReason = {
    CUSTOMER_DEFICIENCY = "Customer Deficiency",
    DELAY_CANCELLATION_OF_PROJECT = "Delay / Cancellation of Project",
    LEGAL_TAX_REGULATORY = "Legal / Tax / Regulatory",
    LOST_TO_COMPETITOR_GOOGLE = "Lost to Competitor - Google",
    LOST_TO_COMPETITOR_MICROSOFT = "Lost to Competitor - Microsoft",
    LOST_TO_COMPETITOR_SOFTLAYER = "Lost to Competitor - SoftLayer",
    LOST_TO_COMPETITOR_VMWARE = "Lost to Competitor - VMWare",
    LOST_TO_COMPETITOR_OTHER = "Lost to Competitor - Other",
    NO_OPPORTUNITY = "No Opportunity",
    ON_PREMISES_DEPLOYMENT = "On Premises Deployment",
    PARTNER_GAP = "Partner Gap",
    PRICE = "Price",
    SECURITY_COMPLIANCE = "Security / Compliance",
    TECHNICAL_LIMITATIONS = "Technical Limitations",
    CUSTOMER_EXPERIENCE = "Customer Experience",
    OTHER = "Other",
    PEOPLERELATIONSHIPGOVERNANCE = "People/Relationship/Governance",
    PRODUCTTECHNOLOGY = "Product/Technology",
    FINANCIALCOMMERCIAL = "Financial/Commercial",
}

M.ReviewStatus = {
    PENDING_SUBMISSION = "Pending Submission",
    SUBMITTED = "Submitted",
    IN_REVIEW = "In review",
    APPROVED = "Approved",
    REJECTED = "Rejected",
    ACTION_REQUIRED = "Action Required",
}

M.Stage = {
    PROSPECT = "Prospect",
    QUALIFIED = "Qualified",
    TECHNICAL_VALIDATION = "Technical Validation",
    BUSINESS_VALIDATION = "Business Validation",
    COMMITTED = "Committed",
    LAUNCHED = "Launched",
    CLOSED_LOST = "Closed Lost",
}

M.Channel = {
    AWS_MARKETING_CENTRAL = "AWS Marketing Central",
    CONTENT_SYNDICATION = "Content Syndication",
    DISPLAY = "Display",
    EMAIL = "Email",
    LIVE_EVENT = "Live Event",
    OUT_OF_HOME = "Out Of Home (OOH)",
    PRINT = "Print",
    SEARCH = "Search",
    SOCIAL = "Social",
    TELEMARKETING = "Telemarketing",
    TV = "TV",
    VIDEO = "Video",
    VIRTUAL_EVENT = "Virtual Event",
}

M.MarketingSource = {
    MARKETING_ACTIVITY = "Marketing Activity",
    NONE = "None",
}

M.NationalSecurity = {
    YES = "Yes",
    NO = "No",
}

M.OpportunityType = {
    NET_NEW_BUSINESS = "Net New Business",
    FLAT_RENEWAL = "Flat Renewal",
    EXPANSION = "Expansion",
}

M.PrimaryNeedFromAws = {
    CO_SELL_ARCHITECTURAL_VALIDATION = "Co-Sell - Architectural Validation",
    CO_SELL_BUSINESS_PRESENTATION = "Co-Sell - Business Presentation",
    CO_SELL_COMPETITIVE_INFORMATION = "Co-Sell - Competitive Information",
    CO_SELL_PRICING_ASSISTANCE = "Co-Sell - Pricing Assistance",
    CO_SELL_TECHNICAL_CONSULTATION = "Co-Sell - Technical Consultation",
    CO_SELL_TOTAL_COST_OF_OWNERSHIP_EVALUATION = "Co-Sell - Total Cost of Ownership Evaluation",
    CO_SELL_DEAL_SUPPORT = "Co-Sell - Deal Support",
    CO_SELL_SUPPORT_FOR_PUBLIC_TENDER_RFX = "Co-Sell - Support for Public Tender / RFx",
}

M.CompetitorName = {
    ORACLE_CLOUD = "Oracle Cloud",
    ON_PREM = "On-Prem",
    CO_LOCATION = "Co-location",
    AKAMAI = "Akamai",
    ALICLOUD = "AliCloud",
    GOOGLE_CLOUD_PLATFORM = "Google Cloud Platform",
    IBM_SOFTLAYER = "IBM Softlayer",
    MICROSOFT_AZURE = "Microsoft Azure",
    OTHER_COST_OPTIMIZATION = "Other- Cost Optimization",
    NO_COMPETITION = "No Competition",
    OTHER = "*Other",
}

M.DeliveryModel = {
    SAAS_OR_PAAS = "SaaS or PaaS",
    BYOL_OR_AMI = "BYOL or AMI",
    MANAGED_SERVICES = "Managed Services",
    PROFESSIONAL_SERVICES = "Professional Services",
    RESELL = "Resell",
    OTHER = "Other",
}

M.SalesActivity = {
    INITIALIZED_DISCUSSIONS_WITH_CUSTOMER = "Initialized discussions with customer",
    CUSTOMER_HAS_SHOWN_INTEREST = "Customer has shown interest in solution",
    CONDUCTED_POC_DEMO = "Conducted POC / Demo",
    IN_EVALUATION_PLANNING_STAGE = "In evaluation / planning stage",
    AGREED_ON_SOLUTION_TO_BUSINESS_PROBLEM = "Agreed on solution to Business Problem",
    COMPLETED_ACTION_PLAN = "Completed Action Plan",
    FINALIZED_DEPLOYMENT_NEEDS = "Finalized Deployment Need",
    SOW_SIGNED = "SOW Signed",
}

M.RevenueModel = {
    CONTRACT = "Contract",
    PAY_AS_YOU_GO = "Pay-as-you-go",
    SUBSCRIPTION = "Subscription",
}

M.OpportunitySortName = {
    LAST_MODIFIEDDATE = "LastModifiedDate",
    IDENTIFIER = "Identifier",
    CUSTOMER_COMPANY_NAME = "CustomerCompanyName",
    CREATED_DATE = "CreatedDate",
    TARGET_CLOSE_DATE = "TargetCloseDate",
}

M.ResourceType = {
    OPPORTUNITY = "Opportunity",
}

M.ResourceSnapshotJobStatus = {
    RUNNING = "Running",
    STOPPED = "Stopped",
}

M.SortBy = {
    CREATED_DATE = "CreatedDate",
}

M.SolutionSortName = {
    IDENTIFIER = "Identifier",
    NAME = "Name",
    STATUS = "Status",
    CATEGORY = "Category",
    CREATEDDATE = "CreatedDate",
}

M.SolutionStatus = {
    ACTIVE = "Active",
    INACTIVE = "Inactive",
    DRAFT = "Draft",
}

return M
