local record M
    pages_describe_fleet_attributes: function(client: table, input: table): function(): table, table
    items_describe_fleet_attributes: function(client: table, input: table): function(): any
    pages_describe_fleet_capacity: function(client: table, input: table): function(): table, table
    items_describe_fleet_capacity: function(client: table, input: table): function(): any
    pages_describe_fleet_events: function(client: table, input: table): function(): table, table
    items_describe_fleet_events: function(client: table, input: table): function(): any
    pages_describe_fleet_location_attributes: function(client: table, input: table): function(): table, table
    pages_describe_fleet_utilization: function(client: table, input: table): function(): table, table
    items_describe_fleet_utilization: function(client: table, input: table): function(): any
    pages_describe_game_server_instances: function(client: table, input: table): function(): table, table
    items_describe_game_server_instances: function(client: table, input: table): function(): any
    pages_describe_game_session_details: function(client: table, input: table): function(): table, table
    items_describe_game_session_details: function(client: table, input: table): function(): any
    pages_describe_game_session_queues: function(client: table, input: table): function(): table, table
    items_describe_game_session_queues: function(client: table, input: table): function(): any
    pages_describe_game_sessions: function(client: table, input: table): function(): table, table
    items_describe_game_sessions: function(client: table, input: table): function(): any
    pages_describe_instances: function(client: table, input: table): function(): table, table
    items_describe_instances: function(client: table, input: table): function(): any
    pages_describe_matchmaking_configurations: function(client: table, input: table): function(): table, table
    items_describe_matchmaking_configurations: function(client: table, input: table): function(): any
    pages_describe_matchmaking_rule_sets: function(client: table, input: table): function(): table, table
    items_describe_matchmaking_rule_sets: function(client: table, input: table): function(): any
    pages_describe_player_sessions: function(client: table, input: table): function(): table, table
    items_describe_player_sessions: function(client: table, input: table): function(): any
    pages_describe_scaling_policies: function(client: table, input: table): function(): table, table
    items_describe_scaling_policies: function(client: table, input: table): function(): any
    pages_list_aliases: function(client: table, input: table): function(): table, table
    items_list_aliases: function(client: table, input: table): function(): any
    pages_list_builds: function(client: table, input: table): function(): table, table
    items_list_builds: function(client: table, input: table): function(): any
    pages_list_compute: function(client: table, input: table): function(): table, table
    items_list_compute: function(client: table, input: table): function(): any
    pages_list_container_fleets: function(client: table, input: table): function(): table, table
    items_list_container_fleets: function(client: table, input: table): function(): any
    pages_list_container_group_definition_versions: function(client: table, input: table): function(): table, table
    items_list_container_group_definition_versions: function(client: table, input: table): function(): any
    pages_list_container_group_definitions: function(client: table, input: table): function(): table, table
    items_list_container_group_definitions: function(client: table, input: table): function(): any
    pages_list_fleet_deployments: function(client: table, input: table): function(): table, table
    items_list_fleet_deployments: function(client: table, input: table): function(): any
    pages_list_fleets: function(client: table, input: table): function(): table, table
    items_list_fleets: function(client: table, input: table): function(): any
    pages_list_game_server_groups: function(client: table, input: table): function(): table, table
    items_list_game_server_groups: function(client: table, input: table): function(): any
    pages_list_game_servers: function(client: table, input: table): function(): table, table
    items_list_game_servers: function(client: table, input: table): function(): any
    pages_list_locations: function(client: table, input: table): function(): table, table
    items_list_locations: function(client: table, input: table): function(): any
    pages_list_scripts: function(client: table, input: table): function(): table, table
    items_list_scripts: function(client: table, input: table): function(): any
    pages_search_game_sessions: function(client: table, input: table): function(): table, table
    items_search_game_sessions: function(client: table, input: table): function(): any
end

return M
