local M = {}

M.AccessDeniedExceptionReason = {
    UNAUTHORIZED_ACCOUNT = "UNAUTHORIZED_ACCOUNT",
    DEPENDENCY_ACCESS_DENIED = "DEPENDENCY_ACCESS_DENIED",
}

M.ChecksumAggregationMethod = {
    CHECKSUM_AGGREGATION_LINEAR = "LINEAR",
}

M.ChecksumAlgorithm = {
    CHECKSUM_ALGORITHM_SHA256 = "SHA256",
}

M.Status = {
    COMPLETED = "completed",
    PENDING = "pending",
    ERROR = "error",
}

M.RequestThrottledExceptionReason = {
    ACCOUNT_THROTTLED = "ACCOUNT_THROTTLED",
    DEPENDENCY_REQUEST_THROTTLED = "DEPENDENCY_REQUEST_THROTTLED",
    RESOURCE_LEVEL_THROTTLE = "RESOURCE_LEVEL_THROTTLE",
}

M.ResourceNotFoundExceptionReason = {
    SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND",
    GRANT_NOT_FOUND = "GRANT_NOT_FOUND",
    DEPENDENCY_RESOURCE_NOT_FOUND = "DEPENDENCY_RESOURCE_NOT_FOUND",
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND",
}

M.ServiceQuotaExceededExceptionReason = {
    DEPENDENCY_SERVICE_QUOTA_EXCEEDED = "DEPENDENCY_SERVICE_QUOTA_EXCEEDED",
}

M.ValidationExceptionReason = {
    INVALID_CUSTOMER_KEY = "INVALID_CUSTOMER_KEY",
    INVALID_PAGE_TOKEN = "INVALID_PAGE_TOKEN",
    INVALID_BLOCK_TOKEN = "INVALID_BLOCK_TOKEN",
    INVALID_GRANT_TOKEN = "INVALID_GRANT_TOKEN",
    INVALID_SNAPSHOT_ID = "INVALID_SNAPSHOT_ID",
    UNRELATED_SNAPSHOTS = "UNRELATED_SNAPSHOTS",
    INVALID_BLOCK = "INVALID_BLOCK",
    INVALID_CONTENT_ENCODING = "INVALID_CONTENT_ENCODING",
    INVALID_TAG = "INVALID_TAG",
    INVALID_DEPENDENCY_REQUEST = "INVALID_DEPENDENCY_REQUEST",
    INVALID_PARAMETER_VALUE = "INVALID_PARAMETER_VALUE",
    INVALID_VOLUME_SIZE = "INVALID_VOLUME_SIZE",
    CONFLICTING_BLOCK_UPDATE = "CONFLICTING_BLOCK_UPDATE",
    INVALID_IMAGE_ID = "INVALID_IMAGE_ID",
    WRITE_REQUEST_TIMEOUT = "WRITE_REQUEST_TIMEOUT",
}

M.SSEType = {
    SSE_EBS = "sse-ebs",
    SSE_KMS = "sse-kms",
    NONE = "none",
}

return M
