local M = {}

M.AccountScope = {
    PAYER = "PAYER",
    LINKED = "LINKED",
}

M.AnalysisStatus = {
    SUCCEEDED = "SUCCEEDED",
    PROCESSING = "PROCESSING",
    FAILED = "FAILED",
}

M.AnalysisType = {
    MAX_SAVINGS = "MAX_SAVINGS",
    CUSTOM_COMMITMENT = "CUSTOM_COMMITMENT",
}

M.PaymentOption = {
    NO_UPFRONT = "NO_UPFRONT",
    PARTIAL_UPFRONT = "PARTIAL_UPFRONT",
    ALL_UPFRONT = "ALL_UPFRONT",
    LIGHT_UTILIZATION = "LIGHT_UTILIZATION",
    MEDIUM_UTILIZATION = "MEDIUM_UTILIZATION",
    HEAVY_UTILIZATION = "HEAVY_UTILIZATION",
}

M.SupportedSavingsPlansType = {
    COMPUTE_SP = "COMPUTE_SP",
    EC2_INSTANCE_SP = "EC2_INSTANCE_SP",
    SAGEMAKER_SP = "SAGEMAKER_SP",
    DATABASE_SP = "DATABASE_SP",
}

M.TermInYears = {
    ONE_YEAR = "ONE_YEAR",
    THREE_YEARS = "THREE_YEARS",
}

M.ErrorCode = {
    NO_USAGE_FOUND = "NO_USAGE_FOUND",
    INTERNAL_FAILURE = "INTERNAL_FAILURE",
    INVALID_SAVINGS_PLANS_TO_ADD = "INVALID_SAVINGS_PLANS_TO_ADD",
    INVALID_SAVINGS_PLANS_TO_EXCLUDE = "INVALID_SAVINGS_PLANS_TO_EXCLUDE",
    INVALID_ACCOUNT_ID = "INVALID_ACCOUNT_ID",
}

M.AnomalyFeedbackType = {
    YES = "YES",
    NO = "NO",
    PLANNED_ACTIVITY = "PLANNED_ACTIVITY",
}

M.MonitorDimension = {
    SERVICE = "SERVICE",
    LINKED_ACCOUNT = "LINKED_ACCOUNT",
    TAG = "TAG",
    COST_CATEGORY = "COST_CATEGORY",
}

M.MatchOption = {
    EQUALS = "EQUALS",
    ABSENT = "ABSENT",
    STARTS_WITH = "STARTS_WITH",
    ENDS_WITH = "ENDS_WITH",
    CONTAINS = "CONTAINS",
    CASE_SENSITIVE = "CASE_SENSITIVE",
    CASE_INSENSITIVE = "CASE_INSENSITIVE",
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
}

M.Dimension = {
    AZ = "AZ",
    INSTANCE_TYPE = "INSTANCE_TYPE",
    LINKED_ACCOUNT = "LINKED_ACCOUNT",
    PAYER_ACCOUNT = "PAYER_ACCOUNT",
    LINKED_ACCOUNT_NAME = "LINKED_ACCOUNT_NAME",
    OPERATION = "OPERATION",
    PURCHASE_TYPE = "PURCHASE_TYPE",
    REGION = "REGION",
    SERVICE = "SERVICE",
    SERVICE_CODE = "SERVICE_CODE",
    USAGE_TYPE = "USAGE_TYPE",
    USAGE_TYPE_GROUP = "USAGE_TYPE_GROUP",
    RECORD_TYPE = "RECORD_TYPE",
    OPERATING_SYSTEM = "OPERATING_SYSTEM",
    TENANCY = "TENANCY",
    SCOPE = "SCOPE",
    PLATFORM = "PLATFORM",
    SUBSCRIPTION_ID = "SUBSCRIPTION_ID",
    LEGAL_ENTITY_NAME = "LEGAL_ENTITY_NAME",
    DEPLOYMENT_OPTION = "DEPLOYMENT_OPTION",
    DATABASE_ENGINE = "DATABASE_ENGINE",
    CACHE_ENGINE = "CACHE_ENGINE",
    INSTANCE_TYPE_FAMILY = "INSTANCE_TYPE_FAMILY",
    BILLING_ENTITY = "BILLING_ENTITY",
    RESERVATION_ID = "RESERVATION_ID",
    RESOURCE_ID = "RESOURCE_ID",
    RIGHTSIZING_TYPE = "RIGHTSIZING_TYPE",
    SAVINGS_PLANS_TYPE = "SAVINGS_PLANS_TYPE",
    SAVINGS_PLAN_ARN = "SAVINGS_PLAN_ARN",
    PAYMENT_OPTION = "PAYMENT_OPTION",
    AGREEMENT_END_DATE_TIME_AFTER = "AGREEMENT_END_DATE_TIME_AFTER",
    AGREEMENT_END_DATE_TIME_BEFORE = "AGREEMENT_END_DATE_TIME_BEFORE",
    INVOICING_ENTITY = "INVOICING_ENTITY",
    ANOMALY_TOTAL_IMPACT_ABSOLUTE = "ANOMALY_TOTAL_IMPACT_ABSOLUTE",
    ANOMALY_TOTAL_IMPACT_PERCENTAGE = "ANOMALY_TOTAL_IMPACT_PERCENTAGE",
}

M.MonitorType = {
    DIMENSIONAL = "DIMENSIONAL",
    CUSTOM = "CUSTOM",
}

M.AnomalySubscriptionFrequency = {
    DAILY = "DAILY",
    IMMEDIATE = "IMMEDIATE",
    WEEKLY = "WEEKLY",
}

M.SubscriberStatus = {
    CONFIRMED = "CONFIRMED",
    DECLINED = "DECLINED",
}

M.SubscriberType = {
    EMAIL = "EMAIL",
    SNS = "SNS",
}

M.ApproximationDimension = {
    SERVICE = "SERVICE",
    RESOURCE = "RESOURCE",
}

M.CostCategoryInheritedValueDimensionName = {
    LINKED_ACCOUNT_NAME = "LINKED_ACCOUNT_NAME",
    TAG = "TAG",
}

M.CostCategoryRuleType = {
    REGULAR = "REGULAR",
    INHERITED_VALUE = "INHERITED_VALUE",
}

M.CostCategoryRuleVersion = {
    CostCategoryExpressionV1 = "CostCategoryExpression.v1",
}

M.CostCategorySplitChargeMethod = {
    FIXED = "FIXED",
    PROPORTIONAL = "PROPORTIONAL",
    EVEN = "EVEN",
}

M.CostCategorySplitChargeRuleParameterType = {
    ALLOCATION_PERCENTAGES = "ALLOCATION_PERCENTAGES",
}

M.CostCategoryStatusComponent = {
    COST_EXPLORER = "COST_EXPLORER",
}

M.CostCategoryStatus = {
    PROCESSING = "PROCESSING",
    APPLIED = "APPLIED",
}

M.NumericOperator = {
    EQUAL = "EQUAL",
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    BETWEEN = "BETWEEN",
}

M.Granularity = {
    DAILY = "DAILY",
    MONTHLY = "MONTHLY",
    HOURLY = "HOURLY",
}

M.GroupDefinitionType = {
    DIMENSION = "DIMENSION",
    TAG = "TAG",
    COST_CATEGORY = "COST_CATEGORY",
}

M.SortOrder = {
    ASCENDING = "ASCENDING",
    DESCENDING = "DESCENDING",
}

M.Metric = {
    BLENDED_COST = "BLENDED_COST",
    UNBLENDED_COST = "UNBLENDED_COST",
    AMORTIZED_COST = "AMORTIZED_COST",
    NET_UNBLENDED_COST = "NET_UNBLENDED_COST",
    NET_AMORTIZED_COST = "NET_AMORTIZED_COST",
    USAGE_QUANTITY = "USAGE_QUANTITY",
    NORMALIZED_USAGE_AMOUNT = "NORMALIZED_USAGE_AMOUNT",
}

M.Context = {
    COST_AND_USAGE = "COST_AND_USAGE",
    RESERVATIONS = "RESERVATIONS",
    SAVINGS_PLANS = "SAVINGS_PLANS",
}

M.LookbackPeriodInDays = {
    SEVEN_DAYS = "SEVEN_DAYS",
    THIRTY_DAYS = "THIRTY_DAYS",
    SIXTY_DAYS = "SIXTY_DAYS",
}

M.OfferingClass = {
    STANDARD = "STANDARD",
    CONVERTIBLE = "CONVERTIBLE",
}

M.RecommendationTarget = {
    SAME_INSTANCE_FAMILY = "SAME_INSTANCE_FAMILY",
    CROSS_INSTANCE_FAMILY = "CROSS_INSTANCE_FAMILY",
}

M.FindingReasonCode = {
    CPU_OVER_PROVISIONED = "CPU_OVER_PROVISIONED",
    CPU_UNDER_PROVISIONED = "CPU_UNDER_PROVISIONED",
    MEMORY_OVER_PROVISIONED = "MEMORY_OVER_PROVISIONED",
    MEMORY_UNDER_PROVISIONED = "MEMORY_UNDER_PROVISIONED",
    EBS_THROUGHPUT_OVER_PROVISIONED = "EBS_THROUGHPUT_OVER_PROVISIONED",
    EBS_THROUGHPUT_UNDER_PROVISIONED = "EBS_THROUGHPUT_UNDER_PROVISIONED",
    EBS_IOPS_OVER_PROVISIONED = "EBS_IOPS_OVER_PROVISIONED",
    EBS_IOPS_UNDER_PROVISIONED = "EBS_IOPS_UNDER_PROVISIONED",
    NETWORK_BANDWIDTH_OVER_PROVISIONED = "NETWORK_BANDWIDTH_OVER_PROVISIONED",
    NETWORK_BANDWIDTH_UNDER_PROVISIONED = "NETWORK_BANDWIDTH_UNDER_PROVISIONED",
    NETWORK_PPS_OVER_PROVISIONED = "NETWORK_PPS_OVER_PROVISIONED",
    NETWORK_PPS_UNDER_PROVISIONED = "NETWORK_PPS_UNDER_PROVISIONED",
    DISK_IOPS_OVER_PROVISIONED = "DISK_IOPS_OVER_PROVISIONED",
    DISK_IOPS_UNDER_PROVISIONED = "DISK_IOPS_UNDER_PROVISIONED",
    DISK_THROUGHPUT_OVER_PROVISIONED = "DISK_THROUGHPUT_OVER_PROVISIONED",
    DISK_THROUGHPUT_UNDER_PROVISIONED = "DISK_THROUGHPUT_UNDER_PROVISIONED",
}

M.PlatformDifference = {
    HYPERVISOR = "HYPERVISOR",
    NETWORK_INTERFACE = "NETWORK_INTERFACE",
    STORAGE_INTERFACE = "STORAGE_INTERFACE",
    INSTANCE_STORE_AVAILABILITY = "INSTANCE_STORE_AVAILABILITY",
    VIRTUALIZATION_TYPE = "VIRTUALIZATION_TYPE",
}

M.RightsizingType = {
    TERMINATE = "TERMINATE",
    MODIFY = "MODIFY",
}

M.SavingsPlansDataType = {
    ATTRIBUTES = "ATTRIBUTES",
    UTILIZATION = "UTILIZATION",
    AMORTIZED_COMMITMENT = "AMORTIZED_COMMITMENT",
    SAVINGS = "SAVINGS",
}

M.CostAllocationTagBackfillStatus = {
    SUCCEEDED = "SUCCEEDED",
    PROCESSING = "PROCESSING",
    FAILED = "FAILED",
}

M.CostAllocationTagStatus = {
    ACTIVE = "Active",
    INACTIVE = "Inactive",
}

M.CostAllocationTagType = {
    AWS_GENERATED = "AWSGenerated",
    USER_DEFINED = "UserDefined",
}

M.GenerationStatus = {
    SUCCEEDED = "SUCCEEDED",
    PROCESSING = "PROCESSING",
    FAILED = "FAILED",
}

return M
