local M = {}

M.EventType = {
    INITIATED_CALL = "INITIATED_CALL",
    RINGING = "RINGING",
    ANSWERED = "ANSWERED",
    COMPLETED_CALL = "COMPLETED_CALL",
    BUSY = "BUSY",
    FAILED = "FAILED",
    NO_ANSWER = "NO_ANSWER",
}

return M
