local M = {}

M.ScanFinding = {
    MALWARE = "MALWARE",
}

M.AggregationPeriod = {
    ONE_DAY = "ONE_DAY",
    SEVEN_DAYS = "SEVEN_DAYS",
    FOURTEEN_DAYS = "FOURTEEN_DAYS",
}

M.LifecycleDeleteAfterEvent = {
    DELETE_AFTER_COPY = "DELETE_AFTER_COPY",
}

M.BackupJobState = {
    CREATED = "CREATED",
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    ABORTING = "ABORTING",
    ABORTED = "ABORTED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    EXPIRED = "EXPIRED",
    PARTIAL = "PARTIAL",
}

M.BackupJobStatus = {
    CREATED = "CREATED",
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    ABORTING = "ABORTING",
    ABORTED = "ABORTED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    EXPIRED = "EXPIRED",
    PARTIAL = "PARTIAL",
    AGGREGATE_ALL = "AGGREGATE_ALL",
    ANY = "ANY",
}

M.MalwareScanner = {
    GUARDDUTY = "GUARDDUTY",
}

M.ScanMode = {
    FULL_SCAN = "FULL_SCAN",
    INCREMENTAL_SCAN = "INCREMENTAL_SCAN",
}

M.ConditionType = {
    STRINGEQUALS = "STRINGEQUALS",
}

M.BackupVaultEvent = {
    BACKUP_JOB_STARTED = "BACKUP_JOB_STARTED",
    BACKUP_JOB_COMPLETED = "BACKUP_JOB_COMPLETED",
    BACKUP_JOB_SUCCESSFUL = "BACKUP_JOB_SUCCESSFUL",
    BACKUP_JOB_FAILED = "BACKUP_JOB_FAILED",
    BACKUP_JOB_EXPIRED = "BACKUP_JOB_EXPIRED",
    RESTORE_JOB_STARTED = "RESTORE_JOB_STARTED",
    RESTORE_JOB_COMPLETED = "RESTORE_JOB_COMPLETED",
    RESTORE_JOB_SUCCESSFUL = "RESTORE_JOB_SUCCESSFUL",
    RESTORE_JOB_FAILED = "RESTORE_JOB_FAILED",
    COPY_JOB_STARTED = "COPY_JOB_STARTED",
    COPY_JOB_SUCCESSFUL = "COPY_JOB_SUCCESSFUL",
    COPY_JOB_FAILED = "COPY_JOB_FAILED",
    RECOVERY_POINT_MODIFIED = "RECOVERY_POINT_MODIFIED",
    BACKUP_PLAN_CREATED = "BACKUP_PLAN_CREATED",
    BACKUP_PLAN_MODIFIED = "BACKUP_PLAN_MODIFIED",
    S3_BACKUP_OBJECT_FAILED = "S3_BACKUP_OBJECT_FAILED",
    S3_RESTORE_OBJECT_FAILED = "S3_RESTORE_OBJECT_FAILED",
    CONTINUOUS_BACKUP_INTERRUPTED = "CONTINUOUS_BACKUP_INTERRUPTED",
    RECOVERY_POINT_INDEX_COMPLETED = "RECOVERY_POINT_INDEX_COMPLETED",
    RECOVERY_POINT_INDEX_DELETED = "RECOVERY_POINT_INDEX_DELETED",
    RECOVERY_POINT_INDEXING_FAILED = "RECOVERY_POINT_INDEXING_FAILED",
    EKS_RESTORE_OBJECT_FAILED = "EKS_RESTORE_OBJECT_FAILED",
    EKS_RESTORE_OBJECT_SKIPPED = "EKS_RESTORE_OBJECT_SKIPPED",
    EKS_BACKUP_OBJECT_FAILED = "EKS_BACKUP_OBJECT_FAILED",
}

M.EncryptionKeyType = {
    AWS_OWNED_KMS_KEY = "AWS_OWNED_KMS_KEY",
    CUSTOMER_MANAGED_KMS_KEY = "CUSTOMER_MANAGED_KMS_KEY",
}

M.VaultState = {
    CREATING = "CREATING",
    AVAILABLE = "AVAILABLE",
    FAILED = "FAILED",
}

M.VaultType = {
    BACKUP_VAULT = "BACKUP_VAULT",
    LOGICALLY_AIR_GAPPED_BACKUP_VAULT = "LOGICALLY_AIR_GAPPED_BACKUP_VAULT",
    RESTORE_ACCESS_BACKUP_VAULT = "RESTORE_ACCESS_BACKUP_VAULT",
}

M.CopyJobState = {
    CREATED = "CREATED",
    RUNNING = "RUNNING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    PARTIAL = "PARTIAL",
}

M.CopyJobStatus = {
    CREATED = "CREATED",
    RUNNING = "RUNNING",
    ABORTING = "ABORTING",
    ABORTED = "ABORTED",
    COMPLETING = "COMPLETING",
    COMPLETED = "COMPLETED",
    FAILING = "FAILING",
    FAILED = "FAILED",
    PARTIAL = "PARTIAL",
    AGGREGATE_ALL = "AGGREGATE_ALL",
    ANY = "ANY",
}

M.LegalHoldStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    CANCELING = "CANCELING",
    CANCELED = "CANCELED",
}

M.RestoreTestingRecoveryPointSelectionAlgorithm = {
    LATEST_WITHIN_WINDOW = "LATEST_WITHIN_WINDOW",
    RANDOM_WITHIN_WINDOW = "RANDOM_WITHIN_WINDOW",
}

M.RestoreTestingRecoveryPointType = {
    CONTINUOUS = "CONTINUOUS",
    SNAPSHOT = "SNAPSHOT",
}

M.MpaSessionStatus = {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    FAILED = "FAILED",
}

M.IndexStatus = {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
    DELETING = "DELETING",
}

M.ScanJobState = {
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_ISSUES = "COMPLETED_WITH_ISSUES",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
}

M.RecoveryPointStatus = {
    COMPLETED = "COMPLETED",
    PARTIAL = "PARTIAL",
    DELETING = "DELETING",
    EXPIRED = "EXPIRED",
    AVAILABLE = "AVAILABLE",
    STOPPED = "STOPPED",
    CREATING = "CREATING",
}

M.StorageClass = {
    WARM = "WARM",
    COLD = "COLD",
    DELETED = "DELETED",
}

M.RestoreDeletionStatus = {
    DELETING = "DELETING",
    FAILED = "FAILED",
    SUCCESSFUL = "SUCCESSFUL",
}

M.RestoreJobStatus = {
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    COMPLETED = "COMPLETED",
    ABORTED = "ABORTED",
    FAILED = "FAILED",
}

M.RestoreValidationStatus = {
    FAILED = "FAILED",
    SUCCESSFUL = "SUCCESSFUL",
    TIMED_OUT = "TIMED_OUT",
    VALIDATING = "VALIDATING",
}

M.ScanResourceType = {
    EBS = "EBS",
    EC2 = "EC2",
    S3 = "S3",
}

M.ScanResultStatus = {
    NO_THREATS_FOUND = "NO_THREATS_FOUND",
    THREATS_FOUND = "THREATS_FOUND",
}

M.ScanState = {
    CANCELED = "CANCELED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_ISSUES = "COMPLETED_WITH_ISSUES",
    CREATED = "CREATED",
    FAILED = "FAILED",
    RUNNING = "RUNNING",
}

M.RuleExecutionType = {
    CONTINUOUS = "CONTINUOUS",
    SNAPSHOTS = "SNAPSHOTS",
    CONTINUOUS_AND_SNAPSHOTS = "CONTINUOUS_AND_SNAPSHOTS",
}

M.MpaRevokeSessionStatus = {
    PENDING = "PENDING",
    FAILED = "FAILED",
}

M.RestoreJobState = {
    CREATED = "CREATED",
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    ABORTED = "ABORTED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    AGGREGATE_ALL = "AGGREGATE_ALL",
    ANY = "ANY",
}

M.ScanJobStatus = {
    CREATED = "CREATED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_ISSUES = "COMPLETED_WITH_ISSUES",
    RUNNING = "RUNNING",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
    AGGREGATE_ALL = "AGGREGATE_ALL",
    ANY = "ANY",
}

M.Index = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

return M
