local M = {}

M.StartSelectorType = {
    FRAGMENT_NUMBER = "FRAGMENT_NUMBER",
    SERVER_TIMESTAMP = "SERVER_TIMESTAMP",
    PRODUCER_TIMESTAMP = "PRODUCER_TIMESTAMP",
    NOW = "NOW",
    EARLIEST = "EARLIEST",
    CONTINUATION_TOKEN = "CONTINUATION_TOKEN",
}

return M
