-- Code generated by lua-client-codegen. DO NOT EDIT.

local awsjson_protocol = require("smithy.protocol.awsjson")
local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("sfn.endpoint_rules")
local schemas = require("sfn.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AWSStepFunctions"
    if not cfg.protocol then
        cfg.protocol = awsjson_protocol.new({ version = "1.0", service_id = cfg.service_id })
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "states", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createActivity(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateActivity, input, options)
end

function Client:createStateMachine(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateStateMachine, input, options)
end

function Client:createStateMachineAlias(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateStateMachineAlias, input, options)
end

function Client:deleteActivity(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteActivity, input, options)
end

function Client:deleteStateMachine(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteStateMachine, input, options)
end

function Client:deleteStateMachineAlias(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteStateMachineAlias, input, options)
end

function Client:deleteStateMachineVersion(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteStateMachineVersion, input, options)
end

function Client:describeActivity(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeActivity, input, options)
end

function Client:describeExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeExecution, input, options)
end

function Client:describeMapRun(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeMapRun, input, options)
end

function Client:describeStateMachine(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeStateMachine, input, options)
end

function Client:describeStateMachineAlias(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeStateMachineAlias, input, options)
end

function Client:describeStateMachineForExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeStateMachineForExecution, input, options)
end

function Client:getActivityTask(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetActivityTask, input, options)
end

function Client:getExecutionHistory(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetExecutionHistory, input, options)
end

function Client:listActivities(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListActivities, input, options)
end

function Client:listExecutions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListExecutions, input, options)
end

function Client:listMapRuns(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListMapRuns, input, options)
end

function Client:listStateMachineAliases(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListStateMachineAliases, input, options)
end

function Client:listStateMachines(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListStateMachines, input, options)
end

function Client:listStateMachineVersions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListStateMachineVersions, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:publishStateMachineVersion(input, options)
    return self:invokeOperation(schemas.Service, schemas.PublishStateMachineVersion, input, options)
end

function Client:redriveExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.RedriveExecution, input, options)
end

function Client:sendTaskFailure(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendTaskFailure, input, options)
end

function Client:sendTaskHeartbeat(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendTaskHeartbeat, input, options)
end

function Client:sendTaskSuccess(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendTaskSuccess, input, options)
end

function Client:startExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartExecution, input, options)
end

function Client:startSyncExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartSyncExecution, input, options)
end

function Client:stopExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.StopExecution, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:testState(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestState, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateMapRun(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateMapRun, input, options)
end

function Client:updateStateMachine(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateStateMachine, input, options)
end

function Client:updateStateMachineAlias(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateStateMachineAlias, input, options)
end

function Client:validateStateMachineDefinition(input, options)
    return self:invokeOperation(schemas.Service, schemas.ValidateStateMachineDefinition, input, options)
end

return M
