local M = {}

M.LocalHealthEventsConfigStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.LogDeliveryStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.MonitorConfigState = {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    ERROR = "ERROR",
}

M.Operator = {
    EQUALS = "EQUALS",
    NOT_EQUALS = "NOT_EQUALS",
}

M.TriangulationEventType = {
    AWS = "AWS",
    INTERNET = "Internet",
}

M.HealthEventStatus = {
    ACTIVE = "ACTIVE",
    RESOLVED = "RESOLVED",
}

M.HealthEventImpactType = {
    AVAILABILITY = "AVAILABILITY",
    PERFORMANCE = "PERFORMANCE",
    LOCAL_AVAILABILITY = "LOCAL_AVAILABILITY",
    LOCAL_PERFORMANCE = "LOCAL_PERFORMANCE",
}

M.InternetEventStatus = {
    ACTIVE = "ACTIVE",
    RESOLVED = "RESOLVED",
}

M.InternetEventType = {
    AVAILABILITY = "AVAILABILITY",
    PERFORMANCE = "PERFORMANCE",
}

M.MonitorProcessingStatusCode = {
    OK = "OK",
    INACTIVE = "INACTIVE",
    COLLECTING_DATA = "COLLECTING_DATA",
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA",
    FAULT_SERVICE = "FAULT_SERVICE",
    FAULT_ACCESS_CLOUDWATCH = "FAULT_ACCESS_CLOUDWATCH",
}

M.QueryStatus = {
    QUEUED = "QUEUED",
    RUNNING = "RUNNING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
}

M.QueryType = {
    MEASUREMENTS = "MEASUREMENTS",
    TOP_LOCATIONS = "TOP_LOCATIONS",
    TOP_LOCATION_DETAILS = "TOP_LOCATION_DETAILS",
    OVERALL_TRAFFIC_SUGGESTIONS = "OVERALL_TRAFFIC_SUGGESTIONS",
    OVERALL_TRAFFIC_SUGGESTIONS_DETAILS = "OVERALL_TRAFFIC_SUGGESTIONS_DETAILS",
    ROUTING_SUGGESTIONS = "ROUTING_SUGGESTIONS",
}

return M
