local record M
    pages_list_component_outputs: function(client: table, input: table): function(): table, table
    items_list_component_outputs: function(client: table, input: table): function(): any
    pages_list_component_provisioned_resources: function(client: table, input: table): function(): table, table
    items_list_component_provisioned_resources: function(client: table, input: table): function(): any
    pages_list_components: function(client: table, input: table): function(): table, table
    items_list_components: function(client: table, input: table): function(): any
    pages_list_deployments: function(client: table, input: table): function(): table, table
    items_list_deployments: function(client: table, input: table): function(): any
    pages_list_environment_account_connections: function(client: table, input: table): function(): table, table
    items_list_environment_account_connections: function(client: table, input: table): function(): any
    pages_list_environment_outputs: function(client: table, input: table): function(): table, table
    items_list_environment_outputs: function(client: table, input: table): function(): any
    pages_list_environment_provisioned_resources: function(client: table, input: table): function(): table, table
    items_list_environment_provisioned_resources: function(client: table, input: table): function(): any
    pages_list_environment_template_versions: function(client: table, input: table): function(): table, table
    items_list_environment_template_versions: function(client: table, input: table): function(): any
    pages_list_environment_templates: function(client: table, input: table): function(): table, table
    items_list_environment_templates: function(client: table, input: table): function(): any
    pages_list_environments: function(client: table, input: table): function(): table, table
    items_list_environments: function(client: table, input: table): function(): any
    pages_list_repositories: function(client: table, input: table): function(): table, table
    items_list_repositories: function(client: table, input: table): function(): any
    pages_list_repository_sync_definitions: function(client: table, input: table): function(): table, table
    items_list_repository_sync_definitions: function(client: table, input: table): function(): any
    pages_list_service_instance_outputs: function(client: table, input: table): function(): table, table
    items_list_service_instance_outputs: function(client: table, input: table): function(): any
    pages_list_service_instance_provisioned_resources: function(client: table, input: table): function(): table, table
    items_list_service_instance_provisioned_resources: function(client: table, input: table): function(): any
    pages_list_service_instances: function(client: table, input: table): function(): table, table
    items_list_service_instances: function(client: table, input: table): function(): any
    pages_list_service_pipeline_outputs: function(client: table, input: table): function(): table, table
    items_list_service_pipeline_outputs: function(client: table, input: table): function(): any
    pages_list_service_pipeline_provisioned_resources: function(client: table, input: table): function(): table, table
    items_list_service_pipeline_provisioned_resources: function(client: table, input: table): function(): any
    pages_list_service_template_versions: function(client: table, input: table): function(): table, table
    items_list_service_template_versions: function(client: table, input: table): function(): any
    pages_list_service_templates: function(client: table, input: table): function(): table, table
    items_list_service_templates: function(client: table, input: table): function(): any
    pages_list_services: function(client: table, input: table): function(): table, table
    items_list_services: function(client: table, input: table): function(): any
    pages_list_tags_for_resource: function(client: table, input: table): function(): table, table
    items_list_tags_for_resource: function(client: table, input: table): function(): any
end

return M
