-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("mq.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("mq.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "mq"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "mq", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createBroker(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateBroker, input, options)
end

function Client:createConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConfiguration, input, options)
end

function Client:createTags(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTags, input, options)
end

function Client:createUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateUser, input, options)
end

function Client:deleteBroker(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteBroker, input, options)
end

function Client:deleteConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConfiguration, input, options)
end

function Client:deleteTags(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTags, input, options)
end

function Client:deleteUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteUser, input, options)
end

function Client:describeBroker(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeBroker, input, options)
end

function Client:describeBrokerEngineTypes(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeBrokerEngineTypes, input, options)
end

function Client:describeBrokerInstanceOptions(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeBrokerInstanceOptions, input, options)
end

function Client:describeConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeConfiguration, input, options)
end

function Client:describeConfigurationRevision(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeConfigurationRevision, input, options)
end

function Client:describeUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeUser, input, options)
end

function Client:listBrokers(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListBrokers, input, options)
end

function Client:listConfigurationRevisions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConfigurationRevisions, input, options)
end

function Client:listConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConfigurations, input, options)
end

function Client:listTags(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTags, input, options)
end

function Client:listUsers(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListUsers, input, options)
end

function Client:promote(input, options)
    return self:invokeOperation(schemas.Service, schemas.Promote, input, options)
end

function Client:rebootBroker(input, options)
    return self:invokeOperation(schemas.Service, schemas.RebootBroker, input, options)
end

function Client:updateBroker(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateBroker, input, options)
end

function Client:updateConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateConfiguration, input, options)
end

function Client:updateUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateUser, input, options)
end

return M
