local M = {}

M.NotificationMessageType = {
    NEW_INSIGHT = "NEW_INSIGHT",
    CLOSED_INSIGHT = "CLOSED_INSIGHT",
    NEW_ASSOCIATION = "NEW_ASSOCIATION",
    SEVERITY_UPGRADED = "SEVERITY_UPGRADED",
    NEW_RECOMMENDATION = "NEW_RECOMMENDATION",
}

M.InsightSeverity = {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH",
}

M.ValidationExceptionReason = {
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION",
    CANNOT_PARSE = "CANNOT_PARSE",
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED",
    OTHER = "OTHER",
    INVALID_PARAMETER_COMBINATION = "INVALID_PARAMETER_COMBINATION",
    PARAMETER_INCONSISTENT_WITH_SERVICE_STATE = "PARAMETER_INCONSISTENT_WITH_SERVICE_STATE",
}

M.EventSourceOptInStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.LogAnomalyType = {
    KEYWORD = "KEYWORD",
    KEYWORD_TOKEN = "KEYWORD_TOKEN",
    FORMAT = "FORMAT",
    HTTP_CODE = "HTTP_CODE",
    BLOCK_FORMAT = "BLOCK_FORMAT",
    NUMERICAL_POINT = "NUMERICAL_POINT",
    NUMERICAL_NAN = "NUMERICAL_NAN",
    NEW_FIELD_NAME = "NEW_FIELD_NAME",
}

M.AnomalySeverity = {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH",
}

M.CloudWatchMetricDataStatusCode = {
    COMPLETE = "Complete",
    INTERNAL_ERROR = "InternalError",
    PARTIAL_DATA = "PartialData",
}

M.CloudWatchMetricsStat = {
    SUM = "Sum",
    AVERAGE = "Average",
    SAMPLE_COUNT = "SampleCount",
    MINIMUM = "Minimum",
    MAXIMUM = "Maximum",
    P99 = "p99",
    P90 = "p90",
    P50 = "p50",
}

M.AnomalyStatus = {
    ONGOING = "ONGOING",
    CLOSED = "CLOSED",
}

M.AnomalyType = {
    CAUSAL = "CAUSAL",
    CONTEXTUAL = "CONTEXTUAL",
}

M.InsightFeedbackOption = {
    VALID_COLLECTION = "VALID_COLLECTION",
    RECOMMENDATION_USEFUL = "RECOMMENDATION_USEFUL",
    ALERT_TOO_SENSITIVE = "ALERT_TOO_SENSITIVE",
    DATA_NOISY_ANOMALY = "DATA_NOISY_ANOMALY",
    DATA_INCORRECT = "DATA_INCORRECT",
}

M.InsightStatus = {
    ONGOING = "ONGOING",
    CLOSED = "CLOSED",
}

M.OrganizationResourceCollectionType = {
    AWS_CLOUD_FORMATION = "AWS_CLOUD_FORMATION",
    AWS_SERVICE = "AWS_SERVICE",
    AWS_ACCOUNT = "AWS_ACCOUNT",
    AWS_TAGS = "AWS_TAGS",
}

M.ServiceName = {
    API_GATEWAY = "API_GATEWAY",
    APPLICATION_ELB = "APPLICATION_ELB",
    AUTO_SCALING_GROUP = "AUTO_SCALING_GROUP",
    CLOUD_FRONT = "CLOUD_FRONT",
    DYNAMO_DB = "DYNAMO_DB",
    EC2 = "EC2",
    ECS = "ECS",
    EKS = "EKS",
    ELASTIC_BEANSTALK = "ELASTIC_BEANSTALK",
    ELASTI_CACHE = "ELASTI_CACHE",
    ELB = "ELB",
    ES = "ES",
    KINESIS = "KINESIS",
    LAMBDA = "LAMBDA",
    NAT_GATEWAY = "NAT_GATEWAY",
    NETWORK_ELB = "NETWORK_ELB",
    RDS = "RDS",
    REDSHIFT = "REDSHIFT",
    ROUTE_53 = "ROUTE_53",
    S3 = "S3",
    SAGE_MAKER = "SAGE_MAKER",
    SNS = "SNS",
    SQS = "SQS",
    STEP_FUNCTIONS = "STEP_FUNCTIONS",
    SWF = "SWF",
}

M.ResourceCollectionType = {
    AWS_CLOUD_FORMATION = "AWS_CLOUD_FORMATION",
    AWS_SERVICE = "AWS_SERVICE",
    AWS_TAGS = "AWS_TAGS",
}

M.OptInStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.ServerSideEncryptionType = {
    CUSTOMER_MANAGED_KEY = "CUSTOMER_MANAGED_KEY",
    AWS_OWNED_KMS_KEY = "AWS_OWNED_KMS_KEY",
}

M.CostEstimationServiceResourceState = {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

M.CostEstimationStatus = {
    ONGOING = "ONGOING",
    COMPLETED = "COMPLETED",
}

M.EventDataSource = {
    AWS_CLOUD_TRAIL = "AWS_CLOUD_TRAIL",
    AWS_CODE_DEPLOY = "AWS_CODE_DEPLOY",
}

M.EventClass = {
    INFRASTRUCTURE = "INFRASTRUCTURE",
    DEPLOYMENT = "DEPLOYMENT",
    SECURITY_CHANGE = "SECURITY_CHANGE",
    CONFIG_CHANGE = "CONFIG_CHANGE",
    SCHEMA_CHANGE = "SCHEMA_CHANGE",
}

M.InsightType = {
    REACTIVE = "REACTIVE",
    PROACTIVE = "PROACTIVE",
}

M.ResourcePermission = {
    FULL_PERMISSION = "FULL_PERMISSION",
    MISSING_PERMISSION = "MISSING_PERMISSION",
}

M.ResourceTypeFilter = {
    LOG_GROUPS = "LOG_GROUPS",
    CLOUDFRONT_DISTRIBUTION = "CLOUDFRONT_DISTRIBUTION",
    DYNAMODB_TABLE = "DYNAMODB_TABLE",
    EC2_NAT_GATEWAY = "EC2_NAT_GATEWAY",
    ECS_CLUSTER = "ECS_CLUSTER",
    ECS_SERVICE = "ECS_SERVICE",
    EKS_CLUSTER = "EKS_CLUSTER",
    ELASTIC_BEANSTALK_ENVIRONMENT = "ELASTIC_BEANSTALK_ENVIRONMENT",
    ELASTIC_LOAD_BALANCER_LOAD_BALANCER = "ELASTIC_LOAD_BALANCER_LOAD_BALANCER",
    ELASTIC_LOAD_BALANCING_V2_LOAD_BALANCER = "ELASTIC_LOAD_BALANCING_V2_LOAD_BALANCER",
    ELASTIC_LOAD_BALANCING_V2_TARGET_GROUP = "ELASTIC_LOAD_BALANCING_V2_TARGET_GROUP",
    ELASTICACHE_CACHE_CLUSTER = "ELASTICACHE_CACHE_CLUSTER",
    ELASTICSEARCH_DOMAIN = "ELASTICSEARCH_DOMAIN",
    KINESIS_STREAM = "KINESIS_STREAM",
    LAMBDA_FUNCTION = "LAMBDA_FUNCTION",
    OPEN_SEARCH_SERVICE_DOMAIN = "OPEN_SEARCH_SERVICE_DOMAIN",
    RDS_DB_INSTANCE = "RDS_DB_INSTANCE",
    RDS_DB_CLUSTER = "RDS_DB_CLUSTER",
    REDSHIFT_CLUSTER = "REDSHIFT_CLUSTER",
    ROUTE53_HOSTED_ZONE = "ROUTE53_HOSTED_ZONE",
    ROUTE53_HEALTH_CHECK = "ROUTE53_HEALTH_CHECK",
    S3_BUCKET = "S3_BUCKET",
    SAGEMAKER_ENDPOINT = "SAGEMAKER_ENDPOINT",
    SNS_TOPIC = "SNS_TOPIC",
    SQS_QUEUE = "SQS_QUEUE",
    STEP_FUNCTIONS_ACTIVITY = "STEP_FUNCTIONS_ACTIVITY",
    STEP_FUNCTIONS_STATE_MACHINE = "STEP_FUNCTIONS_STATE_MACHINE",
}

M.Locale = {
    DE_DE = "DE_DE",
    EN_US = "EN_US",
    EN_GB = "EN_GB",
    ES_ES = "ES_ES",
    FR_FR = "FR_FR",
    IT_IT = "IT_IT",
    JA_JP = "JA_JP",
    KO_KR = "KO_KR",
    PT_BR = "PT_BR",
    ZH_CN = "ZH_CN",
    ZH_TW = "ZH_TW",
}

M.UpdateResourceCollectionAction = {
    ADD = "ADD",
    REMOVE = "REMOVE",
}

return M
