local M = {}

M.ApiGatewayEndpointType = {
    REGIONAL = "REGIONAL",
    PRIVATE = "PRIVATE",
}

M.ApplicationState = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    FAILED = "FAILED",
    UPDATING = "UPDATING",
}

M.ErrorCode = {
    INVALID_RESOURCE_STATE = "INVALID_RESOURCE_STATE",
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED",
    RESOURCE_CREATION_FAILURE = "RESOURCE_CREATION_FAILURE",
    RESOURCE_UPDATE_FAILURE = "RESOURCE_UPDATE_FAILURE",
    SERVICE_ENDPOINT_HEALTH_CHECK_FAILURE = "SERVICE_ENDPOINT_HEALTH_CHECK_FAILURE",
    RESOURCE_DELETION_FAILURE = "RESOURCE_DELETION_FAILURE",
    RESOURCE_RETRIEVAL_FAILURE = "RESOURCE_RETRIEVAL_FAILURE",
    RESOURCE_IN_USE = "RESOURCE_IN_USE",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    STATE_TRANSITION_FAILURE = "STATE_TRANSITION_FAILURE",
    REQUEST_LIMIT_EXCEEDED = "REQUEST_LIMIT_EXCEEDED",
    NOT_AUTHORIZED = "NOT_AUTHORIZED",
}

M.ErrorResourceType = {
    ENVIRONMENT = "ENVIRONMENT",
    APPLICATION = "APPLICATION",
    ROUTE = "ROUTE",
    SERVICE = "SERVICE",
    TRANSIT_GATEWAY = "TRANSIT_GATEWAY",
    TRANSIT_GATEWAY_ATTACHMENT = "TRANSIT_GATEWAY_ATTACHMENT",
    API_GATEWAY = "API_GATEWAY",
    NLB = "NLB",
    TARGET_GROUP = "TARGET_GROUP",
    LOAD_BALANCER_LISTENER = "LOAD_BALANCER_LISTENER",
    VPC_LINK = "VPC_LINK",
    LAMBDA = "LAMBDA",
    VPC = "VPC",
    SUBNET = "SUBNET",
    ROUTE_TABLE = "ROUTE_TABLE",
    SECURITY_GROUP = "SECURITY_GROUP",
    VPC_ENDPOINT_SERVICE_CONFIGURATION = "VPC_ENDPOINT_SERVICE_CONFIGURATION",
    RESOURCE_SHARE = "RESOURCE_SHARE",
    IAM_ROLE = "IAM_ROLE",
}

M.ProxyType = {
    API_GATEWAY = "API_GATEWAY",
}

M.NetworkFabricType = {
    TRANSIT_GATEWAY = "TRANSIT_GATEWAY",
    NONE = "NONE",
}

M.EnvironmentState = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    FAILED = "FAILED",
}

M.RouteActivationState = {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

M.RouteType = {
    DEFAULT = "DEFAULT",
    URI_PATH = "URI_PATH",
}

M.HttpMethod = {
    DELETE = "DELETE",
    GET = "GET",
    HEAD = "HEAD",
    OPTIONS = "OPTIONS",
    PATCH = "PATCH",
    POST = "POST",
    PUT = "PUT",
}

M.RouteState = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    FAILED = "FAILED",
    UPDATING = "UPDATING",
    INACTIVE = "INACTIVE",
}

M.ServiceEndpointType = {
    LAMBDA = "LAMBDA",
    URL = "URL",
}

M.ServiceState = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    FAILED = "FAILED",
}

return M
