-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.AWSServiceAccessStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.IndexState = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    DELETED = "DELETED",
    UPDATING = "UPDATING",
}

M.IndexType = {
    LOCAL = "LOCAL",
    AGGREGATOR = "AGGREGATOR",
}

M.OperationStatus = {
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    IN_PROGRESS = "IN_PROGRESS",
    SKIPPED = "SKIPPED",
}

return M
