local M = {}

M.ApprovalState = {
    APPROVE = "APPROVE",
    REVOKE = "REVOKE",
}

M.OverrideStatus = {
    OVERRIDE = "OVERRIDE",
    REVOKE = "REVOKE",
}

M.ConflictDetailLevelTypeEnum = {
    FILE_LEVEL = "FILE_LEVEL",
    LINE_LEVEL = "LINE_LEVEL",
}

M.ConflictResolutionStrategyTypeEnum = {
    NONE = "NONE",
    ACCEPT_SOURCE = "ACCEPT_SOURCE",
    ACCEPT_DESTINATION = "ACCEPT_DESTINATION",
    AUTOMERGE = "AUTOMERGE",
}

M.MergeOptionTypeEnum = {
    FAST_FORWARD_MERGE = "FAST_FORWARD_MERGE",
    SQUASH_MERGE = "SQUASH_MERGE",
    THREE_WAY_MERGE = "THREE_WAY_MERGE",
}

M.FileModeTypeEnum = {
    EXECUTABLE = "EXECUTABLE",
    NORMAL = "NORMAL",
    SYMLINK = "SYMLINK",
}

M.ChangeTypeEnum = {
    ADDED = "A",
    MODIFIED = "M",
    DELETED = "D",
}

M.ObjectTypeEnum = {
    FILE = "FILE",
    DIRECTORY = "DIRECTORY",
    GIT_LINK = "GIT_LINK",
    SYMBOLIC_LINK = "SYMBOLIC_LINK",
}

M.BatchGetRepositoriesErrorCodeEnum = {
    ENCRYPTION_INTEGRITY_CHECKS_FAILED_EXCEPTION = "EncryptionIntegrityChecksFailedException",
    ENCRYPTION_KEY_ACCESS_DENIED_EXCEPTION = "EncryptionKeyAccessDeniedException",
    ENCRYPTION_KEY_DISABLED_EXCEPTION = "EncryptionKeyDisabledException",
    ENCRYPTION_KEY_NOT_FOUND_EXCEPTION = "EncryptionKeyNotFoundException",
    ENCRYPTION_KEY_UNAVAILABLE_EXCEPTION = "EncryptionKeyUnavailableException",
    REPOSITORY_DOES_NOT_EXIST_EXCEPTION = "RepositoryDoesNotExistException",
}

M.PullRequestStatusEnum = {
    OPEN = "OPEN",
    CLOSED = "CLOSED",
}

M.ReplacementTypeEnum = {
    KEEP_BASE = "KEEP_BASE",
    KEEP_SOURCE = "KEEP_SOURCE",
    KEEP_DESTINATION = "KEEP_DESTINATION",
    USE_NEW_CONTENT = "USE_NEW_CONTENT",
}

M.PullRequestEventType = {
    PULL_REQUEST_CREATED = "PULL_REQUEST_CREATED",
    PULL_REQUEST_STATUS_CHANGED = "PULL_REQUEST_STATUS_CHANGED",
    PULL_REQUEST_SOURCE_REFERENCE_UPDATED = "PULL_REQUEST_SOURCE_REFERENCE_UPDATED",
    PULL_REQUEST_MERGE_STATE_CHANGED = "PULL_REQUEST_MERGE_STATE_CHANGED",
    PULL_REQUEST_APPROVAL_RULE_CREATED = "PULL_REQUEST_APPROVAL_RULE_CREATED",
    PULL_REQUEST_APPROVAL_RULE_UPDATED = "PULL_REQUEST_APPROVAL_RULE_UPDATED",
    PULL_REQUEST_APPROVAL_RULE_DELETED = "PULL_REQUEST_APPROVAL_RULE_DELETED",
    PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN = "PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN",
    PULL_REQUEST_APPROVAL_STATE_CHANGED = "PULL_REQUEST_APPROVAL_STATE_CHANGED",
}

M.RelativeFileVersionEnum = {
    BEFORE = "BEFORE",
    AFTER = "AFTER",
}

M.RepositoryTriggerEventEnum = {
    ALL = "all",
    UPDATE_REFERENCE = "updateReference",
    CREATE_REFERENCE = "createReference",
    DELETE_REFERENCE = "deleteReference",
}

M.OrderEnum = {
    ASCENDING = "ascending",
    DESCENDING = "descending",
}

M.SortByEnum = {
    REPOSITORY_NAME = "repositoryName",
    MODIFIED_DATE = "lastModifiedDate",
}

return M
