-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("mediapackagevod.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("mediapackagevod.schemas")
local sdk_defaults = require("aws.sdk_defaults")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "MediaPackageVod"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(operation)
            local options = {}
            for _, scheme_id in ipairs(operation.effective_auth_schemes) do
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "mediapackage-vod", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:configureLogs(input, options)
    return self:invokeOperation(input, {
        name = "ConfigureLogs",
        input_schema = schemas.ConfigureLogsInput,
        output_schema = schemas.ConfigureLogsOutput,
        http_method = "PUT",
        http_path = "/packaging_groups/{Id}/configure_logs",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createAsset(input, options)
    return self:invokeOperation(input, {
        name = "CreateAsset",
        input_schema = schemas.CreateAssetInput,
        output_schema = schemas.CreateAssetOutput,
        http_method = "POST",
        http_path = "/assets",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createPackagingConfiguration(input, options)
    return self:invokeOperation(input, {
        name = "CreatePackagingConfiguration",
        input_schema = schemas.CreatePackagingConfigurationInput,
        output_schema = schemas.CreatePackagingConfigurationOutput,
        http_method = "POST",
        http_path = "/packaging_configurations",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createPackagingGroup(input, options)
    return self:invokeOperation(input, {
        name = "CreatePackagingGroup",
        input_schema = schemas.CreatePackagingGroupInput,
        output_schema = schemas.CreatePackagingGroupOutput,
        http_method = "POST",
        http_path = "/packaging_groups",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deleteAsset(input, options)
    return self:invokeOperation(input, {
        name = "DeleteAsset",
        input_schema = schemas.DeleteAssetInput,
        output_schema = schemas.DeleteAssetOutput,
        http_method = "DELETE",
        http_path = "/assets/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deletePackagingConfiguration(input, options)
    return self:invokeOperation(input, {
        name = "DeletePackagingConfiguration",
        input_schema = schemas.DeletePackagingConfigurationInput,
        output_schema = schemas.DeletePackagingConfigurationOutput,
        http_method = "DELETE",
        http_path = "/packaging_configurations/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deletePackagingGroup(input, options)
    return self:invokeOperation(input, {
        name = "DeletePackagingGroup",
        input_schema = schemas.DeletePackagingGroupInput,
        output_schema = schemas.DeletePackagingGroupOutput,
        http_method = "DELETE",
        http_path = "/packaging_groups/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:describeAsset(input, options)
    return self:invokeOperation(input, {
        name = "DescribeAsset",
        input_schema = schemas.DescribeAssetInput,
        output_schema = schemas.DescribeAssetOutput,
        http_method = "GET",
        http_path = "/assets/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:describePackagingConfiguration(input, options)
    return self:invokeOperation(input, {
        name = "DescribePackagingConfiguration",
        input_schema = schemas.DescribePackagingConfigurationInput,
        output_schema = schemas.DescribePackagingConfigurationOutput,
        http_method = "GET",
        http_path = "/packaging_configurations/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:describePackagingGroup(input, options)
    return self:invokeOperation(input, {
        name = "DescribePackagingGroup",
        input_schema = schemas.DescribePackagingGroupInput,
        output_schema = schemas.DescribePackagingGroupOutput,
        http_method = "GET",
        http_path = "/packaging_groups/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listAssets(input, options)
    return self:invokeOperation(input, {
        name = "ListAssets",
        input_schema = schemas.ListAssetsInput,
        output_schema = schemas.ListAssetsOutput,
        http_method = "GET",
        http_path = "/assets",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listPackagingConfigurations(input, options)
    return self:invokeOperation(input, {
        name = "ListPackagingConfigurations",
        input_schema = schemas.ListPackagingConfigurationsInput,
        output_schema = schemas.ListPackagingConfigurationsOutput,
        http_method = "GET",
        http_path = "/packaging_configurations",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listPackagingGroups(input, options)
    return self:invokeOperation(input, {
        name = "ListPackagingGroups",
        input_schema = schemas.ListPackagingGroupsInput,
        output_schema = schemas.ListPackagingGroupsOutput,
        http_method = "GET",
        http_path = "/packaging_groups",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(input, {
        name = "ListTagsForResource",
        input_schema = schemas.ListTagsForResourceInput,
        output_schema = schemas.ListTagsForResourceOutput,
        http_method = "GET",
        http_path = "/tags/{ResourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(input, {
        name = "TagResource",
        input_schema = schemas.TagResourceInput,
        output_schema = schemas.TagResourceOutput,
        http_method = "POST",
        http_path = "/tags/{ResourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(input, {
        name = "UntagResource",
        input_schema = schemas.UntagResourceInput,
        output_schema = schemas.UntagResourceOutput,
        http_method = "DELETE",
        http_path = "/tags/{ResourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:updatePackagingGroup(input, options)
    return self:invokeOperation(input, {
        name = "UpdatePackagingGroup",
        input_schema = schemas.UpdatePackagingGroupInput,
        output_schema = schemas.UpdatePackagingGroupOutput,
        http_method = "PUT",
        http_path = "/packaging_groups/{Id}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

return M
