-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("mediapackagevod.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("mediapackagevod.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "MediaPackageVod"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "mediapackage-vod", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:configureLogs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ConfigureLogs, input, options)
end

function Client:createAsset(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateAsset, input, options)
end

function Client:createPackagingConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreatePackagingConfiguration, input, options)
end

function Client:createPackagingGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreatePackagingGroup, input, options)
end

function Client:deleteAsset(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAsset, input, options)
end

function Client:deletePackagingConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeletePackagingConfiguration, input, options)
end

function Client:deletePackagingGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeletePackagingGroup, input, options)
end

function Client:describeAsset(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeAsset, input, options)
end

function Client:describePackagingConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribePackagingConfiguration, input, options)
end

function Client:describePackagingGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribePackagingGroup, input, options)
end

function Client:listAssets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAssets, input, options)
end

function Client:listPackagingConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPackagingConfigurations, input, options)
end

function Client:listPackagingGroups(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPackagingGroups, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updatePackagingGroup(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdatePackagingGroup, input, options)
end

return M
