local M = {}

M.FulfillmentOptionType = {
    AMAZON_MACHINE_IMAGE = "AMAZON_MACHINE_IMAGE",
    API = "API",
    CLOUDFORMATION_TEMPLATE = "CLOUDFORMATION_TEMPLATE",
    CONTAINER = "CONTAINER",
    HELM = "HELM",
    EKS_ADD_ON = "EKS_ADD_ON",
    EC2_IMAGE_BUILDER_COMPONENT = "EC2_IMAGE_BUILDER_COMPONENT",
    DATA_EXCHANGE = "DATA_EXCHANGE",
    PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES",
    SAAS = "SAAS",
    SAGEMAKER_ALGORITHM = "SAGEMAKER_ALGORITHM",
    SAGEMAKER_MODEL = "SAGEMAKER_MODEL",
}

M.ListingBadgeType = {
    AWS_FREE_TIER = "AWS_FREE_TIER",
    FREE_TRIAL = "FREE_TRIAL",
    DEPLOYED_ON_AWS = "DEPLOYED_ON_AWS",
    QUICK_LAUNCH = "QUICK_LAUNCH",
    MULTI_PRODUCT = "MULTI_PRODUCT",
}

M.PricingModelType = {
    USAGE = "USAGE",
    CONTRACT = "CONTRACT",
    BYOL = "BYOL",
    FREE = "FREE",
}

M.PricingUnitType = {
    USERS = "USERS",
    HOSTS = "HOSTS",
    BANDWIDTH = "BANDWIDTH",
    DATA = "DATA",
    TIERS = "TIERS",
    REQUESTS = "REQUESTS",
    UNITS = "UNITS",
}

M.ResourceContentType = {
    EMAIL = "EMAIL",
    PHONE_NUMBER = "PHONE_NUMBER",
    LINK = "LINK",
    OTHER = "OTHER",
}

M.ResourceType = {
    MANUFACTURER_SUPPORT = "MANUFACTURER_SUPPORT",
    MANUFACTURER_INSTRUCTIONS = "MANUFACTURER_INSTRUCTIONS",
}

M.ReviewSourceId = {
    AWS_MARKETPLACE = "AWS_MARKETPLACE",
}

M.SellerEngagementContentType = {
    LINK = "LINK",
}

M.SellerEngagementType = {
    REQUEST_FOR_PRIVATE_OFFER = "REQUEST_FOR_PRIVATE_OFFER",
    REQUEST_FOR_DEMO = "REQUEST_FOR_DEMO",
}

M.ValidationExceptionReason = {
    INVALID_PAGINATION_TOKEN = "INVALID_PAGINATION_TOKEN",
    MALFORMED_REQUEST_PARAMETERS = "MALFORMED_REQUEST_PARAMETERS",
    PAGINATION_LIMIT_EXCEEDED = "PAGINATION_LIMIT_EXCEEDED",
}

M.PurchaseOptionBadgeType = {
    PRIVATE_PRICING = "PRIVATE_PRICING",
    FUTURE_DATED = "FUTURE_DATED",
    REPLACEMENT_OFFER = "REPLACEMENT_OFFER",
}

M.TermType = {
    BYOL_PRICING_TERM = "ByolPricingTerm",
    CONFIGURABLE_UPFRONT_PRICING_TERM = "ConfigurableUpfrontPricingTerm",
    FIXED_UPFRONT_PRICING_TERM = "FixedUpfrontPricingTerm",
    USAGE_BASED_PRICING_TERM = "UsageBasedPricingTerm",
    FREE_TRIAL_PRICING_TERM = "FreeTrialPricingTerm",
    LEGAL_TERM = "LegalTerm",
    PAYMENT_SCHEDULE_TERM = "PaymentScheduleTerm",
    RECURRING_PAYMENT_TERM = "RecurringPaymentTerm",
    RENEWAL_TERM = "RenewalTerm",
    SUPPORT_TERM = "SupportTerm",
    VALIDITY_TERM = "ValidityTerm",
    VARIABLE_PAYMENT_TERM = "VariablePaymentTerm",
}

M.RateCardConstraintType = {
    ALLOWED = "Allowed",
    DISALLOWED = "Disallowed",
}

M.DimensionLabelType = {
    REGION = "Region",
    SAGEMAKER_OPTION = "SagemakerOption",
}

M.SelectorType = {
    DURATION = "Duration",
}

M.LegalDocumentType = {
    CUSTOM_EULA = "CustomEula",
    CUSTOM_DSA = "CustomDsa",
    ENTERPRISE_EULA = "EnterpriseEula",
    STANDARD_EULA = "StandardEula",
    STANDARD_DSA = "StandardDsa",
}

M.BillingPeriodType = {
    MONTHLY = "Monthly",
}

M.DeployedOnAwsStatus = {
    DEPLOYED = "DEPLOYED",
    NOT_DEPLOYED = "NOT_DEPLOYED",
    NOT_APPLICABLE = "NOT_APPLICABLE",
}

M.PurchaseOptionFilterType = {
    PRODUCT_ID = "PRODUCT_ID",
    SELLER_OF_RECORD_PROFILE_ID = "SELLER_OF_RECORD_PROFILE_ID",
    PURCHASE_OPTION_TYPE = "PURCHASE_OPTION_TYPE",
    VISIBILITY_SCOPE = "VISIBILITY_SCOPE",
    AVAILABILITY_STATUS = "AVAILABILITY_STATUS",
}

M.PurchaseOptionType = {
    OFFER = "OFFER",
    OFFERSET = "OFFERSET",
}

M.SearchFacetType = {
    AVERAGE_CUSTOMER_RATING = "AVERAGE_CUSTOMER_RATING",
    CATEGORY = "CATEGORY",
    PUBLISHER = "PUBLISHER",
    FULFILLMENT_OPTION_TYPE = "FULFILLMENT_OPTION_TYPE",
    PRICING_MODEL = "PRICING_MODEL",
    PRICING_UNIT = "PRICING_UNIT",
    DEPLOYED_ON_AWS = "DEPLOYED_ON_AWS",
    NUMBER_OF_PRODUCTS = "NUMBER_OF_PRODUCTS",
}

M.SearchFilterType = {
    MIN_AVERAGE_CUSTOMER_RATING = "MIN_AVERAGE_CUSTOMER_RATING",
    MAX_AVERAGE_CUSTOMER_RATING = "MAX_AVERAGE_CUSTOMER_RATING",
    CATEGORY = "CATEGORY",
    PUBLISHER = "PUBLISHER",
    FULFILLMENT_OPTION_TYPE = "FULFILLMENT_OPTION_TYPE",
    PRICING_MODEL = "PRICING_MODEL",
    PRICING_UNIT = "PRICING_UNIT",
    DEPLOYED_ON_AWS = "DEPLOYED_ON_AWS",
    NUMBER_OF_PRODUCTS = "NUMBER_OF_PRODUCTS",
}

M.SearchListingsSortBy = {
    RELEVANCE = "RELEVANCE",
    AVERAGE_CUSTOMER_RATING = "AVERAGE_CUSTOMER_RATING",
}

M.SearchListingsSortOrder = {
    DESCENDING = "DESCENDING",
    ASCENDING = "ASCENDING",
}

return M
