-- Code generated by lua-client-codegen. DO NOT EDIT.

local awsjson_protocol = require("smithy.protocol.awsjson")
local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("transfer.endpoint_rules")
local schemas = require("transfer.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "TransferService"
    if not cfg.protocol then
        cfg.protocol = awsjson_protocol.new({ version = "1.1", service_id = cfg.service_id })
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "transfer", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createAccess(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateAccess, input, options)
end

function Client:createAgreement(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateAgreement, input, options)
end

function Client:createConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConnector, input, options)
end

function Client:createProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateProfile, input, options)
end

function Client:createServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateServer, input, options)
end

function Client:createUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateUser, input, options)
end

function Client:createWebApp(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateWebApp, input, options)
end

function Client:createWorkflow(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateWorkflow, input, options)
end

function Client:deleteAccess(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAccess, input, options)
end

function Client:deleteAgreement(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAgreement, input, options)
end

function Client:deleteCertificate(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCertificate, input, options)
end

function Client:deleteConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConnector, input, options)
end

function Client:deleteHostKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteHostKey, input, options)
end

function Client:deleteProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteProfile, input, options)
end

function Client:deleteServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteServer, input, options)
end

function Client:deleteSshPublicKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteSshPublicKey, input, options)
end

function Client:deleteUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteUser, input, options)
end

function Client:deleteWebApp(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteWebApp, input, options)
end

function Client:deleteWebAppCustomization(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteWebAppCustomization, input, options)
end

function Client:deleteWorkflow(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteWorkflow, input, options)
end

function Client:describeAccess(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeAccess, input, options)
end

function Client:describeAgreement(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeAgreement, input, options)
end

function Client:describeCertificate(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeCertificate, input, options)
end

function Client:describeConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeConnector, input, options)
end

function Client:describeExecution(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeExecution, input, options)
end

function Client:describeHostKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeHostKey, input, options)
end

function Client:describeProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeProfile, input, options)
end

function Client:describeSecurityPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeSecurityPolicy, input, options)
end

function Client:describeServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeServer, input, options)
end

function Client:describeUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeUser, input, options)
end

function Client:describeWebApp(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeWebApp, input, options)
end

function Client:describeWebAppCustomization(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeWebAppCustomization, input, options)
end

function Client:describeWorkflow(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeWorkflow, input, options)
end

function Client:importCertificate(input, options)
    return self:invokeOperation(schemas.Service, schemas.ImportCertificate, input, options)
end

function Client:importHostKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.ImportHostKey, input, options)
end

function Client:importSshPublicKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.ImportSshPublicKey, input, options)
end

function Client:listAccesses(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAccesses, input, options)
end

function Client:listAgreements(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAgreements, input, options)
end

function Client:listCertificates(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCertificates, input, options)
end

function Client:listConnectors(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConnectors, input, options)
end

function Client:listExecutions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListExecutions, input, options)
end

function Client:listFileTransferResults(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListFileTransferResults, input, options)
end

function Client:listHostKeys(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListHostKeys, input, options)
end

function Client:listProfiles(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListProfiles, input, options)
end

function Client:listSecurityPolicies(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListSecurityPolicies, input, options)
end

function Client:listServers(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListServers, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:listUsers(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListUsers, input, options)
end

function Client:listWebApps(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListWebApps, input, options)
end

function Client:listWorkflows(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListWorkflows, input, options)
end

function Client:sendWorkflowStepState(input, options)
    return self:invokeOperation(schemas.Service, schemas.SendWorkflowStepState, input, options)
end

function Client:startDirectoryListing(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartDirectoryListing, input, options)
end

function Client:startFileTransfer(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartFileTransfer, input, options)
end

function Client:startRemoteDelete(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartRemoteDelete, input, options)
end

function Client:startRemoteMove(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartRemoteMove, input, options)
end

function Client:startServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartServer, input, options)
end

function Client:stopServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.StopServer, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:testConnection(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestConnection, input, options)
end

function Client:testIdentityProvider(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestIdentityProvider, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateAccess(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateAccess, input, options)
end

function Client:updateAgreement(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateAgreement, input, options)
end

function Client:updateCertificate(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateCertificate, input, options)
end

function Client:updateConnector(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateConnector, input, options)
end

function Client:updateHostKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateHostKey, input, options)
end

function Client:updateProfile(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateProfile, input, options)
end

function Client:updateServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateServer, input, options)
end

function Client:updateUser(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateUser, input, options)
end

function Client:updateWebApp(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateWebApp, input, options)
end

function Client:updateWebAppCustomization(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateWebAppCustomization, input, options)
end

return M
