-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("cleanroomsml.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("cleanroomsml.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AWSStarkControlService"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "cleanrooms-ml", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:cancelTrainedModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.CancelTrainedModel, input, options)
end

function Client:cancelTrainedModelInferenceJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.CancelTrainedModelInferenceJob, input, options)
end

function Client:createAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateAudienceModel, input, options)
end

function Client:createConfiguredAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConfiguredAudienceModel, input, options)
end

function Client:createConfiguredModelAlgorithm(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConfiguredModelAlgorithm, input, options)
end

function Client:createConfiguredModelAlgorithmAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateConfiguredModelAlgorithmAssociation, input, options)
end

function Client:createMLInputChannel(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateMLInputChannel, input, options)
end

function Client:createTrainedModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTrainedModel, input, options)
end

function Client:createTrainingDataset(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTrainingDataset, input, options)
end

function Client:deleteAudienceGenerationJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAudienceGenerationJob, input, options)
end

function Client:deleteAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteAudienceModel, input, options)
end

function Client:deleteConfiguredAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConfiguredAudienceModel, input, options)
end

function Client:deleteConfiguredAudienceModelPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConfiguredAudienceModelPolicy, input, options)
end

function Client:deleteConfiguredModelAlgorithm(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConfiguredModelAlgorithm, input, options)
end

function Client:deleteConfiguredModelAlgorithmAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteConfiguredModelAlgorithmAssociation, input, options)
end

function Client:deleteMLConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteMLConfiguration, input, options)
end

function Client:deleteMLInputChannelData(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteMLInputChannelData, input, options)
end

function Client:deleteTrainedModelOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTrainedModelOutput, input, options)
end

function Client:deleteTrainingDataset(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTrainingDataset, input, options)
end

function Client:getAudienceGenerationJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetAudienceGenerationJob, input, options)
end

function Client:getAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetAudienceModel, input, options)
end

function Client:getCollaborationConfiguredModelAlgorithmAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCollaborationConfiguredModelAlgorithmAssociation, input, options)
end

function Client:getCollaborationMLInputChannel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCollaborationMLInputChannel, input, options)
end

function Client:getCollaborationTrainedModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCollaborationTrainedModel, input, options)
end

function Client:getConfiguredAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetConfiguredAudienceModel, input, options)
end

function Client:getConfiguredAudienceModelPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetConfiguredAudienceModelPolicy, input, options)
end

function Client:getConfiguredModelAlgorithm(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetConfiguredModelAlgorithm, input, options)
end

function Client:getConfiguredModelAlgorithmAssociation(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetConfiguredModelAlgorithmAssociation, input, options)
end

function Client:getMLConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetMLConfiguration, input, options)
end

function Client:getMLInputChannel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetMLInputChannel, input, options)
end

function Client:getTrainedModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrainedModel, input, options)
end

function Client:getTrainedModelInferenceJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrainedModelInferenceJob, input, options)
end

function Client:getTrainingDataset(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrainingDataset, input, options)
end

function Client:listAudienceExportJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAudienceExportJobs, input, options)
end

function Client:listAudienceGenerationJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAudienceGenerationJobs, input, options)
end

function Client:listAudienceModels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAudienceModels, input, options)
end

function Client:listCollaborationConfiguredModelAlgorithmAssociations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCollaborationConfiguredModelAlgorithmAssociations, input, options)
end

function Client:listCollaborationMLInputChannels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCollaborationMLInputChannels, input, options)
end

function Client:listCollaborationTrainedModelExportJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCollaborationTrainedModelExportJobs, input, options)
end

function Client:listCollaborationTrainedModelInferenceJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCollaborationTrainedModelInferenceJobs, input, options)
end

function Client:listCollaborationTrainedModels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCollaborationTrainedModels, input, options)
end

function Client:listConfiguredAudienceModels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConfiguredAudienceModels, input, options)
end

function Client:listConfiguredModelAlgorithmAssociations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConfiguredModelAlgorithmAssociations, input, options)
end

function Client:listConfiguredModelAlgorithms(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListConfiguredModelAlgorithms, input, options)
end

function Client:listMLInputChannels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListMLInputChannels, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:listTrainedModelInferenceJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrainedModelInferenceJobs, input, options)
end

function Client:listTrainedModels(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrainedModels, input, options)
end

function Client:listTrainedModelVersions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrainedModelVersions, input, options)
end

function Client:listTrainingDatasets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrainingDatasets, input, options)
end

function Client:putConfiguredAudienceModelPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutConfiguredAudienceModelPolicy, input, options)
end

function Client:putMLConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutMLConfiguration, input, options)
end

function Client:startAudienceExportJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartAudienceExportJob, input, options)
end

function Client:startAudienceGenerationJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartAudienceGenerationJob, input, options)
end

function Client:startTrainedModelExportJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartTrainedModelExportJob, input, options)
end

function Client:startTrainedModelInferenceJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartTrainedModelInferenceJob, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateConfiguredAudienceModel(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateConfiguredAudienceModel, input, options)
end

return M
