local record M
    pages_list_account_assignment_creation_status: function(client: table, input: table): function(): table, table
    items_list_account_assignment_creation_status: function(client: table, input: table): function(): any
    pages_list_account_assignment_deletion_status: function(client: table, input: table): function(): table, table
    items_list_account_assignment_deletion_status: function(client: table, input: table): function(): any
    pages_list_account_assignments: function(client: table, input: table): function(): table, table
    items_list_account_assignments: function(client: table, input: table): function(): any
    pages_list_account_assignments_for_principal: function(client: table, input: table): function(): table, table
    items_list_account_assignments_for_principal: function(client: table, input: table): function(): any
    pages_list_accounts_for_provisioned_permission_set: function(client: table, input: table): function(): table, table
    items_list_accounts_for_provisioned_permission_set: function(client: table, input: table): function(): any
    pages_list_application_access_scopes: function(client: table, input: table): function(): table, table
    items_list_application_access_scopes: function(client: table, input: table): function(): any
    pages_list_application_assignments: function(client: table, input: table): function(): table, table
    items_list_application_assignments: function(client: table, input: table): function(): any
    pages_list_application_assignments_for_principal: function(client: table, input: table): function(): table, table
    items_list_application_assignments_for_principal: function(client: table, input: table): function(): any
    pages_list_application_authentication_methods: function(client: table, input: table): function(): table, table
    items_list_application_authentication_methods: function(client: table, input: table): function(): any
    pages_list_application_grants: function(client: table, input: table): function(): table, table
    items_list_application_grants: function(client: table, input: table): function(): any
    pages_list_application_providers: function(client: table, input: table): function(): table, table
    items_list_application_providers: function(client: table, input: table): function(): any
    pages_list_applications: function(client: table, input: table): function(): table, table
    items_list_applications: function(client: table, input: table): function(): any
    pages_list_customer_managed_policy_references_in_permission_set: function(client: table, input: table): function(): table, table
    items_list_customer_managed_policy_references_in_permission_set: function(client: table, input: table): function(): any
    pages_list_instances: function(client: table, input: table): function(): table, table
    items_list_instances: function(client: table, input: table): function(): any
    pages_list_managed_policies_in_permission_set: function(client: table, input: table): function(): table, table
    items_list_managed_policies_in_permission_set: function(client: table, input: table): function(): any
    pages_list_permission_set_provisioning_status: function(client: table, input: table): function(): table, table
    items_list_permission_set_provisioning_status: function(client: table, input: table): function(): any
    pages_list_permission_sets: function(client: table, input: table): function(): table, table
    items_list_permission_sets: function(client: table, input: table): function(): any
    pages_list_permission_sets_provisioned_to_account: function(client: table, input: table): function(): table, table
    items_list_permission_sets_provisioned_to_account: function(client: table, input: table): function(): any
    pages_list_regions: function(client: table, input: table): function(): table, table
    items_list_regions: function(client: table, input: table): function(): any
    pages_list_tags_for_resource: function(client: table, input: table): function(): table, table
    items_list_tags_for_resource: function(client: table, input: table): function(): any
    pages_list_trusted_token_issuers: function(client: table, input: table): function(): table, table
    items_list_trusted_token_issuers: function(client: table, input: table): function(): any
end

return M
