-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.ActorTokenContentType = {
    NONE = "NONE",
    M2M = "M2M",
    AWS_IAM_ID_TOKEN_JWT = "AWS_IAM_ID_TOKEN_JWT",
}

M.AgentRuntimeEndpointStatus = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
}

M.ValidationExceptionReason = {
    CANNOT_PARSE = "CannotParse",
    FIELD_VALIDATION_FAILED = "FieldValidationFailed",
    IDEMPOTENT_PARAMETER_MISMATCH_EXCEPTION = "IdempotentParameterMismatchException",
    ROOT_EVENT_IN_OTHER_SESSION = "EventInOtherSession",
    RESOURCE_CONFLICT = "ResourceConflict",
}

M.AgentManagedRuntimeType = {
    PYTHON_3_10 = "PYTHON_3_10",
    PYTHON_3_11 = "PYTHON_3_11",
    PYTHON_3_12 = "PYTHON_3_12",
    PYTHON_3_13 = "PYTHON_3_13",
    PYTHON_3_14 = "PYTHON_3_14",
    NODE_22 = "NODE_22",
}

M.ClaimMatchOperatorType = {
    EQUALS = "EQUALS",
    CONTAINS = "CONTAINS",
    CONTAINS_ANY = "CONTAINS_ANY",
}

M.InboundTokenClaimValueType = {
    STRING = "STRING",
    STRING_ARRAY = "STRING_ARRAY",
}

M.EndpointIpAddressType = {
    IPV4 = "IPV4",
    IPV6 = "IPV6",
}

M.NetworkMode = {
    PUBLIC = "PUBLIC",
    VPC = "VPC",
}

M.ServerProtocol = {
    MCP = "MCP",
    HTTP = "HTTP",
    A2A = "A2A",
    AGUI = "AGUI",
}

M.AgentRuntimeStatus = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
}

M.BrowserProfileStatus = {
    READY = "READY",
    DELETING = "DELETING",
    DELETED = "DELETED",
    SAVING = "SAVING",
}

M.BrowserEnterprisePolicyType = {
    MANAGED = "MANAGED",
    RECOMMENDED = "RECOMMENDED",
}

M.BrowserNetworkMode = {
    PUBLIC = "PUBLIC",
    VPC = "VPC",
}

M.BrowserStatus = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
    DELETED = "DELETED",
}

M.ResourceType = {
    SYSTEM = "SYSTEM",
    CUSTOM = "CUSTOM",
}

M.CodeInterpreterNetworkMode = {
    PUBLIC = "PUBLIC",
    SANDBOX = "SANDBOX",
    VPC = "VPC",
}

M.CodeInterpreterStatus = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
    DELETED = "DELETED",
}

M.ConfigurationBundleStatus = {
    ACTIVE = "ACTIVE",
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
}

M.EvaluatorLevel = {
    TOOL_CALL = "TOOL_CALL",
    TRACE = "TRACE",
    SESSION = "SESSION",
}

M.EvaluatorStatus = {
    ACTIVE = "ACTIVE",
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETING = "DELETING",
}

M.IncludedData = {
    ALL_DATA = "ALL_DATA",
    METADATA_ONLY = "METADATA_ONLY",
}

M.EvaluatorType = {
    BUILTIN = "Builtin",
    CUSTOM = "Custom",
    CODE = "CustomCode",
}

M.AuthorizerType = {
    CUSTOM_JWT = "CUSTOM_JWT",
    AWS_IAM = "AWS_IAM",
    NONE = "NONE",
    AUTHENTICATE_ONLY = "AUTHENTICATE_ONLY",
}

M.ExceptionLevel = {
    DEBUG = "DEBUG",
}

M.GatewayInterceptionPoint = {
    REQUEST = "REQUEST",
    RESPONSE = "RESPONSE",
}

M.GatewayPolicyEngineMode = {
    LOG_ONLY = "LOG_ONLY",
    ENFORCE = "ENFORCE",
}

M.SearchType = {
    SEMANTIC = "SEMANTIC",
}

M.GatewayProtocolType = {
    MCP = "MCP",
}

M.GatewayStatus = {
    CREATING = "CREATING",
    UPDATING = "UPDATING",
    UPDATE_UNSUCCESSFUL = "UPDATE_UNSUCCESSFUL",
    DELETING = "DELETING",
    READY = "READY",
    FAILED = "FAILED",
}

M.PrincipalMatchOperator = {
    StringEquals = "StringEquals",
    StringLike = "StringLike",
}

M.GatewayRuleStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
}

M.ApiKeyCredentialLocation = {
    HEADER = "HEADER",
    QUERY_PARAMETER = "QUERY_PARAMETER",
}

M.OAuthGrantType = {
    CLIENT_CREDENTIALS = "CLIENT_CREDENTIALS",
    AUTHORIZATION_CODE = "AUTHORIZATION_CODE",
    TOKEN_EXCHANGE = "TOKEN_EXCHANGE",
}

M.CredentialProviderType = {
    GATEWAY_IAM_ROLE = "GATEWAY_IAM_ROLE",
    OAUTH = "OAUTH",
    API_KEY = "API_KEY",
    CALLER_IAM_CREDENTIALS = "CALLER_IAM_CREDENTIALS",
    JWT_PASSTHROUGH = "JWT_PASSTHROUGH",
}

M.RestApiMethod = {
    GET = "GET",
    DELETE = "DELETE",
    HEAD = "HEAD",
    OPTIONS = "OPTIONS",
    PATCH = "PATCH",
    PUT = "PUT",
    POST = "POST",
}

M.SchemaType = {
    STRING = "string",
    NUMBER = "number",
    OBJECT = "object",
    ARRAY = "array",
    BOOLEAN = "boolean",
    INTEGER = "integer",
}

M.ListingMode = {
    DEFAULT = "DEFAULT",
    DYNAMIC = "DYNAMIC",
}

M.TargetProtocolType = {
    MCP = "MCP",
    HTTP = "HTTP",
}

M.TargetStatus = {
    CREATING = "CREATING",
    UPDATING = "UPDATING",
    UPDATE_UNSUCCESSFUL = "UPDATE_UNSUCCESSFUL",
    DELETING = "DELETING",
    READY = "READY",
    FAILED = "FAILED",
    SYNCHRONIZING = "SYNCHRONIZING",
    SYNCHRONIZE_UNSUCCESSFUL = "SYNCHRONIZE_UNSUCCESSFUL",
    CREATE_PENDING_AUTH = "CREATE_PENDING_AUTH",
    UPDATE_PENDING_AUTH = "UPDATE_PENDING_AUTH",
    SYNCHRONIZE_PENDING_AUTH = "SYNCHRONIZE_PENDING_AUTH",
}

M.KeyType = {
    CustomerManagedKey = "CustomerManagedKey",
    ServiceManagedKey = "ServiceManagedKey",
}

M.HarnessToolType = {
    REMOTE_MCP = "remote_mcp",
    AGENTCORE_BROWSER = "agentcore_browser",
    AGENTCORE_GATEWAY = "agentcore_gateway",
    INLINE_FUNCTION = "inline_function",
    AGENTCORE_CODE_INTERPRETER = "agentcore_code_interpreter",
}

M.HarnessTruncationStrategy = {
    SLIDING_WINDOW = "sliding_window",
    SUMMARIZATION = "summarization",
    NONE = "none",
}

M.HarnessStatus = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
}

M.MetadataValueType = {
    STRING = "STRING",
    STRINGLIST = "STRINGLIST",
    NUMBER = "NUMBER",
}

M.ContentLevel = {
    METADATA_ONLY = "METADATA_ONLY",
    FULL_CONTENT = "FULL_CONTENT",
}

M.ContentType = {
    MEMORY_RECORDS = "MEMORY_RECORDS",
}

M.MemoryStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
    DELETING = "DELETING",
}

M.OverrideType = {
    SEMANTIC_OVERRIDE = "SEMANTIC_OVERRIDE",
    SUMMARY_OVERRIDE = "SUMMARY_OVERRIDE",
    USER_PREFERENCE_OVERRIDE = "USER_PREFERENCE_OVERRIDE",
    SELF_MANAGED = "SELF_MANAGED",
    EPISODIC_OVERRIDE = "EPISODIC_OVERRIDE",
}

M.MemoryStrategyStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    FAILED = "FAILED",
}

M.MemoryStrategyType = {
    SEMANTIC = "SEMANTIC",
    SUMMARIZATION = "SUMMARIZATION",
    USER_PREFERENCE = "USER_PREFERENCE",
    CUSTOM = "CUSTOM",
    EPISODIC = "EPISODIC",
}

M.MemoryView = {
    FULL = "full",
    WITHOUT_DECRYPTION = "without_decryption",
}

M.CredentialProviderVendorType = {
    GoogleOauth2 = "GoogleOauth2",
    GithubOauth2 = "GithubOauth2",
    SlackOauth2 = "SlackOauth2",
    SalesforceOauth2 = "SalesforceOauth2",
    MicrosoftOauth2 = "MicrosoftOauth2",
    CustomOauth2 = "CustomOauth2",
    AtlassianOauth2 = "AtlassianOauth2",
    LinkedinOauth2 = "LinkedinOauth2",
    XOauth2 = "XOauth2",
    OktaOauth2 = "OktaOauth2",
    OneLoginOauth2 = "OneLoginOauth2",
    PingOneOauth2 = "PingOneOauth2",
    FacebookOauth2 = "FacebookOauth2",
    YandexOauth2 = "YandexOauth2",
    RedditOauth2 = "RedditOauth2",
    ZoomOauth2 = "ZoomOauth2",
    TwitchOauth2 = "TwitchOauth2",
    SpotifyOauth2 = "SpotifyOauth2",
    DropboxOauth2 = "DropboxOauth2",
    NotionOauth2 = "NotionOauth2",
    HubspotOauth2 = "HubspotOauth2",
    CyberArkOauth2 = "CyberArkOauth2",
    FusionAuthOauth2 = "FusionAuthOauth2",
    Auth0Oauth2 = "Auth0Oauth2",
    CognitoOauth2 = "CognitoOauth2",
}

M.ClientAuthenticationMethodType = {
    CLIENT_SECRET_BASIC = "CLIENT_SECRET_BASIC",
    CLIENT_SECRET_POST = "CLIENT_SECRET_POST",
    AWS_IAM_ID_TOKEN_JWT = "AWS_IAM_ID_TOKEN_JWT",
}

M.OnBehalfOfTokenExchangeGrantTypeType = {
    TOKEN_EXCHANGE = "TOKEN_EXCHANGE",
    JWT_AUTHORIZATION_GRANT = "JWT_AUTHORIZATION_GRANT",
}

M.Status = {
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    READY = "READY",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
}

M.FilterOperator = {
    EQUALS = "Equals",
    NOT_EQUALS = "NotEquals",
    GREATER_THAN = "GreaterThan",
    LESS_THAN = "LessThan",
    GREATER_THAN_OR_EQUAL = "GreaterThanOrEqual",
    LESS_THAN_OR_EQUAL = "LessThanOrEqual",
    CONTAINS = "Contains",
    NOT_CONTAINS = "NotContains",
}

M.OnlineEvaluationExecutionStatus = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.OnlineEvaluationConfigStatus = {
    ACTIVE = "ACTIVE",
    CREATING = "CREATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETING = "DELETING",
    ERROR = "ERROR",
}

M.PolicyEngineStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
}

M.PolicyGenerationStatus = {
    GENERATING = "GENERATING",
    GENERATED = "GENERATED",
    GENERATE_FAILED = "GENERATE_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
}

M.FindingType = {
    VALID = "VALID",
    INVALID = "INVALID",
    NOT_TRANSLATABLE = "NOT_TRANSLATABLE",
    ALLOW_ALL = "ALLOW_ALL",
    ALLOW_NONE = "ALLOW_NONE",
    DENY_ALL = "DENY_ALL",
    DENY_NONE = "DENY_NONE",
}

M.PolicyValidationMode = {
    FAIL_ON_ANY_FINDINGS = "FAIL_ON_ANY_FINDINGS",
    IGNORE_ALL_FINDINGS = "IGNORE_ALL_FINDINGS",
}

M.PolicyStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
}

M.DescriptorType = {
    MCP = "MCP",
    A2A = "A2A",
    CUSTOM = "CUSTOM",
    AGENT_SKILLS = "AGENT_SKILLS",
}

M.RegistryRecordOAuthGrantType = {
    CLIENT_CREDENTIALS = "CLIENT_CREDENTIALS",
}

M.RegistryRecordCredentialProviderType = {
    OAUTH = "OAUTH",
    IAM = "IAM",
}

M.SynchronizationType = {
    URL = "URL",
}

M.RegistryRecordStatus = {
    DRAFT = "DRAFT",
    PENDING_APPROVAL = "PENDING_APPROVAL",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    DEPRECATED = "DEPRECATED",
    CREATING = "CREATING",
    UPDATING = "UPDATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.RegistryAuthorizerType = {
    CUSTOM_JWT = "CUSTOM_JWT",
    AWS_IAM = "AWS_IAM",
}

M.RegistryStatus = {
    CREATING = "CREATING",
    READY = "READY",
    UPDATING = "UPDATING",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETING = "DELETING",
    DELETE_FAILED = "DELETE_FAILED",
}

return M
