local M = {}

M.ResourceShareAssociationType = {
    PRINCIPAL = "PRINCIPAL",
    RESOURCE = "RESOURCE",
    SOURCE = "SOURCE",
}

M.ResourceShareAssociationStatus = {
    ASSOCIATING = "ASSOCIATING",
    ASSOCIATED = "ASSOCIATED",
    FAILED = "FAILED",
    DISASSOCIATING = "DISASSOCIATING",
    DISASSOCIATED = "DISASSOCIATED",
    SUSPENDED = "SUSPENDED",
    SUSPENDING = "SUSPENDING",
    RESTORING = "RESTORING",
}

M.ResourceShareInvitationStatus = {
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
    EXPIRED = "EXPIRED",
}

M.PermissionFeatureSet = {
    CREATED_FROM_POLICY = "CREATED_FROM_POLICY",
    PROMOTING_TO_STANDARD = "PROMOTING_TO_STANDARD",
    STANDARD = "STANDARD",
}

M.PermissionType = {
    CUSTOMER_MANAGED = "CUSTOMER_MANAGED",
    AWS_MANAGED = "AWS_MANAGED",
}

M.PermissionStatus = {
    ATTACHABLE = "ATTACHABLE",
    UNATTACHABLE = "UNATTACHABLE",
    DELETING = "DELETING",
    DELETED = "DELETED",
}

M.ResourceShareFeatureSet = {
    CREATED_FROM_POLICY = "CREATED_FROM_POLICY",
    PROMOTING_TO_STANDARD = "PROMOTING_TO_STANDARD",
    STANDARD = "STANDARD",
}

M.ResourceShareStatus = {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
    DELETING = "DELETING",
    DELETED = "DELETED",
}

M.ResourceOwner = {
    SELF = "SELF",
    OTHER_ACCOUNTS = "OTHER-ACCOUNTS",
}

M.ResourceRegionScopeFilter = {
    ALL = "ALL",
    REGIONAL = "REGIONAL",
    GLOBAL = "GLOBAL",
}

M.ResourceRegionScope = {
    REGIONAL = "REGIONAL",
    GLOBAL = "GLOBAL",
}

M.ResourceStatus = {
    AVAILABLE = "AVAILABLE",
    ZONAL_RESOURCE_INACCESSIBLE = "ZONAL_RESOURCE_INACCESSIBLE",
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED",
    UNAVAILABLE = "UNAVAILABLE",
    PENDING = "PENDING",
}

M.PermissionTypeFilter = {
    ALL = "ALL",
    AWS_MANAGED = "AWS_MANAGED",
    CUSTOMER_MANAGED = "CUSTOMER_MANAGED",
}

M.ReplacePermissionAssociationsWorkStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
}

return M
