-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.Operator = {
    EQUAL = "Equal",
    NOT_EQUAL = "NotEqual",
    CONTAINS = "Contains",
}

M.SubscriptionProviderSource = {
    RedHat = "RedHat",
}

M.SubscriptionProviderStatus = {
    ACTIVE = "ACTIVE",
    INVALID = "INVALID",
    PENDING = "PENDING",
}

M.LinuxSubscriptionsDiscovery = {
    Enabled = "Enabled",
    Disabled = "Disabled",
}

M.OrganizationIntegration = {
    Enabled = "Enabled",
    Disabled = "Disabled",
}

M.Status = {
    InProgress = "InProgress",
    Completed = "Completed",
    Successful = "Successful",
    Failed = "Failed",
}

return M
