-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("neptunegraph.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("neptunegraph.schemas")
local sdk_defaults = require("aws.sdk_defaults")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AmazonNeptuneGraph"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(operation)
            local options = {}
            for _, scheme_id in ipairs(operation.effective_auth_schemes) do
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "neptune-graph", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:cancelExportTask(input, options)
    return self:invokeOperation(input, {
        name = "CancelExportTask",
        input_schema = schemas.CancelExportTaskInput,
        output_schema = schemas.CancelExportTaskOutput,
        http_method = "DELETE",
        http_path = "/exporttasks/{taskIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:cancelImportTask(input, options)
    return self:invokeOperation(input, {
        name = "CancelImportTask",
        input_schema = schemas.CancelImportTaskInput,
        output_schema = schemas.CancelImportTaskOutput,
        http_method = "DELETE",
        http_path = "/importtasks/{taskIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:cancelQuery(input, options)
    return self:invokeOperation(input, {
        name = "CancelQuery",
        input_schema = schemas.CancelQueryInput,
        output_schema = schemas.CancelQueryOutput,
        http_method = "DELETE",
        http_path = "/queries/{queryId}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createGraph(input, options)
    return self:invokeOperation(input, {
        name = "CreateGraph",
        input_schema = schemas.CreateGraphInput,
        output_schema = schemas.CreateGraphOutput,
        http_method = "POST",
        http_path = "/graphs",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createGraphSnapshot(input, options)
    return self:invokeOperation(input, {
        name = "CreateGraphSnapshot",
        input_schema = schemas.CreateGraphSnapshotInput,
        output_schema = schemas.CreateGraphSnapshotOutput,
        http_method = "POST",
        http_path = "/snapshots",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createGraphUsingImportTask(input, options)
    return self:invokeOperation(input, {
        name = "CreateGraphUsingImportTask",
        input_schema = schemas.CreateGraphUsingImportTaskInput,
        output_schema = schemas.CreateGraphUsingImportTaskOutput,
        http_method = "POST",
        http_path = "/importtasks",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:createPrivateGraphEndpoint(input, options)
    return self:invokeOperation(input, {
        name = "CreatePrivateGraphEndpoint",
        input_schema = schemas.CreatePrivateGraphEndpointInput,
        output_schema = schemas.CreatePrivateGraphEndpointOutput,
        http_method = "POST",
        http_path = "/graphs/{graphIdentifier}/endpoints/",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deleteGraph(input, options)
    return self:invokeOperation(input, {
        name = "DeleteGraph",
        input_schema = schemas.DeleteGraphInput,
        output_schema = schemas.DeleteGraphOutput,
        http_method = "DELETE",
        http_path = "/graphs/{graphIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deleteGraphSnapshot(input, options)
    return self:invokeOperation(input, {
        name = "DeleteGraphSnapshot",
        input_schema = schemas.DeleteGraphSnapshotInput,
        output_schema = schemas.DeleteGraphSnapshotOutput,
        http_method = "DELETE",
        http_path = "/snapshots/{snapshotIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:deletePrivateGraphEndpoint(input, options)
    return self:invokeOperation(input, {
        name = "DeletePrivateGraphEndpoint",
        input_schema = schemas.DeletePrivateGraphEndpointInput,
        output_schema = schemas.DeletePrivateGraphEndpointOutput,
        http_method = "DELETE",
        http_path = "/graphs/{graphIdentifier}/endpoints/{vpcId}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:executeQuery(input, options)
    return self:invokeOperation(input, {
        name = "ExecuteQuery",
        input_schema = schemas.ExecuteQueryInput,
        output_schema = schemas.ExecuteQueryOutput,
        http_method = "POST",
        http_path = "/queries",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getExportTask(input, options)
    return self:invokeOperation(input, {
        name = "GetExportTask",
        input_schema = schemas.GetExportTaskInput,
        output_schema = schemas.GetExportTaskOutput,
        http_method = "GET",
        http_path = "/exporttasks/{taskIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getGraph(input, options)
    return self:invokeOperation(input, {
        name = "GetGraph",
        input_schema = schemas.GetGraphInput,
        output_schema = schemas.GetGraphOutput,
        http_method = "GET",
        http_path = "/graphs/{graphIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getGraphSnapshot(input, options)
    return self:invokeOperation(input, {
        name = "GetGraphSnapshot",
        input_schema = schemas.GetGraphSnapshotInput,
        output_schema = schemas.GetGraphSnapshotOutput,
        http_method = "GET",
        http_path = "/snapshots/{snapshotIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getGraphSummary(input, options)
    return self:invokeOperation(input, {
        name = "GetGraphSummary",
        input_schema = schemas.GetGraphSummaryInput,
        output_schema = schemas.GetGraphSummaryOutput,
        http_method = "GET",
        http_path = "/summary",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getImportTask(input, options)
    return self:invokeOperation(input, {
        name = "GetImportTask",
        input_schema = schemas.GetImportTaskInput,
        output_schema = schemas.GetImportTaskOutput,
        http_method = "GET",
        http_path = "/importtasks/{taskIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getPrivateGraphEndpoint(input, options)
    return self:invokeOperation(input, {
        name = "GetPrivateGraphEndpoint",
        input_schema = schemas.GetPrivateGraphEndpointInput,
        output_schema = schemas.GetPrivateGraphEndpointOutput,
        http_method = "GET",
        http_path = "/graphs/{graphIdentifier}/endpoints/{vpcId}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:getQuery(input, options)
    return self:invokeOperation(input, {
        name = "GetQuery",
        input_schema = schemas.GetQueryInput,
        output_schema = schemas.GetQueryOutput,
        http_method = "GET",
        http_path = "/queries/{queryId}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listExportTasks(input, options)
    return self:invokeOperation(input, {
        name = "ListExportTasks",
        input_schema = schemas.ListExportTasksInput,
        output_schema = schemas.ListExportTasksOutput,
        http_method = "GET",
        http_path = "/exporttasks",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listGraphs(input, options)
    return self:invokeOperation(input, {
        name = "ListGraphs",
        input_schema = schemas.ListGraphsInput,
        output_schema = schemas.ListGraphsOutput,
        http_method = "GET",
        http_path = "/graphs",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listGraphSnapshots(input, options)
    return self:invokeOperation(input, {
        name = "ListGraphSnapshots",
        input_schema = schemas.ListGraphSnapshotsInput,
        output_schema = schemas.ListGraphSnapshotsOutput,
        http_method = "GET",
        http_path = "/snapshots",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listImportTasks(input, options)
    return self:invokeOperation(input, {
        name = "ListImportTasks",
        input_schema = schemas.ListImportTasksInput,
        output_schema = schemas.ListImportTasksOutput,
        http_method = "GET",
        http_path = "/importtasks",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listPrivateGraphEndpoints(input, options)
    return self:invokeOperation(input, {
        name = "ListPrivateGraphEndpoints",
        input_schema = schemas.ListPrivateGraphEndpointsInput,
        output_schema = schemas.ListPrivateGraphEndpointsOutput,
        http_method = "GET",
        http_path = "/graphs/{graphIdentifier}/endpoints/",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listQueries(input, options)
    return self:invokeOperation(input, {
        name = "ListQueries",
        input_schema = schemas.ListQueriesInput,
        output_schema = schemas.ListQueriesOutput,
        http_method = "GET",
        http_path = "/queries",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(input, {
        name = "ListTagsForResource",
        input_schema = schemas.ListTagsForResourceInput,
        output_schema = schemas.ListTagsForResourceOutput,
        http_method = "GET",
        http_path = "/tags/{resourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:resetGraph(input, options)
    return self:invokeOperation(input, {
        name = "ResetGraph",
        input_schema = schemas.ResetGraphInput,
        output_schema = schemas.ResetGraphOutput,
        http_method = "PUT",
        http_path = "/graphs/{graphIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:restoreGraphFromSnapshot(input, options)
    return self:invokeOperation(input, {
        name = "RestoreGraphFromSnapshot",
        input_schema = schemas.RestoreGraphFromSnapshotInput,
        output_schema = schemas.RestoreGraphFromSnapshotOutput,
        http_method = "POST",
        http_path = "/snapshots/{snapshotIdentifier}/restore",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:startExportTask(input, options)
    return self:invokeOperation(input, {
        name = "StartExportTask",
        input_schema = schemas.StartExportTaskInput,
        output_schema = schemas.StartExportTaskOutput,
        http_method = "POST",
        http_path = "/exporttasks",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:startGraph(input, options)
    return self:invokeOperation(input, {
        name = "StartGraph",
        input_schema = schemas.StartGraphInput,
        output_schema = schemas.StartGraphOutput,
        http_method = "POST",
        http_path = "/graphs/{graphIdentifier}/start",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:startImportTask(input, options)
    return self:invokeOperation(input, {
        name = "StartImportTask",
        input_schema = schemas.StartImportTaskInput,
        output_schema = schemas.StartImportTaskOutput,
        http_method = "POST",
        http_path = "/graphs/{graphIdentifier}/importtasks",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:stopGraph(input, options)
    return self:invokeOperation(input, {
        name = "StopGraph",
        input_schema = schemas.StopGraphInput,
        output_schema = schemas.StopGraphOutput,
        http_method = "POST",
        http_path = "/graphs/{graphIdentifier}/stop",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(input, {
        name = "TagResource",
        input_schema = schemas.TagResourceInput,
        output_schema = schemas.TagResourceOutput,
        http_method = "POST",
        http_path = "/tags/{resourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(input, {
        name = "UntagResource",
        input_schema = schemas.UntagResourceInput,
        output_schema = schemas.UntagResourceOutput,
        http_method = "DELETE",
        http_path = "/tags/{resourceArn}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

function Client:updateGraph(input, options)
    return self:invokeOperation(input, {
        name = "UpdateGraph",
        input_schema = schemas.UpdateGraphInput,
        output_schema = schemas.UpdateGraphOutput,
        http_method = "PATCH",
        http_path = "/graphs/{graphIdentifier}",
        effective_auth_schemes = {
            "aws.auth#sigv4",
        },
    }, options)
end

return M
