local M = {}

M.NodeDataType = {
    INT8 = "INT8",
    UINT8 = "UINT8",
    INT16 = "INT16",
    UINT16 = "UINT16",
    INT32 = "INT32",
    UINT32 = "UINT32",
    INT64 = "INT64",
    UINT64 = "UINT64",
    BOOLEAN = "BOOLEAN",
    FLOAT = "FLOAT",
    DOUBLE = "DOUBLE",
    STRING = "STRING",
    UNIX_TIMESTAMP = "UNIX_TIMESTAMP",
    INT8_ARRAY = "INT8_ARRAY",
    UINT8_ARRAY = "UINT8_ARRAY",
    INT16_ARRAY = "INT16_ARRAY",
    UINT16_ARRAY = "UINT16_ARRAY",
    INT32_ARRAY = "INT32_ARRAY",
    UINT32_ARRAY = "UINT32_ARRAY",
    INT64_ARRAY = "INT64_ARRAY",
    UINT64_ARRAY = "UINT64_ARRAY",
    BOOLEAN_ARRAY = "BOOLEAN_ARRAY",
    FLOAT_ARRAY = "FLOAT_ARRAY",
    DOUBLE_ARRAY = "DOUBLE_ARRAY",
    STRING_ARRAY = "STRING_ARRAY",
    UNIX_TIMESTAMP_ARRAY = "UNIX_TIMESTAMP_ARRAY",
    UNKNOWN = "UNKNOWN",
    STRUCT = "STRUCT",
    STRUCT_ARRAY = "STRUCT_ARRAY",
}

M.ValidationExceptionReason = {
    UNKNOWN_OPERATION = "unknownOperation",
    CANNOT_PARSE = "cannotParse",
    FIELD_VALIDATION_FAILED = "fieldValidationFailed",
    OTHER = "other",
}

M.VehicleAssociationBehavior = {
    CREATE_IOT_THING = "CreateIotThing",
    VALIDATE_IOT_THING_EXISTS = "ValidateIotThingExists",
}

M.TimeUnit = {
    MILLISECOND = "MILLISECOND",
    SECOND = "SECOND",
    MINUTE = "MINUTE",
    HOUR = "HOUR",
}

M.UpdateMode = {
    OVERWRITE = "Overwrite",
    MERGE = "Merge",
}

M.TriggerMode = {
    ALWAYS = "ALWAYS",
    RISING_EDGE = "RISING_EDGE",
}

M.Compression = {
    OFF = "OFF",
    SNAPPY = "SNAPPY",
}

M.DataFormat = {
    JSON = "JSON",
    PARQUET = "PARQUET",
}

M.StorageCompressionFormat = {
    NONE = "NONE",
    GZIP = "GZIP",
}

M.StorageMaximumSizeUnit = {
    MB = "MB",
    GB = "GB",
    TB = "TB",
}

M.StorageMinimumTimeToLiveUnit = {
    HOURS = "HOURS",
    DAYS = "DAYS",
    WEEKS = "WEEKS",
}

M.DiagnosticsMode = {
    OFF = "OFF",
    SEND_ACTIVE_DTCS = "SEND_ACTIVE_DTCS",
}

M.SpoolingMode = {
    OFF = "OFF",
    TO_DISK = "TO_DISK",
}

M.CampaignStatus = {
    CREATING = "CREATING",
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL",
    RUNNING = "RUNNING",
    SUSPENDED = "SUSPENDED",
}

M.ListResponseScope = {
    METADATA_ONLY = "METADATA_ONLY",
}

M.UpdateCampaignAction = {
    APPROVE = "APPROVE",
    SUSPEND = "SUSPEND",
    RESUME = "RESUME",
    UPDATE = "UPDATE",
}

M.SignalValueType = {
    INTEGER = "INTEGER",
    FLOATING_POINT = "FLOATING_POINT",
}

M.LogType = {
    OFF = "OFF",
    ERROR = "ERROR",
}

M.DefaultForUnmappedSignalsType = {
    CUSTOM_DECODING = "CUSTOM_DECODING",
}

M.NetworkInterfaceType = {
    CAN_INTERFACE = "CAN_INTERFACE",
    OBD_INTERFACE = "OBD_INTERFACE",
    VEHICLE_MIDDLEWARE = "VEHICLE_MIDDLEWARE",
    CUSTOM_DECODING_INTERFACE = "CUSTOM_DECODING_INTERFACE",
}

M.VehicleMiddlewareProtocol = {
    ROS_2 = "ROS_2",
}

M.ROS2PrimitiveType = {
    BOOL = "BOOL",
    BYTE = "BYTE",
    CHAR = "CHAR",
    FLOAT32 = "FLOAT32",
    FLOAT64 = "FLOAT64",
    INT8 = "INT8",
    UINT8 = "UINT8",
    INT16 = "INT16",
    UINT16 = "UINT16",
    INT32 = "INT32",
    UINT32 = "UINT32",
    INT64 = "INT64",
    UINT64 = "UINT64",
    STRING = "STRING",
    WSTRING = "WSTRING",
}

M.StructuredMessageListType = {
    FIXED_CAPACITY = "FIXED_CAPACITY",
    DYNAMIC_UNBOUNDED_CAPACITY = "DYNAMIC_UNBOUNDED_CAPACITY",
    DYNAMIC_BOUNDED_CAPACITY = "DYNAMIC_BOUNDED_CAPACITY",
}

M.SignalDecoderType = {
    CAN_SIGNAL = "CAN_SIGNAL",
    OBD_SIGNAL = "OBD_SIGNAL",
    MESSAGE_SIGNAL = "MESSAGE_SIGNAL",
    CUSTOM_DECODING_SIGNAL = "CUSTOM_DECODING_SIGNAL",
}

M.NetworkInterfaceFailureReason = {
    DUPLICATE_INTERFACE = "DUPLICATE_NETWORK_INTERFACE",
    CONFLICTING_NETWORK_INTERFACE = "CONFLICTING_NETWORK_INTERFACE",
    NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS = "NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS",
    CAN_NETWORK_INTERFACE_INFO_IS_NULL = "CAN_NETWORK_INTERFACE_INFO_IS_NULL",
    OBD_NETWORK_INTERFACE_INFO_IS_NULL = "OBD_NETWORK_INTERFACE_INFO_IS_NULL",
    NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS = "NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS",
    VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL = "VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL",
    CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL = "CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL",
}

M.SignalDecoderFailureReason = {
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL",
    CONFLICTING_SIGNAL = "CONFLICTING_SIGNAL",
    SIGNAL_TO_ADD_ALREADY_EXISTS = "SIGNAL_TO_ADD_ALREADY_EXISTS",
    SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE = "SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE",
    NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE = "NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE",
    SIGNAL_NOT_IN_MODEL = "SIGNAL_NOT_IN_MODEL",
    CAN_SIGNAL_INFO_IS_NULL = "CAN_SIGNAL_INFO_IS_NULL",
    OBD_SIGNAL_INFO_IS_NULL = "OBD_SIGNAL_INFO_IS_NULL",
    NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL = "NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL",
    MESSAGE_SIGNAL_INFO_IS_NULL = "MESSAGE_SIGNAL_INFO_IS_NULL",
    SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE = "SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE",
    STRUCT_SIZE_MISMATCH = "STRUCT_SIZE_MISMATCH",
    NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL = "NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL",
    SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG = "SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG",
    EMPTY_MESSAGE_SIGNAL = "EMPTY_MESSAGE_SIGNAL",
    CUSTOM_DECODING_SIGNAL_INFO_IS_NULL = "CUSTOM_DECODING_SIGNAL_INFO_IS_NULL",
}

M.NodeDataEncoding = {
    BINARY = "BINARY",
    TYPED = "TYPED",
}

M.ManifestStatus = {
    ACTIVE = "ACTIVE",
    DRAFT = "DRAFT",
    INVALID = "INVALID",
    VALIDATING = "VALIDATING",
}

M.EncryptionStatus = {
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILURE = "FAILURE",
}

M.EncryptionType = {
    KMS_BASED_ENCRYPTION = "KMS_BASED_ENCRYPTION",
    FLEETWISE_DEFAULT_ENCRYPTION = "FLEETWISE_DEFAULT_ENCRYPTION",
}

M.RegistrationStatus = {
    REGISTRATION_PENDING = "REGISTRATION_PENDING",
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",
    REGISTRATION_FAILURE = "REGISTRATION_FAILURE",
}

M.VehicleState = {
    CREATED = "CREATED",
    READY = "READY",
    HEALTHY = "HEALTHY",
    SUSPENDED = "SUSPENDED",
    DELETING = "DELETING",
    READY_FOR_CHECKIN = "READY_FOR_CHECKIN",
}

M.SignalNodeType = {
    SENSOR = "SENSOR",
    ACTUATOR = "ACTUATOR",
    ATTRIBUTE = "ATTRIBUTE",
    BRANCH = "BRANCH",
    CUSTOM_STRUCT = "CUSTOM_STRUCT",
    CUSTOM_PROPERTY = "CUSTOM_PROPERTY",
}

return M
