-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.Format = {
    CSV = "CSV",
    PARQUET = "PARQUET",
}

M.ReportFrequency = {
    MONTHLY = "MONTHLY",
    DAILY = "DAILY",
    ALL = "ALL",
}

M.S3BucketRegion = {
    AP_EAST_1 = "ap-east-1",
    ME_SOUTH_1 = "me-south-1",
    EU_SOUTH_1 = "eu-south-1",
    AF_SOUTH_1 = "af-south-1",
}

return M
