local record M
    pages_list_bill_estimate_commitments: function(client: table, input: table): function(): table, table
    items_list_bill_estimate_commitments: function(client: table, input: table): function(): any
    pages_list_bill_estimate_input_commitment_modifications: function(client: table, input: table): function(): table, table
    items_list_bill_estimate_input_commitment_modifications: function(client: table, input: table): function(): any
    pages_list_bill_estimate_input_usage_modifications: function(client: table, input: table): function(): table, table
    items_list_bill_estimate_input_usage_modifications: function(client: table, input: table): function(): any
    pages_list_bill_estimate_line_items: function(client: table, input: table): function(): table, table
    items_list_bill_estimate_line_items: function(client: table, input: table): function(): any
    pages_list_bill_estimates: function(client: table, input: table): function(): table, table
    items_list_bill_estimates: function(client: table, input: table): function(): any
    pages_list_bill_scenario_commitment_modifications: function(client: table, input: table): function(): table, table
    items_list_bill_scenario_commitment_modifications: function(client: table, input: table): function(): any
    pages_list_bill_scenario_usage_modifications: function(client: table, input: table): function(): table, table
    items_list_bill_scenario_usage_modifications: function(client: table, input: table): function(): any
    pages_list_bill_scenarios: function(client: table, input: table): function(): table, table
    items_list_bill_scenarios: function(client: table, input: table): function(): any
    pages_list_workload_estimate_usage: function(client: table, input: table): function(): table, table
    items_list_workload_estimate_usage: function(client: table, input: table): function(): any
    pages_list_workload_estimates: function(client: table, input: table): function(): table, table
    items_list_workload_estimates: function(client: table, input: table): function(): any
end

return M
