local M = {}

M.CurrencyCode = {
    USD = "USD",
}

M.PurchaseAgreementType = {
    SAVINGS_PLANS = "SAVINGS_PLANS",
    RESERVED_INSTANCE = "RESERVED_INSTANCE",
}

M.ValidationExceptionReason = {
    UNKNOWN_OPERATION = "unknownOperation",
    CANNOT_PARSE = "cannotParse",
    FIELD_VALIDATION_FAILED = "fieldValidationFailed",
    INVALID_REQUEST_FROM_MEMBER = "invalidRequestFromMember",
    DISALLOWED_RATE = "disallowedRate",
    OTHER = "other",
}

M.MatchOption = {
    EQUALS = "EQUALS",
    STARTS_WITH = "STARTS_WITH",
    CONTAINS = "CONTAINS",
}

M.ListUsageFilterName = {
    USAGE_ACCOUNT_ID = "USAGE_ACCOUNT_ID",
    SERVICE_CODE = "SERVICE_CODE",
    USAGE_TYPE = "USAGE_TYPE",
    OPERATION = "OPERATION",
    LOCATION = "LOCATION",
    USAGE_GROUP = "USAGE_GROUP",
    HISTORICAL_USAGE_ACCOUNT_ID = "HISTORICAL_USAGE_ACCOUNT_ID",
    HISTORICAL_SERVICE_CODE = "HISTORICAL_SERVICE_CODE",
    HISTORICAL_USAGE_TYPE = "HISTORICAL_USAGE_TYPE",
    HISTORICAL_OPERATION = "HISTORICAL_OPERATION",
    HISTORICAL_LOCATION = "HISTORICAL_LOCATION",
}

M.ListBillEstimateLineItemsFilterName = {
    USAGE_ACCOUNT_ID = "USAGE_ACCOUNT_ID",
    SERVICE_CODE = "SERVICE_CODE",
    USAGE_TYPE = "USAGE_TYPE",
    OPERATION = "OPERATION",
    LOCATION = "LOCATION",
    LINE_ITEM_TYPE = "LINE_ITEM_TYPE",
}

M.BillEstimateStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETE = "COMPLETE",
    FAILED = "FAILED",
}

M.GroupSharingPreferenceEnum = {
    OPEN = "OPEN",
    PRIORITIZED = "PRIORITIZED",
    RESTRICTED = "RESTRICTED",
}

M.ListBillEstimatesFilterName = {
    STATUS = "STATUS",
    NAME = "NAME",
}

M.BatchCreateBillScenarioCommitmentModificationErrorCode = {
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    INVALID_ACCOUNT = "INVALID_ACCOUNT",
}

M.BatchDeleteBillScenarioCommitmentModificationErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.BatchUpdateBillScenarioCommitmentModificationErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.BillScenarioStatus = {
    READY = "READY",
    LOCKED = "LOCKED",
    FAILED = "FAILED",
    STALE = "STALE",
}

M.BatchCreateBillScenarioUsageModificationErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.BatchDeleteBillScenarioUsageModificationErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.BatchUpdateBillScenarioUsageModificationErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.ListBillScenariosFilterName = {
    STATUS = "STATUS",
    NAME = "NAME",
    GROUP_SHARING_PREFERENCE = "GROUP_SHARING_PREFERENCE",
    COST_CATEGORY_ARN = "COST_CATEGORY_ARN",
}

M.RateType = {
    BEFORE_DISCOUNTS = "BEFORE_DISCOUNTS",
    AFTER_DISCOUNTS = "AFTER_DISCOUNTS",
    AFTER_DISCOUNTS_AND_COMMITMENTS = "AFTER_DISCOUNTS_AND_COMMITMENTS",
}

M.WorkloadEstimateRateType = {
    BEFORE_DISCOUNTS = "BEFORE_DISCOUNTS",
    AFTER_DISCOUNTS = "AFTER_DISCOUNTS",
    AFTER_DISCOUNTS_AND_COMMITMENTS = "AFTER_DISCOUNTS_AND_COMMITMENTS",
}

M.WorkloadEstimateStatus = {
    UPDATING = "UPDATING",
    VALID = "VALID",
    INVALID = "INVALID",
    ACTION_NEEDED = "ACTION_NEEDED",
}

M.ListWorkloadEstimatesFilterName = {
    STATUS = "STATUS",
    NAME = "NAME",
}

M.BatchCreateWorkloadEstimateUsageCode = {
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

M.WorkloadEstimateCostStatus = {
    VALID = "VALID",
    INVALID = "INVALID",
    STALE = "STALE",
}

M.WorkloadEstimateUpdateUsageErrorCode = {
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

return M
