local M = {}

M.ActionType = {
    ADDED_PROFILE_KEY = "ADDED_PROFILE_KEY",
    DELETED_PROFILE_KEY = "DELETED_PROFILE_KEY",
    CREATED = "CREATED",
    UPDATED = "UPDATED",
    INGESTED = "INGESTED",
    DELETED_BY_CUSTOMER = "DELETED_BY_CUSTOMER",
    EXPIRED = "EXPIRED",
    MERGED = "MERGED",
    DELETED_BY_MERGE = "DELETED_BY_MERGE",
}

M.StringDimensionType = {
    INCLUSIVE = "INCLUSIVE",
    EXCLUSIVE = "EXCLUSIVE",
    CONTAINS = "CONTAINS",
    BEGINS_WITH = "BEGINS_WITH",
    ENDS_WITH = "ENDS_WITH",
}

M.SourceConnectorType = {
    SALESFORCE = "Salesforce",
    MARKETO = "Marketo",
    ZENDESK = "Zendesk",
    SERVICENOW = "Servicenow",
    S3 = "S3",
}

M.MarketoConnectorOperator = {
    PROJECTION = "PROJECTION",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN = "GREATER_THAN",
    BETWEEN = "BETWEEN",
    ADDITION = "ADDITION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    SUBTRACTION = "SUBTRACTION",
    MASK_ALL = "MASK_ALL",
    MASK_FIRST_N = "MASK_FIRST_N",
    MASK_LAST_N = "MASK_LAST_N",
    VALIDATE_NON_NULL = "VALIDATE_NON_NULL",
    VALIDATE_NON_ZERO = "VALIDATE_NON_ZERO",
    VALIDATE_NON_NEGATIVE = "VALIDATE_NON_NEGATIVE",
    VALIDATE_NUMERIC = "VALIDATE_NUMERIC",
    NO_OP = "NO_OP",
}

M.S3ConnectorOperator = {
    PROJECTION = "PROJECTION",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN = "GREATER_THAN",
    BETWEEN = "BETWEEN",
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO",
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO",
    EQUAL_TO = "EQUAL_TO",
    NOT_EQUAL_TO = "NOT_EQUAL_TO",
    ADDITION = "ADDITION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    SUBTRACTION = "SUBTRACTION",
    MASK_ALL = "MASK_ALL",
    MASK_FIRST_N = "MASK_FIRST_N",
    MASK_LAST_N = "MASK_LAST_N",
    VALIDATE_NON_NULL = "VALIDATE_NON_NULL",
    VALIDATE_NON_ZERO = "VALIDATE_NON_ZERO",
    VALIDATE_NON_NEGATIVE = "VALIDATE_NON_NEGATIVE",
    VALIDATE_NUMERIC = "VALIDATE_NUMERIC",
    NO_OP = "NO_OP",
}

M.SalesforceConnectorOperator = {
    PROJECTION = "PROJECTION",
    LESS_THAN = "LESS_THAN",
    CONTAINS = "CONTAINS",
    GREATER_THAN = "GREATER_THAN",
    BETWEEN = "BETWEEN",
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO",
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO",
    EQUAL_TO = "EQUAL_TO",
    NOT_EQUAL_TO = "NOT_EQUAL_TO",
    ADDITION = "ADDITION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    SUBTRACTION = "SUBTRACTION",
    MASK_ALL = "MASK_ALL",
    MASK_FIRST_N = "MASK_FIRST_N",
    MASK_LAST_N = "MASK_LAST_N",
    VALIDATE_NON_NULL = "VALIDATE_NON_NULL",
    VALIDATE_NON_ZERO = "VALIDATE_NON_ZERO",
    VALIDATE_NON_NEGATIVE = "VALIDATE_NON_NEGATIVE",
    VALIDATE_NUMERIC = "VALIDATE_NUMERIC",
    NO_OP = "NO_OP",
}

M.ServiceNowConnectorOperator = {
    PROJECTION = "PROJECTION",
    CONTAINS = "CONTAINS",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN = "GREATER_THAN",
    BETWEEN = "BETWEEN",
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO",
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO",
    EQUAL_TO = "EQUAL_TO",
    NOT_EQUAL_TO = "NOT_EQUAL_TO",
    ADDITION = "ADDITION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    SUBTRACTION = "SUBTRACTION",
    MASK_ALL = "MASK_ALL",
    MASK_FIRST_N = "MASK_FIRST_N",
    MASK_LAST_N = "MASK_LAST_N",
    VALIDATE_NON_NULL = "VALIDATE_NON_NULL",
    VALIDATE_NON_ZERO = "VALIDATE_NON_ZERO",
    VALIDATE_NON_NEGATIVE = "VALIDATE_NON_NEGATIVE",
    VALIDATE_NUMERIC = "VALIDATE_NUMERIC",
    NO_OP = "NO_OP",
}

M.ZendeskConnectorOperator = {
    PROJECTION = "PROJECTION",
    GREATER_THAN = "GREATER_THAN",
    ADDITION = "ADDITION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    SUBTRACTION = "SUBTRACTION",
    MASK_ALL = "MASK_ALL",
    MASK_FIRST_N = "MASK_FIRST_N",
    MASK_LAST_N = "MASK_LAST_N",
    VALIDATE_NON_NULL = "VALIDATE_NON_NULL",
    VALIDATE_NON_ZERO = "VALIDATE_NON_ZERO",
    VALIDATE_NON_NEGATIVE = "VALIDATE_NON_NEGATIVE",
    VALIDATE_NUMERIC = "VALIDATE_NUMERIC",
    NO_OP = "NO_OP",
}

M.OperatorPropertiesKeys = {
    VALUE = "VALUE",
    VALUES = "VALUES",
    DATA_TYPE = "DATA_TYPE",
    UPPER_BOUND = "UPPER_BOUND",
    LOWER_BOUND = "LOWER_BOUND",
    SOURCE_DATA_TYPE = "SOURCE_DATA_TYPE",
    DESTINATION_DATA_TYPE = "DESTINATION_DATA_TYPE",
    VALIDATION_ACTION = "VALIDATION_ACTION",
    MASK_VALUE = "MASK_VALUE",
    MASK_LENGTH = "MASK_LENGTH",
    TRUNCATE_LENGTH = "TRUNCATE_LENGTH",
    MATH_OPERATION_FIELDS_ORDER = "MATH_OPERATION_FIELDS_ORDER",
    CONCAT_FORMAT = "CONCAT_FORMAT",
    SUBFIELD_CATEGORY_MAP = "SUBFIELD_CATEGORY_MAP",
}

M.TaskType = {
    ARITHMETIC = "Arithmetic",
    FILTER = "Filter",
    MAP = "Map",
    MASK = "Mask",
    MERGE = "Merge",
    TRUNCATE = "Truncate",
    VALIDATE = "Validate",
}

M.DataPullMode = {
    INCREMENTAL = "Incremental",
    COMPLETE = "Complete",
}

M.TriggerType = {
    SCHEDULED = "Scheduled",
    EVENT = "Event",
    ONDEMAND = "OnDemand",
}

M.Status = {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETE = "COMPLETE",
    FAILED = "FAILED",
    SPLIT = "SPLIT",
    RETRY = "RETRY",
    CANCELLED = "CANCELLED",
}

M.AttributeDimensionType = {
    INCLUSIVE = "INCLUSIVE",
    EXCLUSIVE = "EXCLUSIVE",
    CONTAINS = "CONTAINS",
    BEGINS_WITH = "BEGINS_WITH",
    ENDS_WITH = "ENDS_WITH",
    BEFORE = "BEFORE",
    AFTER = "AFTER",
    BETWEEN = "BETWEEN",
    NOT_BETWEEN = "NOT_BETWEEN",
    ON = "ON",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
    EQUAL = "EQUAL",
}

M.FilterDimensionType = {
    INCLUSIVE = "INCLUSIVE",
    EXCLUSIVE = "EXCLUSIVE",
    CONTAINS = "CONTAINS",
    BEGINS_WITH = "BEGINS_WITH",
    ENDS_WITH = "ENDS_WITH",
    BEFORE = "BEFORE",
    AFTER = "AFTER",
    BETWEEN = "BETWEEN",
    NOT_BETWEEN = "NOT_BETWEEN",
    ON = "ON",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
    EQUAL = "EQUAL",
}

M.AttributeMatchingModel = {
    ONE_TO_ONE = "ONE_TO_ONE",
    MANY_TO_MANY = "MANY_TO_MANY",
}

M.ConflictResolvingModel = {
    RECENCY = "RECENCY",
    SOURCE = "SOURCE",
}

M.RangeUnit = {
    DAYS = "DAYS",
}

M.ContactType = {
    PHONE_NUMBER = "PhoneNumber",
    MOBILE_PHONE_NUMBER = "MobilePhoneNumber",
    HOME_PHONE_NUMBER = "HomePhoneNumber",
    BUSINESS_PHONE_NUMBER = "BusinessPhoneNumber",
    EMAIL_ADDRESS = "EmailAddress",
    PERSONAL_EMAIL_ADDRESS = "PersonalEmailAddress",
    BUSINESS_EMAIL_ADDRESS = "BusinessEmailAddress",
}

M.Gender = {
    MALE = "MALE",
    FEMALE = "FEMALE",
    UNSPECIFIED = "UNSPECIFIED",
}

M.PartyType = {
    INDIVIDUAL = "INDIVIDUAL",
    BUSINESS = "BUSINESS",
    OTHER = "OTHER",
}

M.ProfileType = {
    ACCOUNT_PROFILE = "ACCOUNT_PROFILE",
    PROFILE = "PROFILE",
}

M.ReadinessStatus = {
    PREPARING = "PREPARING",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
}

M.ComparisonOperator = {
    INCLUSIVE = "INCLUSIVE",
    EXCLUSIVE = "EXCLUSIVE",
    CONTAINS = "CONTAINS",
    BEGINS_WITH = "BEGINS_WITH",
    ENDS_WITH = "ENDS_WITH",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
    EQUAL = "EQUAL",
    BEFORE = "BEFORE",
    AFTER = "AFTER",
    ON = "ON",
    BETWEEN = "BETWEEN",
    NOT_BETWEEN = "NOT_BETWEEN",
}

M.Unit = {
    DAYS = "DAYS",
}

M.Operator = {
    EQUAL_TO = "EQUAL_TO",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    NOT_EQUAL_TO = "NOT_EQUAL_TO",
}

M.ContentType = {
    STRING = "STRING",
    NUMBER = "NUMBER",
}

M.Type = {
    ALL = "ALL",
    ANY = "ANY",
    NONE = "NONE",
}

M.Include = {
    ALL = "ALL",
    ANY = "ANY",
    NONE = "NONE",
}

M.Statistic = {
    FIRST_OCCURRENCE = "FIRST_OCCURRENCE",
    LAST_OCCURRENCE = "LAST_OCCURRENCE",
    COUNT = "COUNT",
    SUM = "SUM",
    MINIMUM = "MINIMUM",
    MAXIMUM = "MAXIMUM",
    AVERAGE = "AVERAGE",
    MAX_OCCURRENCE = "MAX_OCCURRENCE",
}

M.JobScheduleDayOfTheWeek = {
    SUNDAY = "SUNDAY",
    MONDAY = "MONDAY",
    TUESDAY = "TUESDAY",
    WEDNESDAY = "WEDNESDAY",
    THURSDAY = "THURSDAY",
    FRIDAY = "FRIDAY",
    SATURDAY = "SATURDAY",
}

M.RuleBasedMatchingStatus = {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    ACTIVE = "ACTIVE",
}

M.LayoutType = {
    PROFILE_EXPLORER = "PROFILE_EXPLORER",
}

M.EventTriggerLogicalOperator = {
    ANY = "ANY",
    ALL = "ALL",
    NONE = "NONE",
}

M.PeriodUnit = {
    HOURS = "HOURS",
    DAYS = "DAYS",
    WEEKS = "WEEKS",
    MONTHS = "MONTHS",
}

M.WorkflowType = {
    APPFLOW_INTEGRATION = "APPFLOW_INTEGRATION",
}

M.RecommenderRecipeName = {
    RECOMMENDED_FOR_YOU = "recommended-for-you",
    SIMILAR_ITEMS = "similar-items",
    FREQUENTLY_PAIRED_ITEMS = "frequently-paired-items",
    POPULAR_ITEMS = "popular-items",
    TRENDING_NOW = "trending-now",
    PERSONALIZED_RANKING = "personalized-ranking",
}

M.FeatureType = {
    TEXTUAL = "TEXTUAL",
    CATEGORICAL = "CATEGORICAL",
}

M.RecommenderSchemaStatus = {
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
}

M.DateDimensionType = {
    BEFORE = "BEFORE",
    AFTER = "AFTER",
    BETWEEN = "BETWEEN",
    NOT_BETWEEN = "NOT_BETWEEN",
    ON = "ON",
}

M.ProfileTypeDimensionType = {
    INCLUSIVE = "INCLUSIVE",
    EXCLUSIVE = "EXCLUSIVE",
}

M.IncludeOptions = {
    ALL = "ALL",
    ANY = "ANY",
    NONE = "NONE",
}

M.SegmentSortDataType = {
    STRING = "STRING",
    NUMBER = "NUMBER",
    DATE = "DATE",
}

M.SegmentSortOrder = {
    ASC = "ASC",
    DESC = "DESC",
}

M.SortAttributeType = {
    PROFILE = "PROFILE",
    CALCULATED = "CALCULATED",
}

M.DataFormat = {
    CSV = "CSV",
    JSONL = "JSONL",
    ORC = "ORC",
}

M.FieldContentType = {
    STRING = "STRING",
    NUMBER = "NUMBER",
    PHONE_NUMBER = "PHONE_NUMBER",
    EMAIL_ADDRESS = "EMAIL_ADDRESS",
    NAME = "NAME",
}

M.StandardIdentifier = {
    PROFILE = "PROFILE",
    ASSET = "ASSET",
    CASE = "CASE",
    DEVICE = "DEVICE",
    WEB_ANALYTICS = "WEB_ANALYTICS",
    ORDER = "ORDER",
    COMMUNICATION_RECORD = "COMMUNICATION_RECORD",
    AIR_PREFERENCE = "AIR_PREFERENCE",
    HOTEL_PREFERENCE = "HOTEL_PREFERENCE",
    AIR_BOOKING = "AIR_BOOKING",
    AIR_SEGMENT = "AIR_SEGMENT",
    HOTEL_RESERVATION = "HOTEL_RESERVATION",
    HOTEL_STAY_REVENUE = "HOTEL_STAY_REVENUE",
    LOYALTY = "LOYALTY",
    LOYALTY_TRANSACTION = "LOYALTY_TRANSACTION",
    LOYALTY_PROMOTION = "LOYALTY_PROMOTION",
    UNIQUE = "UNIQUE",
    SECONDARY = "SECONDARY",
    LOOKUP_ONLY = "LOOKUP_ONLY",
    NEW_ONLY = "NEW_ONLY",
}

M.EventStreamDestinationStatus = {
    HEALTHY = "HEALTHY",
    UNHEALTHY = "UNHEALTHY",
}

M.EventStreamState = {
    RUNNING = "RUNNING",
    STOPPED = "STOPPED",
}

M.IdentityResolutionJobStatus = {
    PENDING = "PENDING",
    PREPROCESSING = "PREPROCESSING",
    FIND_MATCHING = "FIND_MATCHING",
    MERGING = "MERGING",
    COMPLETED = "COMPLETED",
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS",
    FAILED = "FAILED",
}

M.Scope = {
    PROFILE = "PROFILE",
    DOMAIN = "DOMAIN",
}

M.RecommenderStatus = {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
    STOPPING = "STOPPING",
    INACTIVE = "INACTIVE",
    STARTING = "STARTING",
    DELETING = "DELETING",
}

M.TrainingMetricName = {
    HIT = "hit",
    COVERAGE = "coverage",
    RECALL = "recall",
    POPULARITY = "popularity",
    FRESHNESS = "freshness",
    SIMILARITY = "similarity",
    MEAN_RECIPROCAL_RANK_AT_25 = "mean_reciprocal_rank_at_25",
    NORMALIZED_DISCOUNTED_CUMULATIVE_GAIN_AT_5 = "normalized_discounted_cumulative_gain_at_5",
    NORMALIZED_DISCOUNTED_CUMULATIVE_GAIN_AT_10 = "normalized_discounted_cumulative_gain_at_10",
    NORMALIZED_DISCOUNTED_CUMULATIVE_GAIN_AT_25 = "normalized_discounted_cumulative_gain_at_25",
    PRECISION_AT_5 = "precision_at_5",
    PRECISION_AT_10 = "precision_at_10",
    PRECISION_AT_25 = "precision_at_25",
}

M.RecommenderFilterStatus = {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    FAILED = "FAILED",
    DELETING = "DELETING",
}

M.SegmentType = {
    CLASSIC = "CLASSIC",
    ENHANCED = "ENHANCED",
}

M.EstimateStatus = {
    RUNNING = "RUNNING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
}

M.QueryResult = {
    PRESENT = "PRESENT",
    ABSENT = "ABSENT",
}

M.SegmentSnapshotStatus = {
    COMPLETED = "COMPLETED",
    IN_PROGRESS = "IN_PROGRESS",
    FAILED = "FAILED",
}

M.MatchType = {
    RULE_BASED_MATCHING = "RULE_BASED_MATCHING",
    ML_BASED_MATCHING = "ML_BASED_MATCHING",
}

M.UploadJobStatus = {
    CREATED = "CREATED",
    IN_PROGRESS = "IN_PROGRESS",
    PARTIALLY_SUCCEEDED = "PARTIALLY_SUCCEEDED",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    STOPPED = "STOPPED",
}

M.StatusReason = {
    VALIDATION_FAILURE = "VALIDATION_FAILURE",
    INTERNAL_FAILURE = "INTERNAL_FAILURE",
}

M.logicalOperator = {
    AND = "AND",
    OR = "OR",
}

return M
