-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.QueryNetwork = {
    ETHEREUM_MAINNET = "ETHEREUM_MAINNET",
    ETHEREUM_SEPOLIA_TESTNET = "ETHEREUM_SEPOLIA_TESTNET",
    BITCOIN_MAINNET = "BITCOIN_MAINNET",
    BITCOIN_TESTNET = "BITCOIN_TESTNET",
}

M.QueryTokenStandard = {
    ERC20 = "ERC20",
    ERC721 = "ERC721",
    ERC1155 = "ERC1155",
}

M.ErrorType = {
    VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION",
    RESOURCE_NOT_FOUND_EXCEPTION = "RESOURCE_NOT_FOUND_EXCEPTION",
}

M.ResourceType = {
    COLLECTION = "collection",
}

M.ValidationExceptionReason = {
    UNKNOWN_OPERATION = "unknownOperation",
    CANNOT_PARSE = "cannotParse",
    FIELD_VALIDATION_FAILED = "fieldValidationFailed",
    OTHER = "other",
}

M.ConfirmationStatus = {
    FINAL = "FINAL",
    NONFINAL = "NONFINAL",
}

M.ExecutionStatus = {
    FAILED = "FAILED",
    SUCCEEDED = "SUCCEEDED",
}

M.ListFilteredTransactionEventsSortBy = {
    blockchainInstant = "blockchainInstant",
}

M.SortOrder = {
    ASCENDING = "ASCENDING",
    DESCENDING = "DESCENDING",
}

M.QueryTransactionEventType = {
    ERC20_TRANSFER = "ERC20_TRANSFER",
    ERC20_MINT = "ERC20_MINT",
    ERC20_BURN = "ERC20_BURN",
    ERC20_DEPOSIT = "ERC20_DEPOSIT",
    ERC20_WITHDRAWAL = "ERC20_WITHDRAWAL",
    ERC721_TRANSFER = "ERC721_TRANSFER",
    ERC1155_TRANSFER = "ERC1155_TRANSFER",
    BITCOIN_VIN = "BITCOIN_VIN",
    BITCOIN_VOUT = "BITCOIN_VOUT",
    INTERNAL_ETH_TRANSFER = "INTERNAL_ETH_TRANSFER",
    ETH_TRANSFER = "ETH_TRANSFER",
}

M.ListTransactionsSortBy = {
    TRANSACTION_TIMESTAMP = "TRANSACTION_TIMESTAMP",
}

return M
