local record M
    pages_list_annotation_import_jobs: function(client: table, input: table): function(): table, table
    items_list_annotation_import_jobs: function(client: table, input: table): function(): any
    pages_list_annotation_store_versions: function(client: table, input: table): function(): table, table
    items_list_annotation_store_versions: function(client: table, input: table): function(): any
    pages_list_annotation_stores: function(client: table, input: table): function(): table, table
    items_list_annotation_stores: function(client: table, input: table): function(): any
    pages_list_batch: function(client: table, input: table): function(): table, table
    items_list_batch: function(client: table, input: table): function(): any
    pages_list_configurations: function(client: table, input: table): function(): table, table
    items_list_configurations: function(client: table, input: table): function(): any
    pages_list_multipart_read_set_uploads: function(client: table, input: table): function(): table, table
    items_list_multipart_read_set_uploads: function(client: table, input: table): function(): any
    pages_list_read_set_activation_jobs: function(client: table, input: table): function(): table, table
    items_list_read_set_activation_jobs: function(client: table, input: table): function(): any
    pages_list_read_set_export_jobs: function(client: table, input: table): function(): table, table
    items_list_read_set_export_jobs: function(client: table, input: table): function(): any
    pages_list_read_set_import_jobs: function(client: table, input: table): function(): table, table
    items_list_read_set_import_jobs: function(client: table, input: table): function(): any
    pages_list_read_set_upload_parts: function(client: table, input: table): function(): table, table
    items_list_read_set_upload_parts: function(client: table, input: table): function(): any
    pages_list_read_sets: function(client: table, input: table): function(): table, table
    items_list_read_sets: function(client: table, input: table): function(): any
    pages_list_reference_import_jobs: function(client: table, input: table): function(): table, table
    items_list_reference_import_jobs: function(client: table, input: table): function(): any
    pages_list_reference_stores: function(client: table, input: table): function(): table, table
    items_list_reference_stores: function(client: table, input: table): function(): any
    pages_list_references: function(client: table, input: table): function(): table, table
    items_list_references: function(client: table, input: table): function(): any
    pages_list_run_caches: function(client: table, input: table): function(): table, table
    items_list_run_caches: function(client: table, input: table): function(): any
    pages_list_run_groups: function(client: table, input: table): function(): table, table
    items_list_run_groups: function(client: table, input: table): function(): any
    pages_list_run_tasks: function(client: table, input: table): function(): table, table
    items_list_run_tasks: function(client: table, input: table): function(): any
    pages_list_runs: function(client: table, input: table): function(): table, table
    items_list_runs: function(client: table, input: table): function(): any
    pages_list_runs_in_batch: function(client: table, input: table): function(): table, table
    items_list_runs_in_batch: function(client: table, input: table): function(): any
    pages_list_sequence_stores: function(client: table, input: table): function(): table, table
    items_list_sequence_stores: function(client: table, input: table): function(): any
    pages_list_shares: function(client: table, input: table): function(): table, table
    items_list_shares: function(client: table, input: table): function(): any
    pages_list_variant_import_jobs: function(client: table, input: table): function(): table, table
    items_list_variant_import_jobs: function(client: table, input: table): function(): any
    pages_list_variant_stores: function(client: table, input: table): function(): table, table
    items_list_variant_stores: function(client: table, input: table): function(): any
    pages_list_workflow_versions: function(client: table, input: table): function(): table, table
    items_list_workflow_versions: function(client: table, input: table): function(): any
    pages_list_workflows: function(client: table, input: table): function(): table, table
    items_list_workflows: function(client: table, input: table): function(): any
end

return M
