local M = {}

M.Accelerators = {
    GPU = "GPU",
}

M.ShareStatus = {
    PENDING = "PENDING",
    ACTIVATING = "ACTIVATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    DELETED = "DELETED",
    FAILED = "FAILED",
}

M.ReadSetActivationJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELLING = "CANCELLING",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_FAILURES = "COMPLETED_WITH_FAILURES",
}

M.ReadSetActivationJobItemStatus = {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    FINISHED = "FINISHED",
    FAILED = "FAILED",
}

M.JobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELLED = "CANCELLED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    COMPLETED_WITH_FAILURES = "COMPLETED_WITH_FAILURES",
}

M.EncryptionType = {
    KMS = "KMS",
}

M.StoreFormat = {
    GFF = "GFF",
    TSV = "TSV",
    VCF = "VCF",
}

M.AnnotationType = {
    GENERIC = "GENERIC",
    CHR_POS = "CHR_POS",
    CHR_POS_REF_ALT = "CHR_POS_REF_ALT",
    CHR_START_END_ONE_BASE = "CHR_START_END_ONE_BASE",
    CHR_START_END_REF_ALT_ONE_BASE = "CHR_START_END_REF_ALT_ONE_BASE",
    CHR_START_END_ZERO_BASE = "CHR_START_END_ZERO_BASE",
    CHR_START_END_REF_ALT_ZERO_BASE = "CHR_START_END_REF_ALT_ZERO_BASE",
}

M.FormatToHeaderKey = {
    CHR = "CHR",
    START = "START",
    END = "END",
    REF = "REF",
    ALT = "ALT",
    POS = "POS",
}

M.SchemaValueType = {
    LONG = "LONG",
    INT = "INT",
    STRING = "STRING",
    FLOAT = "FLOAT",
    DOUBLE = "DOUBLE",
    BOOLEAN = "BOOLEAN",
}

M.StoreStatus = {
    CREATING = "CREATING",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
}

M.VersionStatus = {
    CREATING = "CREATING",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    ACTIVE = "ACTIVE",
    FAILED = "FAILED",
}

M.BatchStatus = {
    CREATING = "CREATING",
    PENDING = "PENDING",
    SUBMITTING = "SUBMITTING",
    INPROGRESS = "INPROGRESS",
    STOPPING = "STOPPING",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    PROCESSED = "PROCESSED",
    RUNS_DELETING = "RUNS_DELETING",
    RUNS_DELETED = "RUNS_DELETED",
}

M.CacheBehavior = {
    CACHE_ON_FAILURE = "CACHE_ON_FAILURE",
    CACHE_ALWAYS = "CACHE_ALWAYS",
}

M.ReadSetPartSource = {
    SOURCE1 = "SOURCE1",
    SOURCE2 = "SOURCE2",
}

M.ConfigurationStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    DELETED = "DELETED",
    FAILED = "FAILED",
}

M.FileType = {
    FASTQ = "FASTQ",
    BAM = "BAM",
    CRAM = "CRAM",
    UBAM = "UBAM",
}

M.RunCacheStatus = {
    ACTIVE = "ACTIVE",
    DELETED = "DELETED",
    FAILED = "FAILED",
}

M.ETagAlgorithmFamily = {
    MD5UP = "MD5up",
    SHA256UP = "SHA256up",
    SHA512UP = "SHA512up",
}

M.SequenceStoreStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    FAILED = "FAILED",
}

M.SourceReferenceType = {
    BRANCH = "BRANCH",
    TAG = "TAG",
    COMMIT = "COMMIT",
}

M.WorkflowEngine = {
    WDL = "WDL",
    NEXTFLOW = "NEXTFLOW",
    CWL = "CWL",
    WDL_LENIENT = "WDL_LENIENT",
}

M.StorageType = {
    STATIC = "STATIC",
    DYNAMIC = "DYNAMIC",
}

M.WorkflowStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    UPDATING = "UPDATING",
    DELETED = "DELETED",
    FAILED = "FAILED",
    INACTIVE = "INACTIVE",
}

M.CreationType = {
    IMPORT = "IMPORT",
    UPLOAD = "UPLOAD",
}

M.RunLogLevel = {
    OFF = "OFF",
    FATAL = "FATAL",
    ERROR = "ERROR",
    ALL = "ALL",
}

M.NetworkingMode = {
    RESTRICTED = "RESTRICTED",
    VPC = "VPC",
}

M.RunRetentionMode = {
    RETAIN = "RETAIN",
    REMOVE = "REMOVE",
}

M.WorkflowType = {
    PRIVATE = "PRIVATE",
    READY2RUN = "READY2RUN",
}

M.ETagAlgorithm = {
    FASTQ_MD5UP = "FASTQ_MD5up",
    BAM_MD5UP = "BAM_MD5up",
    CRAM_MD5UP = "CRAM_MD5up",
    FASTQ_SHA256UP = "FASTQ_SHA256up",
    BAM_SHA256UP = "BAM_SHA256up",
    CRAM_SHA256UP = "CRAM_SHA256up",
    FASTQ_SHA512UP = "FASTQ_SHA512up",
    BAM_SHA512UP = "BAM_SHA512up",
    CRAM_SHA512UP = "CRAM_SHA512up",
}

M.ReadSetExportJobItemStatus = {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    FINISHED = "FINISHED",
    FAILED = "FAILED",
}

M.ReadSetExportJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELLING = "CANCELLING",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_FAILURES = "COMPLETED_WITH_FAILURES",
}

M.ShareResourceType = {
    VARIANT_STORE = "VARIANT_STORE",
    ANNOTATION_STORE = "ANNOTATION_STORE",
    WORKFLOW = "WORKFLOW",
}

M.ReadSetFile = {
    SOURCE1 = "SOURCE1",
    SOURCE2 = "SOURCE2",
    INDEX = "INDEX",
}

M.ReadSetImportJobItemStatus = {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    FINISHED = "FINISHED",
    FAILED = "FAILED",
}

M.ReadSetImportJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELLING = "CANCELLING",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_FAILURES = "COMPLETED_WITH_FAILURES",
}

M.ReadSetStatus = {
    ARCHIVED = "ARCHIVED",
    ACTIVATING = "ACTIVATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    DELETED = "DELETED",
    PROCESSING_UPLOAD = "PROCESSING_UPLOAD",
    UPLOAD_FAILED = "UPLOAD_FAILED",
}

M.ReferenceFile = {
    SOURCE = "SOURCE",
    INDEX = "INDEX",
}

M.ReferenceImportJobItemStatus = {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    FINISHED = "FINISHED",
    FAILED = "FAILED",
}

M.ReferenceImportJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELLING = "CANCELLING",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_FAILURES = "COMPLETED_WITH_FAILURES",
}

M.ReferenceCreationType = {
    IMPORT = "IMPORT",
}

M.ReferenceStatus = {
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    DELETED = "DELETED",
}

M.RunExport = {
    DEFINITION = "DEFINITION",
}

M.RunStatus = {
    PENDING = "PENDING",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    STOPPING = "STOPPING",
    COMPLETED = "COMPLETED",
    DELETED = "DELETED",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
}

M.TaskStatus = {
    PENDING = "PENDING",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    STOPPING = "STOPPING",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
}

M.StoreType = {
    SEQUENCE_STORE = "SEQUENCE_STORE",
    REFERENCE_STORE = "REFERENCE_STORE",
}

M.WorkflowExport = {
    DEFINITION = "DEFINITION",
    README = "README",
}

M.SubmissionStatus = {
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    CANCEL_SUCCESS = "CANCEL_SUCCESS",
    CANCEL_FAILED = "CANCEL_FAILED",
    DELETE_SUCCESS = "DELETE_SUCCESS",
    DELETE_FAILED = "DELETE_FAILED",
}

M.ResourceOwner = {
    SELF = "SELF",
    OTHER = "OTHER",
}

return M
