local M = {}

M.ActionCompletionStrategy = {
    AUTO_COMPLETION_UPON_APPROVAL = "AUTO_COMPLETION_UPON_APPROVAL",
}

M.AdditionalSecurityRequirement = {
    APPROVER_VERIFICATION_REQUIRED = "APPROVER_VERIFICATION_REQUIRED",
}

M.ApproverLastActivity = {
    VOTED = "VOTED",
    BASELINED = "BASELINED",
    RESPONDED_TO_INVITATION = "RESPONDED_TO_INVITATION",
}

M.MfaSyncStatus = {
    IN_SYNC = "IN_SYNC",
    OUT_OF_SYNC = "OUT_OF_SYNC",
}

M.MfaType = {
    EMAIL_OTP = "EMAIL_OTP",
}

M.IdentityStatus = {
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
    INVALID = "INVALID",
}

M.ApprovalTeamStatus = {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    DELETING = "DELETING",
    PENDING = "PENDING",
}

M.ApprovalTeamStatusCode = {
    VALIDATING = "VALIDATING",
    PENDING_ACTIVATION = "PENDING_ACTIVATION",
    FAILED_VALIDATION = "FAILED_VALIDATION",
    FAILED_ACTIVATION = "FAILED_ACTIVATION",
    UPDATE_PENDING_APPROVAL = "UPDATE_PENDING_APPROVAL",
    UPDATE_PENDING_ACTIVATION = "UPDATE_PENDING_ACTIVATION",
    UPDATE_FAILED_APPROVAL = "UPDATE_FAILED_APPROVAL",
    UPDATE_FAILED_ACTIVATION = "UPDATE_FAILED_ACTIVATION",
    UPDATE_FAILED_VALIDATION = "UPDATE_FAILED_VALIDATION",
    DELETE_PENDING_APPROVAL = "DELETE_PENDING_APPROVAL",
    DELETE_FAILED_APPROVAL = "DELETE_FAILED_APPROVAL",
    DELETE_FAILED_VALIDATION = "DELETE_FAILED_VALIDATION",
}

M.UpdateAction = {
    SYNCHRONIZE_MFA_DEVICES = "SYNCHRONIZE_MFA_DEVICES",
}

M.PolicyType = {
    AWS_MANAGED = "AWS_MANAGED",
    AWS_RAM = "AWS_RAM",
}

M.PolicyStatus = {
    ATTACHABLE = "ATTACHABLE",
    DEPRECATED = "DEPRECATED",
}

M.IdentitySourceType = {
    IAM_IDENTITY_CENTER = "IAM_IDENTITY_CENTER",
}

M.IdentitySourceStatus = {
    CREATING = "CREATING",
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    ERROR = "ERROR",
}

M.IdentitySourceStatusCode = {
    ACCESS_DENIED = "ACCESS_DENIED",
    DELETION_FAILED = "DELETION_FAILED",
    IDC_INSTANCE_NOT_FOUND = "IDC_INSTANCE_NOT_FOUND",
    IDC_INSTANCE_NOT_VALID = "IDC_INSTANCE_NOT_VALID",
}

M.SessionResponse = {
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    NO_RESPONSE = "NO_RESPONSE",
}

M.SessionExecutionStatus = {
    EXECUTED = "EXECUTED",
    FAILED = "FAILED",
    PENDING = "PENDING",
}

M.SessionStatus = {
    PENDING = "PENDING",
    CANCELLED = "CANCELLED",
    APPROVED = "APPROVED",
    FAILED = "FAILED",
    CREATING = "CREATING",
}

M.SessionStatusCode = {
    REJECTED = "REJECTED",
    EXPIRED = "EXPIRED",
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED",
    ALL_APPROVERS_IN_SESSION = "ALL_APPROVERS_IN_SESSION",
}

M.FilterField = {
    ACTION_NAME = "ActionName",
    APPROVAL_TEAM_NAME = "ApprovalTeamName",
    VOTING_TIME = "VotingTime",
    VOTE = "Vote",
    SESSION_STATUS = "SessionStatus",
    INITIATION_TIME = "InitiationTime",
}

M.Operator = {
    EQUALS = "EQ",
    NOT_EQUALS = "NE",
    GREATER_THAN = "GT",
    LESS_THAN = "LT",
    GREATER_THAN_OR_EQUAL_TO = "GTE",
    LESS_THAN_OR_EQUAL_TO = "LTE",
    CONTAINS = "CONTAINS",
    DOES_NOT_CONTAIN = "NOT_CONTAINS",
    BETWEEN = "BETWEEN",
}

return M
