local M = {}

M.MigrationWorkflowStatusEnum = {
    CREATING = "CREATING",
    NOT_STARTED = "NOT_STARTED",
    CREATION_FAILED = "CREATION_FAILED",
    STARTING = "STARTING",
    IN_PROGRESS = "IN_PROGRESS",
    WORKFLOW_FAILED = "WORKFLOW_FAILED",
    PAUSED = "PAUSED",
    PAUSING = "PAUSING",
    PAUSING_FAILED = "PAUSING_FAILED",
    USER_ATTENTION_REQUIRED = "USER_ATTENTION_REQUIRED",
    DELETING = "DELETING",
    DELETION_FAILED = "DELETION_FAILED",
    DELETED = "DELETED",
    COMPLETED = "COMPLETED",
}

M.DataType = {
    STRING = "STRING",
    INTEGER = "INTEGER",
    STRINGLIST = "STRINGLIST",
    STRINGMAP = "STRINGMAP",
}

M.TemplateStatus = {
    CREATED = "CREATED",
    READY = "READY",
    PENDING_CREATION = "PENDING_CREATION",
    CREATING = "CREATING",
    CREATION_FAILED = "CREATION_FAILED",
}

M.PluginHealth = {
    PLUGIN_HEALTHY = "HEALTHY",
    PLUGIN_UNHEALTHY = "UNHEALTHY",
}

M.StepActionType = {
    MANUAL = "MANUAL",
    AUTOMATED = "AUTOMATED",
}

M.RunEnvironment = {
    AWS = "AWS",
    ONPREMISE = "ONPREMISE",
}

M.TargetType = {
    SINGLE = "SINGLE",
    ALL = "ALL",
    NONE = "NONE",
}

M.Owner = {
    AWSManaged = "AWS_MANAGED",
    CUSTOM = "CUSTOM",
}

M.StepGroupStatus = {
    AWAITING_DEPENDENCIES = "AWAITING_DEPENDENCIES",
    READY = "READY",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    PAUSED = "PAUSED",
    PAUSING = "PAUSING",
    USER_ATTENTION_REQUIRED = "USER_ATTENTION_REQUIRED",
}

M.StepStatus = {
    AWAITING_DEPENDENCIES = "AWAITING_DEPENDENCIES",
    SKIPPED = "SKIPPED",
    READY = "READY",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    PAUSED = "PAUSED",
    USER_ATTENTION_REQUIRED = "USER_ATTENTION_REQUIRED",
}

return M
