-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("route53.endpoint_rules")
local restxml_protocol = require("smithy.protocol.restxml")
local schemas = require("route53.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AWSDnsV20130401"
    if not cfg.protocol then
        cfg.protocol = restxml_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "route53", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:activateKeySigningKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.ActivateKeySigningKey, input, options)
end

function Client:associateVPCWithHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.AssociateVPCWithHostedZone, input, options)
end

function Client:changeCidrCollection(input, options)
    return self:invokeOperation(schemas.Service, schemas.ChangeCidrCollection, input, options)
end

function Client:changeResourceRecordSets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ChangeResourceRecordSets, input, options)
end

function Client:changeTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ChangeTagsForResource, input, options)
end

function Client:createCidrCollection(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCidrCollection, input, options)
end

function Client:createHealthCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateHealthCheck, input, options)
end

function Client:createHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateHostedZone, input, options)
end

function Client:createKeySigningKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateKeySigningKey, input, options)
end

function Client:createQueryLoggingConfig(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateQueryLoggingConfig, input, options)
end

function Client:createReusableDelegationSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateReusableDelegationSet, input, options)
end

function Client:createTrafficPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTrafficPolicy, input, options)
end

function Client:createTrafficPolicyInstance(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTrafficPolicyInstance, input, options)
end

function Client:createTrafficPolicyVersion(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTrafficPolicyVersion, input, options)
end

function Client:createVPCAssociationAuthorization(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateVPCAssociationAuthorization, input, options)
end

function Client:deactivateKeySigningKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeactivateKeySigningKey, input, options)
end

function Client:deleteCidrCollection(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCidrCollection, input, options)
end

function Client:deleteHealthCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteHealthCheck, input, options)
end

function Client:deleteHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteHostedZone, input, options)
end

function Client:deleteKeySigningKey(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteKeySigningKey, input, options)
end

function Client:deleteQueryLoggingConfig(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteQueryLoggingConfig, input, options)
end

function Client:deleteReusableDelegationSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteReusableDelegationSet, input, options)
end

function Client:deleteTrafficPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTrafficPolicy, input, options)
end

function Client:deleteTrafficPolicyInstance(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTrafficPolicyInstance, input, options)
end

function Client:deleteVPCAssociationAuthorization(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteVPCAssociationAuthorization, input, options)
end

function Client:disableHostedZoneDNSSEC(input, options)
    return self:invokeOperation(schemas.Service, schemas.DisableHostedZoneDNSSEC, input, options)
end

function Client:disassociateVPCFromHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.DisassociateVPCFromHostedZone, input, options)
end

function Client:enableHostedZoneDNSSEC(input, options)
    return self:invokeOperation(schemas.Service, schemas.EnableHostedZoneDNSSEC, input, options)
end

function Client:getAccountLimit(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetAccountLimit, input, options)
end

function Client:getChange(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetChange, input, options)
end

function Client:getCheckerIpRanges(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCheckerIpRanges, input, options)
end

function Client:getDNSSEC(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetDNSSEC, input, options)
end

function Client:getGeoLocation(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetGeoLocation, input, options)
end

function Client:getHealthCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHealthCheck, input, options)
end

function Client:getHealthCheckCount(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHealthCheckCount, input, options)
end

function Client:getHealthCheckLastFailureReason(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHealthCheckLastFailureReason, input, options)
end

function Client:getHealthCheckStatus(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHealthCheckStatus, input, options)
end

function Client:getHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHostedZone, input, options)
end

function Client:getHostedZoneCount(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHostedZoneCount, input, options)
end

function Client:getHostedZoneLimit(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetHostedZoneLimit, input, options)
end

function Client:getQueryLoggingConfig(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetQueryLoggingConfig, input, options)
end

function Client:getReusableDelegationSet(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetReusableDelegationSet, input, options)
end

function Client:getReusableDelegationSetLimit(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetReusableDelegationSetLimit, input, options)
end

function Client:getTrafficPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrafficPolicy, input, options)
end

function Client:getTrafficPolicyInstance(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrafficPolicyInstance, input, options)
end

function Client:getTrafficPolicyInstanceCount(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTrafficPolicyInstanceCount, input, options)
end

function Client:listCidrBlocks(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCidrBlocks, input, options)
end

function Client:listCidrCollections(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCidrCollections, input, options)
end

function Client:listCidrLocations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCidrLocations, input, options)
end

function Client:listGeoLocations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListGeoLocations, input, options)
end

function Client:listHealthChecks(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListHealthChecks, input, options)
end

function Client:listHostedZones(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListHostedZones, input, options)
end

function Client:listHostedZonesByName(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListHostedZonesByName, input, options)
end

function Client:listHostedZonesByVPC(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListHostedZonesByVPC, input, options)
end

function Client:listQueryLoggingConfigs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListQueryLoggingConfigs, input, options)
end

function Client:listResourceRecordSets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListResourceRecordSets, input, options)
end

function Client:listReusableDelegationSets(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListReusableDelegationSets, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:listTagsForResources(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResources, input, options)
end

function Client:listTrafficPolicies(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrafficPolicies, input, options)
end

function Client:listTrafficPolicyInstances(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrafficPolicyInstances, input, options)
end

function Client:listTrafficPolicyInstancesByHostedZone(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrafficPolicyInstancesByHostedZone, input, options)
end

function Client:listTrafficPolicyInstancesByPolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrafficPolicyInstancesByPolicy, input, options)
end

function Client:listTrafficPolicyVersions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTrafficPolicyVersions, input, options)
end

function Client:listVPCAssociationAuthorizations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListVPCAssociationAuthorizations, input, options)
end

function Client:testDNSAnswer(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestDNSAnswer, input, options)
end

function Client:updateHealthCheck(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateHealthCheck, input, options)
end

function Client:updateHostedZoneComment(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateHostedZoneComment, input, options)
end

function Client:updateHostedZoneFeatures(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateHostedZoneFeatures, input, options)
end

function Client:updateTrafficPolicyComment(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateTrafficPolicyComment, input, options)
end

function Client:updateTrafficPolicyInstance(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateTrafficPolicyInstance, input, options)
end

return M
