-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated endpoint ruleset tests — do not edit

local endpoint = require("smithy.endpoint")
local ruleset = require("kms.endpoint_rules")

describe("endpoint rules", function()
    it("For region af-south-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "af-south-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.af-south-1.amazonaws.com", result.url)
    end)

    it("For region af-south-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "af-south-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.af-south-1.amazonaws.com", result.url)
    end)

    it("For region ap-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-east-1.amazonaws.com", result.url)
    end)

    it("For region ap-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-east-1.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-northeast-1.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-northeast-1.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-2 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-2",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-northeast-2.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-2 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-2",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-northeast-2.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-3 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-3",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-northeast-3.amazonaws.com", result.url)
    end)

    it("For region ap-northeast-3 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-northeast-3",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-northeast-3.amazonaws.com", result.url)
    end)

    it("For region ap-south-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-south-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-south-1.amazonaws.com", result.url)
    end)

    it("For region ap-south-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-south-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-south-1.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-southeast-1.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-southeast-1.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-2 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-2",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-southeast-2.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-2 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-2",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-southeast-2.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-3 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-3",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ap-southeast-3.amazonaws.com", result.url)
    end)

    it("For region ap-southeast-3 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ap-southeast-3",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ap-southeast-3.amazonaws.com", result.url)
    end)

    it("For region ca-central-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "ca-central-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.ca-central-1.amazonaws.com", result.url)
    end)

    it("For region ca-central-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "ca-central-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.ca-central-1.amazonaws.com", result.url)
    end)

    it("For region eu-central-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-central-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-central-1.amazonaws.com", result.url)
    end)

    it("For region eu-central-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-central-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-central-1.amazonaws.com", result.url)
    end)

    it("For region eu-north-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-north-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-north-1.amazonaws.com", result.url)
    end)

    it("For region eu-north-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-north-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-north-1.amazonaws.com", result.url)
    end)

    it("For region eu-south-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-south-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-south-1.amazonaws.com", result.url)
    end)

    it("For region eu-south-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-south-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-south-1.amazonaws.com", result.url)
    end)

    it("For region eu-west-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-west-1.amazonaws.com", result.url)
    end)

    it("For region eu-west-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-west-1.amazonaws.com", result.url)
    end)

    it("For region eu-west-2 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-2",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-west-2.amazonaws.com", result.url)
    end)

    it("For region eu-west-2 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-2",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-west-2.amazonaws.com", result.url)
    end)

    it("For region eu-west-3 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-3",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.eu-west-3.amazonaws.com", result.url)
    end)

    it("For region eu-west-3 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "eu-west-3",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.eu-west-3.amazonaws.com", result.url)
    end)

    it("For region me-south-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "me-south-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.me-south-1.amazonaws.com", result.url)
    end)

    it("For region me-south-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "me-south-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.me-south-1.amazonaws.com", result.url)
    end)

    it("For region sa-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "sa-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.sa-east-1.amazonaws.com", result.url)
    end)

    it("For region sa-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "sa-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.sa-east-1.amazonaws.com", result.url)
    end)

    it("For region us-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-east-1.amazonaws.com", result.url)
    end)

    it("For region us-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-east-1.amazonaws.com", result.url)
    end)

    it("For region us-east-2 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-east-2",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-east-2.amazonaws.com", result.url)
    end)

    it("For region us-east-2 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-east-2",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-east-2.amazonaws.com", result.url)
    end)

    it("For region us-west-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-west-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-west-1.amazonaws.com", result.url)
    end)

    it("For region us-west-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-west-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-west-1.amazonaws.com", result.url)
    end)

    it("For region us-west-2 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-west-2",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-west-2.amazonaws.com", result.url)
    end)

    it("For region us-west-2 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-west-2",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-west-2.amazonaws.com", result.url)
    end)

    it("For region us-east-1 with FIPS enabled and DualStack enabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = true,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-east-1.api.aws", result.url)
    end)

    it("For region us-east-1 with FIPS disabled and DualStack enabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = false,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-east-1.api.aws", result.url)
    end)

    it("For region cn-north-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "cn-north-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.cn-north-1.amazonaws.com.cn", result.url)
    end)

    it("For region cn-northwest-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "cn-northwest-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.cn-northwest-1.amazonaws.com.cn", result.url)
    end)

    it("For region cn-north-1 with FIPS enabled and DualStack enabled", function()
        local params = {
            Region = "cn-north-1",
            UseFIPS = true,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.cn-north-1.api.amazonwebservices.com.cn", result.url)
    end)

    it("For region cn-north-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "cn-north-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.cn-north-1.amazonaws.com.cn", result.url)
    end)

    it("For region cn-north-1 with FIPS disabled and DualStack enabled", function()
        local params = {
            Region = "cn-north-1",
            UseFIPS = false,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.cn-north-1.api.amazonwebservices.com.cn", result.url)
    end)

    it("For region us-gov-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-gov-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-gov-east-1.amazonaws.com", result.url)
    end)

    it("For region us-gov-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-gov-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-gov-east-1.amazonaws.com", result.url)
    end)

    it("For region us-gov-west-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-gov-west-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-gov-west-1.amazonaws.com", result.url)
    end)

    it("For region us-gov-west-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-gov-west-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-gov-west-1.amazonaws.com", result.url)
    end)

    it("For region us-gov-east-1 with FIPS enabled and DualStack enabled", function()
        local params = {
            Region = "us-gov-east-1",
            UseFIPS = true,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-gov-east-1.api.aws", result.url)
    end)

    it("For region us-gov-east-1 with FIPS disabled and DualStack enabled", function()
        local params = {
            Region = "us-gov-east-1",
            UseFIPS = false,
            UseDualStack = true,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-gov-east-1.api.aws", result.url)
    end)

    it("For region us-iso-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-iso-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-iso-east-1.c2s.ic.gov", result.url)
    end)

    it("For region us-iso-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-iso-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-iso-east-1.c2s.ic.gov", result.url)
    end)

    it("For region us-iso-west-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-iso-west-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-iso-west-1.c2s.ic.gov", result.url)
    end)

    it("For region us-iso-west-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-iso-west-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-iso-west-1.c2s.ic.gov", result.url)
    end)

    it("For region us-isob-east-1 with FIPS disabled and DualStack disabled", function()
        local params = {
            Region = "us-isob-east-1",
            UseFIPS = false,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms.us-isob-east-1.sc2s.sgov.gov", result.url)
    end)

    it("For region us-isob-east-1 with FIPS enabled and DualStack disabled", function()
        local params = {
            Region = "us-isob-east-1",
            UseFIPS = true,
            UseDualStack = false,
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://kms-fips.us-isob-east-1.sc2s.sgov.gov", result.url)
    end)

    it("For custom endpoint with region set and fips disabled and dualstack disabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = false,
            UseDualStack = false,
            Endpoint = "https://example.com",
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://example.com", result.url)
    end)

    it("For custom endpoint with region not set and fips disabled and dualstack disabled", function()
        local params = {
            UseFIPS = false,
            UseDualStack = false,
            Endpoint = "https://example.com",
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_not_nil(result, "expected endpoint but got error: " .. tostring(err))
        assert.are.equal("https://example.com", result.url)
    end)

    it("For custom endpoint with fips enabled and dualstack disabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = true,
            UseDualStack = false,
            Endpoint = "https://example.com",
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_nil(result, "expected error but got result")
        assert.is_not_nil(err, "expected error but got nil")
        assert.are.equal("Invalid Configuration: FIPS and custom endpoint are not supported", err)
    end)

    it("For custom endpoint with fips disabled and dualstack enabled", function()
        local params = {
            Region = "us-east-1",
            UseFIPS = false,
            UseDualStack = true,
            Endpoint = "https://example.com",
        }
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_nil(result, "expected error but got result")
        assert.is_not_nil(err, "expected error but got nil")
        assert.are.equal("Invalid Configuration: Dualstack and custom endpoint are not supported", err)
    end)

    it("Missing region", function()
        local params = {}
        local result, err = endpoint.resolve(ruleset, params)
        assert.is_nil(result, "expected error but got result")
        assert.is_not_nil(err, "expected error but got nil")
        assert.are.equal("Invalid Configuration: Missing Region", err)
    end)

end)
