-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("amplifyuibuilder.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("amplifyuibuilder.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AmplifyUIBuilder"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "amplifyuibuilder", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createComponent(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateComponent, input, options)
end

function Client:createForm(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateForm, input, options)
end

function Client:createTheme(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateTheme, input, options)
end

function Client:deleteComponent(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteComponent, input, options)
end

function Client:deleteForm(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteForm, input, options)
end

function Client:deleteTheme(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteTheme, input, options)
end

function Client:exchangeCodeForToken(input, options)
    return self:invokeOperation(schemas.Service, schemas.ExchangeCodeForToken, input, options)
end

function Client:exportComponents(input, options)
    return self:invokeOperation(schemas.Service, schemas.ExportComponents, input, options)
end

function Client:exportForms(input, options)
    return self:invokeOperation(schemas.Service, schemas.ExportForms, input, options)
end

function Client:exportThemes(input, options)
    return self:invokeOperation(schemas.Service, schemas.ExportThemes, input, options)
end

function Client:getCodegenJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCodegenJob, input, options)
end

function Client:getComponent(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetComponent, input, options)
end

function Client:getForm(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetForm, input, options)
end

function Client:getMetadata(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetMetadata, input, options)
end

function Client:getTheme(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetTheme, input, options)
end

function Client:listCodegenJobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCodegenJobs, input, options)
end

function Client:listComponents(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListComponents, input, options)
end

function Client:listForms(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListForms, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:listThemes(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListThemes, input, options)
end

function Client:putMetadataFlag(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutMetadataFlag, input, options)
end

function Client:refreshToken(input, options)
    return self:invokeOperation(schemas.Service, schemas.RefreshToken, input, options)
end

function Client:startCodegenJob(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartCodegenJob, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateComponent(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateComponent, input, options)
end

function Client:updateForm(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateForm, input, options)
end

function Client:updateTheme(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateTheme, input, options)
end

return M
