local record M
    pages_list_centralization_rules_for_organization: function(client: table, input: table): function(): table, table
    items_list_centralization_rules_for_organization: function(client: table, input: table): function(): any
    pages_list_resource_telemetry: function(client: table, input: table): function(): table, table
    items_list_resource_telemetry: function(client: table, input: table): function(): any
    pages_list_resource_telemetry_for_organization: function(client: table, input: table): function(): table, table
    items_list_resource_telemetry_for_organization: function(client: table, input: table): function(): any
    pages_list_s3_table_integrations: function(client: table, input: table): function(): table, table
    items_list_s3_table_integrations: function(client: table, input: table): function(): any
    pages_list_telemetry_pipelines: function(client: table, input: table): function(): table, table
    items_list_telemetry_pipelines: function(client: table, input: table): function(): any
    pages_list_telemetry_rules: function(client: table, input: table): function(): table, table
    items_list_telemetry_rules: function(client: table, input: table): function(): any
    pages_list_telemetry_rules_for_organization: function(client: table, input: table): function(): table, table
    items_list_telemetry_rules_for_organization: function(client: table, input: table): function(): any
end

return M
