local M = {}

M.ConnectionType = {
    WEBSOCKET = "WEBSOCKET",
    CONNECTION_CREDENTIALS = "CONNECTION_CREDENTIALS",
    WEBRTC_CONNECTION = "WEBRTC_CONNECTION",
}

M.MeetingFeatureStatus = {
    AVAILABLE = "AVAILABLE",
    UNAVAILABLE = "UNAVAILABLE",
}

M.ResourceType = {
    CONTACT = "CONTACT",
    CONTACT_FLOW = "CONTACT_FLOW",
    INSTANCE = "INSTANCE",
    PARTICIPANT = "PARTICIPANT",
    HIERARCHY_LEVEL = "HIERARCHY_LEVEL",
    HIERARCHY_GROUP = "HIERARCHY_GROUP",
    USER = "USER",
    PHONE_NUMBER = "PHONE_NUMBER",
}

M.ScanDirection = {
    FORWARD = "FORWARD",
    BACKWARD = "BACKWARD",
}

M.SortKey = {
    DESCENDING = "DESCENDING",
    ASCENDING = "ASCENDING",
}

M.ArtifactStatus = {
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    IN_PROGRESS = "IN_PROGRESS",
}

M.MessageProcessingStatus = {
    PROCESSING = "PROCESSING",
    FAILED = "FAILED",
    REJECTED = "REJECTED",
}

M.ParticipantRole = {
    AGENT = "AGENT",
    CUSTOMER = "CUSTOMER",
    SYSTEM = "SYSTEM",
    CUSTOM_BOT = "CUSTOM_BOT",
    SUPERVISOR = "SUPERVISOR",
}

M.ChatItemType = {
    TYPING = "TYPING",
    PARTICIPANT_JOINED = "PARTICIPANT_JOINED",
    PARTICIPANT_LEFT = "PARTICIPANT_LEFT",
    CHAT_ENDED = "CHAT_ENDED",
    TRANSFER_SUCCEEDED = "TRANSFER_SUCCEEDED",
    TRANSFER_FAILED = "TRANSFER_FAILED",
    MESSAGE = "MESSAGE",
    EVENT = "EVENT",
    ATTACHMENT = "ATTACHMENT",
    CONNECTION_ACK = "CONNECTION_ACK",
    MESSAGE_DELIVERED = "MESSAGE_DELIVERED",
    MESSAGE_READ = "MESSAGE_READ",
}

return M
