local M = {}

M.EmissionsType = {
    TOTAL_LBM_CARBON_EMISSIONS = "TOTAL_LBM_CARBON_EMISSIONS",
    TOTAL_MBM_CARBON_EMISSIONS = "TOTAL_MBM_CARBON_EMISSIONS",
    TOTAL_SCOPE_1_CARBON_EMISSIONS = "TOTAL_SCOPE_1_CARBON_EMISSIONS",
    TOTAL_SCOPE_2_LBM_CARBON_EMISSIONS = "TOTAL_SCOPE_2_LBM_CARBON_EMISSIONS",
    TOTAL_SCOPE_2_MBM_CARBON_EMISSIONS = "TOTAL_SCOPE_2_MBM_CARBON_EMISSIONS",
    TOTAL_SCOPE_3_LBM_CARBON_EMISSIONS = "TOTAL_SCOPE_3_LBM_CARBON_EMISSIONS",
    TOTAL_SCOPE_3_MBM_CARBON_EMISSIONS = "TOTAL_SCOPE_3_MBM_CARBON_EMISSIONS",
}

M.Dimension = {
    USAGE_ACCOUNT_ID = "USAGE_ACCOUNT_ID",
    REGION = "REGION",
    SERVICE = "SERVICE",
}

M.TimeGranularity = {
    YEARLY_CALENDAR = "YEARLY_CALENDAR",
    YEARLY_FISCAL = "YEARLY_FISCAL",
    QUARTERLY_CALENDAR = "QUARTERLY_CALENDAR",
    QUARTERLY_FISCAL = "QUARTERLY_FISCAL",
    MONTHLY = "MONTHLY",
}

M.EmissionsUnit = {
    MT_CO2E = "MTCO2e",
}

return M
