local M = {}

M.ApplicationInstanceHealthStatus = {
    RUNNING = "RUNNING",
    ERROR = "ERROR",
    NOT_AVAILABLE = "NOT_AVAILABLE",
}

M.DesiredState = {
    RUNNING = "RUNNING",
    STOPPED = "STOPPED",
    REMOVED = "REMOVED",
}

M.DeviceReportedStatus = {
    STOPPING = "STOPPING",
    STOPPED = "STOPPED",
    STOP_ERROR = "STOP_ERROR",
    REMOVAL_FAILED = "REMOVAL_FAILED",
    REMOVAL_IN_PROGRESS = "REMOVAL_IN_PROGRESS",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    INSTALL_ERROR = "INSTALL_ERROR",
    LAUNCHED = "LAUNCHED",
    LAUNCH_ERROR = "LAUNCH_ERROR",
    INSTALL_IN_PROGRESS = "INSTALL_IN_PROGRESS",
}

M.ApplicationInstanceStatus = {
    DEPLOYMENT_PENDING = "DEPLOYMENT_PENDING",
    DEPLOYMENT_REQUESTED = "DEPLOYMENT_REQUESTED",
    DEPLOYMENT_IN_PROGRESS = "DEPLOYMENT_IN_PROGRESS",
    DEPLOYMENT_ERROR = "DEPLOYMENT_ERROR",
    DEPLOYMENT_SUCCEEDED = "DEPLOYMENT_SUCCEEDED",
    REMOVAL_PENDING = "REMOVAL_PENDING",
    REMOVAL_REQUESTED = "REMOVAL_REQUESTED",
    REMOVAL_IN_PROGRESS = "REMOVAL_IN_PROGRESS",
    REMOVAL_FAILED = "REMOVAL_FAILED",
    REMOVAL_SUCCEEDED = "REMOVAL_SUCCEEDED",
    DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED",
}

M.ConnectionType = {
    STATIC_IP = "STATIC_IP",
    DHCP = "DHCP",
}

M.ValidationExceptionReason = {
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION",
    CANNOT_PARSE = "CANNOT_PARSE",
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED",
    OTHER = "OTHER",
}

M.JobType = {
    OTA = "OTA",
    REBOOT = "REBOOT",
}

M.JobResourceType = {
    PACKAGE = "PACKAGE",
}

M.TemplateType = {
    RTSP_CAMERA_STREAM = "RTSP_CAMERA_STREAM",
}

M.PackageImportJobType = {
    NODE_PACKAGE_VERSION = "NODE_PACKAGE_VERSION",
    MARKETPLACE_NODE_PACKAGE_VERSION = "MARKETPLACE_NODE_PACKAGE_VERSION",
}

M.DeviceBrand = {
    AWS_PANORAMA = "AWS_PANORAMA",
    LENOVO = "LENOVO",
}

M.NetworkConnectionStatus = {
    CONNECTED = "CONNECTED",
    NOT_CONNECTED = "NOT_CONNECTED",
    CONNECTING = "CONNECTING",
}

M.DeviceAggregatedStatus = {
    ERROR = "ERROR",
    AWAITING_PROVISIONING = "AWAITING_PROVISIONING",
    PENDING = "PENDING",
    FAILED = "FAILED",
    DELETING = "DELETING",
    ONLINE = "ONLINE",
    OFFLINE = "OFFLINE",
    LEASE_EXPIRED = "LEASE_EXPIRED",
    UPDATE_NEEDED = "UPDATE_NEEDED",
    REBOOTING = "REBOOTING",
}

M.DeviceConnectionStatus = {
    ONLINE = "ONLINE",
    OFFLINE = "OFFLINE",
    AWAITING_CREDENTIALS = "AWAITING_CREDENTIALS",
    NOT_AVAILABLE = "NOT_AVAILABLE",
    ERROR = "ERROR",
}

M.UpdateProgress = {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    VERIFYING = "VERIFYING",
    REBOOTING = "REBOOTING",
    DOWNLOADING = "DOWNLOADING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
}

M.DeviceStatus = {
    AWAITING_PROVISIONING = "AWAITING_PROVISIONING",
    PENDING = "PENDING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    ERROR = "ERROR",
    DELETING = "DELETING",
}

M.DeviceType = {
    PANORAMA_APPLIANCE_DEVELOPER_KIT = "PANORAMA_APPLIANCE_DEVELOPER_KIT",
    PANORAMA_APPLIANCE = "PANORAMA_APPLIANCE",
}

M.NodeCategory = {
    BUSINESS_LOGIC = "BUSINESS_LOGIC",
    ML_MODEL = "ML_MODEL",
    MEDIA_SOURCE = "MEDIA_SOURCE",
    MEDIA_SINK = "MEDIA_SINK",
}

M.PortType = {
    BOOLEAN = "BOOLEAN",
    STRING = "STRING",
    INT32 = "INT32",
    FLOAT32 = "FLOAT32",
    MEDIA = "MEDIA",
}

M.NodeFromTemplateJobStatus = {
    PENDING = "PENDING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
}

M.PackageImportJobStatus = {
    PENDING = "PENDING",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
}

M.PackageVersionStatus = {
    REGISTER_PENDING = "REGISTER_PENDING",
    REGISTER_COMPLETED = "REGISTER_COMPLETED",
    FAILED = "FAILED",
    DELETING = "DELETING",
}

M.NodeInstanceStatus = {
    RUNNING = "RUNNING",
    ERROR = "ERROR",
    NOT_AVAILABLE = "NOT_AVAILABLE",
    PAUSED = "PAUSED",
}

M.StatusFilter = {
    DEPLOYMENT_SUCCEEDED = "DEPLOYMENT_SUCCEEDED",
    DEPLOYMENT_ERROR = "DEPLOYMENT_ERROR",
    REMOVAL_SUCCEEDED = "REMOVAL_SUCCEEDED",
    REMOVAL_FAILED = "REMOVAL_FAILED",
    PROCESSING_DEPLOYMENT = "PROCESSING_DEPLOYMENT",
    PROCESSING_REMOVAL = "PROCESSING_REMOVAL",
    DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED",
}

M.ListDevicesSortBy = {
    DEVICE_ID = "DEVICE_ID",
    CREATED_TIME = "CREATED_TIME",
    NAME = "NAME",
    DEVICE_AGGREGATED_STATUS = "DEVICE_AGGREGATED_STATUS",
}

M.SortOrder = {
    ASCENDING = "ASCENDING",
    DESCENDING = "DESCENDING",
}

M.NodeSignalValue = {
    PAUSE = "PAUSE",
    RESUME = "RESUME",
}

return M
