local M = {}

M.AdsInteractionExcludeEventType = {
    AD_MARKER_FOUND = "AD_MARKER_FOUND",
    NON_AD_MARKER_FOUND = "NON_AD_MARKER_FOUND",
    MAKING_ADS_REQUEST = "MAKING_ADS_REQUEST",
    MODIFIED_TARGET_URL = "MODIFIED_TARGET_URL",
    VAST_REDIRECT = "VAST_REDIRECT",
    EMPTY_VAST_RESPONSE = "EMPTY_VAST_RESPONSE",
    EMPTY_VMAP_RESPONSE = "EMPTY_VMAP_RESPONSE",
    VAST_RESPONSE = "VAST_RESPONSE",
    REDIRECTED_VAST_RESPONSE = "REDIRECTED_VAST_RESPONSE",
    FILLED_AVAIL = "FILLED_AVAIL",
    FILLED_OVERLAY_AVAIL = "FILLED_OVERLAY_AVAIL",
    BEACON_FIRED = "BEACON_FIRED",
    WARNING_NO_ADVERTISEMENTS = "WARNING_NO_ADVERTISEMENTS",
    WARNING_VPAID_AD_DROPPED = "WARNING_VPAID_AD_DROPPED",
    WARNING_URL_VARIABLE_SUBSTITUTION_FAILED = "WARNING_URL_VARIABLE_SUBSTITUTION_FAILED",
    ERROR_UNKNOWN = "ERROR_UNKNOWN",
    ERROR_UNKNOWN_HOST = "ERROR_UNKNOWN_HOST",
    ERROR_DISALLOWED_HOST = "ERROR_DISALLOWED_HOST",
    ERROR_ADS_IO = "ERROR_ADS_IO",
    ERROR_ADS_TIMEOUT = "ERROR_ADS_TIMEOUT",
    ERROR_ADS_RESPONSE_PARSE = "ERROR_ADS_RESPONSE_PARSE",
    ERROR_ADS_RESPONSE_UNKNOWN_ROOT_ELEMENT = "ERROR_ADS_RESPONSE_UNKNOWN_ROOT_ELEMENT",
    ERROR_ADS_INVALID_RESPONSE = "ERROR_ADS_INVALID_RESPONSE",
    ERROR_VAST_REDIRECT_EMPTY_RESPONSE = "ERROR_VAST_REDIRECT_EMPTY_RESPONSE",
    ERROR_VAST_REDIRECT_MULTIPLE_VAST = "ERROR_VAST_REDIRECT_MULTIPLE_VAST",
    ERROR_VAST_REDIRECT_FAILED = "ERROR_VAST_REDIRECT_FAILED",
    ERROR_VAST_MISSING_MEDIAFILES = "ERROR_VAST_MISSING_MEDIAFILES",
    ERROR_VAST_MISSING_CREATIVES = "ERROR_VAST_MISSING_CREATIVES",
    ERROR_VAST_MISSING_OVERLAYS = "ERROR_VAST_MISSING_OVERLAYS",
    ERROR_VAST_MISSING_IMPRESSION = "ERROR_VAST_MISSING_IMPRESSION",
    ERROR_VAST_INVALID_VAST_AD_TAG_URI = "ERROR_VAST_INVALID_VAST_AD_TAG_URI",
    ERROR_VAST_MULTIPLE_TRACKING_EVENTS = "ERROR_VAST_MULTIPLE_TRACKING_EVENTS",
    ERROR_VAST_MULTIPLE_LINEAR = "ERROR_VAST_MULTIPLE_LINEAR",
    ERROR_VAST_INVALID_MEDIA_FILE = "ERROR_VAST_INVALID_MEDIA_FILE",
    ERROR_FIRING_BEACON_FAILED = "ERROR_FIRING_BEACON_FAILED",
    ERROR_PERSONALIZATION_DISABLED = "ERROR_PERSONALIZATION_DISABLED",
    VOD_TIME_BASED_AVAIL_PLAN_VAST_RESPONSE_FOR_OFFSET = "VOD_TIME_BASED_AVAIL_PLAN_VAST_RESPONSE_FOR_OFFSET",
    VOD_TIME_BASED_AVAIL_PLAN_SUCCESS = "VOD_TIME_BASED_AVAIL_PLAN_SUCCESS",
    VOD_TIME_BASED_AVAIL_PLAN_WARNING_NO_ADVERTISEMENTS = "VOD_TIME_BASED_AVAIL_PLAN_WARNING_NO_ADVERTISEMENTS",
    INTERSTITIAL_VOD_SUCCESS = "INTERSTITIAL_VOD_SUCCESS",
    INTERSTITIAL_VOD_FAILURE = "INTERSTITIAL_VOD_FAILURE",
    PRE_ADS_REQUEST_HOOK_ERROR = "PRE_ADS_REQUEST_HOOK_ERROR",
    PRE_ADS_REQUEST_FUNCTION_ERROR = "PRE_ADS_REQUEST_FUNCTION_ERROR",
}

M.AdsInteractionPublishOptInEventType = {
    RAW_ADS_RESPONSE = "RAW_ADS_RESPONSE",
    RAW_ADS_REQUEST = "RAW_ADS_REQUEST",
    PRE_ADS_REQUEST_HOOK_SUMMARY = "PRE_ADS_REQUEST_HOOK_SUMMARY",
    PRE_ADS_REQUEST_FUNCTION_COMPLETED = "PRE_ADS_REQUEST_FUNCTION_COMPLETED",
}

M.MessageType = {
    SPLICE_INSERT = "SPLICE_INSERT",
    TIME_SIGNAL = "TIME_SIGNAL",
}

M.AlertCategory = {
    SCHEDULING_ERROR = "SCHEDULING_ERROR",
    PLAYBACK_WARNING = "PLAYBACK_WARNING",
    INFO = "INFO",
}

M.Operator = {
    EQUALS = "EQUALS",
}

M.LogType = {
    AS_RUN = "AS_RUN",
}

M.AdMarkupType = {
    DATERANGE = "DATERANGE",
    SCTE35_ENHANCED = "SCTE35_ENHANCED",
}

M.RuntimeType = {
    JSONATA = "JSONATA",
}

M.FunctionType = {
    HTTP_REQUEST = "HTTP_REQUEST",
    CUSTOM_OUTPUT = "CUSTOM_OUTPUT",
    SEQUENTIAL_EXECUTOR = "SEQUENTIAL_EXECUTOR",
}

M.MethodType = {
    GET = "GET",
    POST = "POST",
}

M.Type = {
    DASH = "DASH",
    HLS = "HLS",
}

M.LoggingStrategy = {
    VENDED_LOGS = "VENDED_LOGS",
    LEGACY_CLOUDWATCH = "LEGACY_CLOUDWATCH",
}

M.StreamingMediaFileConditioning = {
    TRANSCODE = "TRANSCODE",
    NONE = "NONE",
}

M.CompressionMethod = {
    NONE = "NONE",
    GZIP = "GZIP",
}

M.Method = {
    GET = "GET",
    POST = "POST",
}

M.FillPolicy = {
    FULL_AVAIL_ONLY = "FULL_AVAIL_ONLY",
    PARTIAL_AVAIL = "PARTIAL_AVAIL",
}

M.Mode = {
    OFF = "OFF",
    BEHIND_LIVE_EDGE = "BEHIND_LIVE_EDGE",
    AFTER_LIVE_EDGE = "AFTER_LIVE_EDGE",
}

M.OriginManifestType = {
    SINGLE_PERIOD = "SINGLE_PERIOD",
    MULTI_PERIOD = "MULTI_PERIOD",
}

M.EventName = {
    PRE_SESSION_INITIALIZATION = "PRE_SESSION_INITIALIZATION",
    PRE_ADS_REQUEST = "PRE_ADS_REQUEST",
}

M.InsertionMode = {
    STITCHED_ONLY = "STITCHED_ONLY",
    PLAYER_SELECT = "PLAYER_SELECT",
}

M.ManifestServiceExcludeEventType = {
    GENERATED_MANIFEST = "GENERATED_MANIFEST",
    ORIGIN_MANIFEST = "ORIGIN_MANIFEST",
    SESSION_INITIALIZED = "SESSION_INITIALIZED",
    TRACKING_RESPONSE = "TRACKING_RESPONSE",
    CONFIG_SYNTAX_ERROR = "CONFIG_SYNTAX_ERROR",
    CONFIG_SECURITY_ERROR = "CONFIG_SECURITY_ERROR",
    UNKNOWN_HOST = "UNKNOWN_HOST",
    TIMEOUT_ERROR = "TIMEOUT_ERROR",
    CONNECTION_ERROR = "CONNECTION_ERROR",
    IO_ERROR = "IO_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    HOST_DISALLOWED = "HOST_DISALLOWED",
    PARSING_ERROR = "PARSING_ERROR",
    MANIFEST_ERROR = "MANIFEST_ERROR",
    NO_MASTER_OR_MEDIA_PLAYLIST = "NO_MASTER_OR_MEDIA_PLAYLIST",
    NO_MASTER_PLAYLIST = "NO_MASTER_PLAYLIST",
    NO_MEDIA_PLAYLIST = "NO_MEDIA_PLAYLIST",
    INCOMPATIBLE_HLS_VERSION = "INCOMPATIBLE_HLS_VERSION",
    SCTE35_PARSING_ERROR = "SCTE35_PARSING_ERROR",
    INVALID_SINGLE_PERIOD_DASH_MANIFEST = "INVALID_SINGLE_PERIOD_DASH_MANIFEST",
    UNSUPPORTED_SINGLE_PERIOD_DASH_MANIFEST = "UNSUPPORTED_SINGLE_PERIOD_DASH_MANIFEST",
    LAST_PERIOD_MISSING_AUDIO = "LAST_PERIOD_MISSING_AUDIO",
    LAST_PERIOD_MISSING_AUDIO_WARNING = "LAST_PERIOD_MISSING_AUDIO_WARNING",
    ERROR_ORIGIN_PREFIX_INTERPOLATION = "ERROR_ORIGIN_PREFIX_INTERPOLATION",
    ERROR_ADS_INTERPOLATION = "ERROR_ADS_INTERPOLATION",
    ERROR_LIVE_PRE_ROLL_ADS_INTERPOLATION = "ERROR_LIVE_PRE_ROLL_ADS_INTERPOLATION",
    ERROR_CDN_AD_SEGMENT_INTERPOLATION = "ERROR_CDN_AD_SEGMENT_INTERPOLATION",
    ERROR_CDN_CONTENT_SEGMENT_INTERPOLATION = "ERROR_CDN_CONTENT_SEGMENT_INTERPOLATION",
    ERROR_SLATE_AD_URL_INTERPOLATION = "ERROR_SLATE_AD_URL_INTERPOLATION",
    ERROR_PROFILE_NAME_INTERPOLATION = "ERROR_PROFILE_NAME_INTERPOLATION",
    ERROR_BUMPER_START_INTERPOLATION = "ERROR_BUMPER_START_INTERPOLATION",
    ERROR_BUMPER_END_INTERPOLATION = "ERROR_BUMPER_END_INTERPOLATION",
    PRE_SESSION_INIT_HOOK_ERROR = "PRE_SESSION_INIT_HOOK_ERROR",
    PRE_SESSION_INIT_FUNCTION_ERROR = "PRE_SESSION_INIT_FUNCTION_ERROR",
}

M.ManifestServicePublishOptInEventType = {
    PRE_SESSION_INIT_HOOK_SUMMARY = "PRE_SESSION_INIT_HOOK_SUMMARY",
    PRE_SESSION_INIT_FUNCTION_COMPLETED = "PRE_SESSION_INIT_FUNCTION_COMPLETED",
}

M.TrafficShapingType = {
    RETRIEVAL_WINDOW = "RETRIEVAL_WINDOW",
    TPS = "TPS",
}

M.PrefetchScheduleType = {
    SINGLE = "SINGLE",
    RECURRING = "RECURRING",
}

M.ScheduleEntryType = {
    PROGRAM = "PROGRAM",
    FILLER_SLATE = "FILLER_SLATE",
    ALTERNATE_MEDIA = "ALTERNATE_MEDIA",
}

M.AccessType = {
    S3_SIGV4 = "S3_SIGV4",
    SECRETS_MANAGER_ACCESS_TOKEN = "SECRETS_MANAGER_ACCESS_TOKEN",
    AUTODETECT_SIGV4 = "AUTODETECT_SIGV4",
}

M.PlaybackMode = {
    LOOP = "LOOP",
    LINEAR = "LINEAR",
}

M.Tier = {
    BASIC = "BASIC",
    STANDARD = "STANDARD",
}

M.ChannelState = {
    RUNNING = "RUNNING",
    STOPPED = "STOPPED",
}

M.RelativePosition = {
    BEFORE_PROGRAM = "BEFORE_PROGRAM",
    AFTER_PROGRAM = "AFTER_PROGRAM",
}

M.ListPrefetchScheduleType = {
    SINGLE = "SINGLE",
    RECURRING = "RECURRING",
    ALL = "ALL",
}

return M
