local record M
    pages_list_account_pools: function(client: table, input: table): function(): table, table
    items_list_account_pools: function(client: table, input: table): function(): any
    pages_list_accounts_in_account_pool: function(client: table, input: table): function(): table, table
    items_list_accounts_in_account_pool: function(client: table, input: table): function(): any
    pages_list_asset_filters: function(client: table, input: table): function(): table, table
    items_list_asset_filters: function(client: table, input: table): function(): any
    pages_list_asset_revisions: function(client: table, input: table): function(): table, table
    items_list_asset_revisions: function(client: table, input: table): function(): any
    pages_list_connections: function(client: table, input: table): function(): table, table
    items_list_connections: function(client: table, input: table): function(): any
    pages_list_data_product_revisions: function(client: table, input: table): function(): table, table
    items_list_data_product_revisions: function(client: table, input: table): function(): any
    pages_list_data_source_run_activities: function(client: table, input: table): function(): table, table
    items_list_data_source_run_activities: function(client: table, input: table): function(): any
    pages_list_data_source_runs: function(client: table, input: table): function(): table, table
    items_list_data_source_runs: function(client: table, input: table): function(): any
    pages_list_data_sources: function(client: table, input: table): function(): table, table
    items_list_data_sources: function(client: table, input: table): function(): any
    pages_list_domain_units_for_parent: function(client: table, input: table): function(): table, table
    items_list_domain_units_for_parent: function(client: table, input: table): function(): any
    pages_list_domains: function(client: table, input: table): function(): table, table
    items_list_domains: function(client: table, input: table): function(): any
    pages_list_entity_owners: function(client: table, input: table): function(): table, table
    items_list_entity_owners: function(client: table, input: table): function(): any
    pages_list_environment_actions: function(client: table, input: table): function(): table, table
    items_list_environment_actions: function(client: table, input: table): function(): any
    pages_list_environment_blueprint_configurations: function(client: table, input: table): function(): table, table
    items_list_environment_blueprint_configurations: function(client: table, input: table): function(): any
    pages_list_environment_blueprints: function(client: table, input: table): function(): table, table
    items_list_environment_blueprints: function(client: table, input: table): function(): any
    pages_list_environment_profiles: function(client: table, input: table): function(): table, table
    items_list_environment_profiles: function(client: table, input: table): function(): any
    pages_list_environments: function(client: table, input: table): function(): table, table
    items_list_environments: function(client: table, input: table): function(): any
    pages_list_job_runs: function(client: table, input: table): function(): table, table
    items_list_job_runs: function(client: table, input: table): function(): any
    pages_list_lineage_events: function(client: table, input: table): function(): table, table
    items_list_lineage_events: function(client: table, input: table): function(): any
    pages_list_lineage_node_history: function(client: table, input: table): function(): table, table
    items_list_lineage_node_history: function(client: table, input: table): function(): any
    pages_list_metadata_generation_runs: function(client: table, input: table): function(): table, table
    items_list_metadata_generation_runs: function(client: table, input: table): function(): any
    pages_list_notebook_runs: function(client: table, input: table): function(): table, table
    items_list_notebook_runs: function(client: table, input: table): function(): any
    pages_list_notifications: function(client: table, input: table): function(): table, table
    items_list_notifications: function(client: table, input: table): function(): any
    pages_list_policy_grants: function(client: table, input: table): function(): table, table
    items_list_policy_grants: function(client: table, input: table): function(): any
    pages_list_project_memberships: function(client: table, input: table): function(): table, table
    items_list_project_memberships: function(client: table, input: table): function(): any
    pages_list_project_profiles: function(client: table, input: table): function(): table, table
    items_list_project_profiles: function(client: table, input: table): function(): any
    pages_list_projects: function(client: table, input: table): function(): table, table
    items_list_projects: function(client: table, input: table): function(): any
    pages_list_rules: function(client: table, input: table): function(): table, table
    items_list_rules: function(client: table, input: table): function(): any
    pages_list_subscription_grants: function(client: table, input: table): function(): table, table
    items_list_subscription_grants: function(client: table, input: table): function(): any
    pages_list_subscription_requests: function(client: table, input: table): function(): table, table
    items_list_subscription_requests: function(client: table, input: table): function(): any
    pages_list_subscription_targets: function(client: table, input: table): function(): table, table
    items_list_subscription_targets: function(client: table, input: table): function(): any
    pages_list_subscriptions: function(client: table, input: table): function(): table, table
    items_list_subscriptions: function(client: table, input: table): function(): any
    pages_list_time_series_data_points: function(client: table, input: table): function(): table, table
    items_list_time_series_data_points: function(client: table, input: table): function(): any
    pages_query_graph: function(client: table, input: table): function(): table, table
    items_query_graph: function(client: table, input: table): function(): any
    pages_search: function(client: table, input: table): function(): table, table
    items_search: function(client: table, input: table): function(): any
    pages_search_group_profiles: function(client: table, input: table): function(): table, table
    items_search_group_profiles: function(client: table, input: table): function(): any
    pages_search_listings: function(client: table, input: table): function(): table, table
    items_search_listings: function(client: table, input: table): function(): any
    pages_search_types: function(client: table, input: table): function(): table, table
    items_search_types: function(client: table, input: table): function(): any
    pages_search_user_profiles: function(client: table, input: table): function(): table, table
    items_search_user_profiles: function(client: table, input: table): function(): any
end

return M
