-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("osis.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("osis.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AmazonOpenSearchIngestionService"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "osis", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createPipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreatePipeline, input, options)
end

function Client:createPipelineEndpoint(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreatePipelineEndpoint, input, options)
end

function Client:deletePipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeletePipeline, input, options)
end

function Client:deletePipelineEndpoint(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeletePipelineEndpoint, input, options)
end

function Client:deleteResourcePolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteResourcePolicy, input, options)
end

function Client:getPipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetPipeline, input, options)
end

function Client:getPipelineBlueprint(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetPipelineBlueprint, input, options)
end

function Client:getPipelineChangeProgress(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetPipelineChangeProgress, input, options)
end

function Client:getResourcePolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetResourcePolicy, input, options)
end

function Client:listPipelineBlueprints(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPipelineBlueprints, input, options)
end

function Client:listPipelineEndpointConnections(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPipelineEndpointConnections, input, options)
end

function Client:listPipelineEndpoints(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPipelineEndpoints, input, options)
end

function Client:listPipelines(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListPipelines, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:putResourcePolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutResourcePolicy, input, options)
end

function Client:revokePipelineEndpointConnections(input, options)
    return self:invokeOperation(schemas.Service, schemas.RevokePipelineEndpointConnections, input, options)
end

function Client:startPipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.StartPipeline, input, options)
end

function Client:stopPipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.StopPipeline, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updatePipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdatePipeline, input, options)
end

function Client:validatePipeline(input, options)
    return self:invokeOperation(schemas.Service, schemas.ValidatePipeline, input, options)
end

return M
