local M = {}

M.ComplianceType = {
    Compliant = "COMPLIANT",
    Non_Compliant = "NON_COMPLIANT",
    Not_Applicable = "NOT_APPLICABLE",
    Insufficient_Data = "INSUFFICIENT_DATA",
}

M.ConformancePackComplianceType = {
    COMPLIANT = "COMPLIANT",
    NON_COMPLIANT = "NON_COMPLIANT",
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA",
}

M.AggregateConformancePackComplianceSummaryGroupKey = {
    ACCOUNT_ID = "ACCOUNT_ID",
    AWS_REGION = "AWS_REGION",
}

M.AggregatedSourceStatusType = {
    FAILED = "FAILED",
    SUCCEEDED = "SUCCEEDED",
    OUTDATED = "OUTDATED",
}

M.AggregatedSourceType = {
    ACCOUNT = "ACCOUNT",
    ORGANIZATION = "ORGANIZATION",
}

M.EvaluationMode = {
    DETECTIVE = "DETECTIVE",
    PROACTIVE = "PROACTIVE",
}

M.ResourceType = {
    CustomerGateway = "AWS::EC2::CustomerGateway",
    EIP = "AWS::EC2::EIP",
    Host = "AWS::EC2::Host",
    Instance = "AWS::EC2::Instance",
    InternetGateway = "AWS::EC2::InternetGateway",
    NetworkAcl = "AWS::EC2::NetworkAcl",
    NetworkInterface = "AWS::EC2::NetworkInterface",
    RouteTable = "AWS::EC2::RouteTable",
    SecurityGroup = "AWS::EC2::SecurityGroup",
    Subnet = "AWS::EC2::Subnet",
    Trail = "AWS::CloudTrail::Trail",
    Volume = "AWS::EC2::Volume",
    VPC = "AWS::EC2::VPC",
    VPNConnection = "AWS::EC2::VPNConnection",
    VPNGateway = "AWS::EC2::VPNGateway",
    RegisteredHAInstance = "AWS::EC2::RegisteredHAInstance",
    NatGateway = "AWS::EC2::NatGateway",
    EgressOnlyInternetGateway = "AWS::EC2::EgressOnlyInternetGateway",
    VPCEndpoint = "AWS::EC2::VPCEndpoint",
    VPCEndpointService = "AWS::EC2::VPCEndpointService",
    FlowLog = "AWS::EC2::FlowLog",
    VPCPeeringConnection = "AWS::EC2::VPCPeeringConnection",
    Domain = "AWS::Elasticsearch::Domain",
    Group = "AWS::IAM::Group",
    Policy = "AWS::IAM::Policy",
    Role = "AWS::IAM::Role",
    User = "AWS::IAM::User",
    LoadBalancerV2 = "AWS::ElasticLoadBalancingV2::LoadBalancer",
    Certificate = "AWS::ACM::Certificate",
    DBInstance = "AWS::RDS::DBInstance",
    DBSubnetGroup = "AWS::RDS::DBSubnetGroup",
    DBSecurityGroup = "AWS::RDS::DBSecurityGroup",
    DBSnapshot = "AWS::RDS::DBSnapshot",
    DBCluster = "AWS::RDS::DBCluster",
    DBClusterSnapshot = "AWS::RDS::DBClusterSnapshot",
    EventSubscription = "AWS::RDS::EventSubscription",
    Bucket = "AWS::S3::Bucket",
    AccountPublicAccessBlock = "AWS::S3::AccountPublicAccessBlock",
    Cluster = "AWS::Redshift::Cluster",
    ClusterSnapshot = "AWS::Redshift::ClusterSnapshot",
    ClusterParameterGroup = "AWS::Redshift::ClusterParameterGroup",
    ClusterSecurityGroup = "AWS::Redshift::ClusterSecurityGroup",
    ClusterSubnetGroup = "AWS::Redshift::ClusterSubnetGroup",
    RedshiftEventSubscription = "AWS::Redshift::EventSubscription",
    ManagedInstanceInventory = "AWS::SSM::ManagedInstanceInventory",
    Alarm = "AWS::CloudWatch::Alarm",
    Stack = "AWS::CloudFormation::Stack",
    LoadBalancer = "AWS::ElasticLoadBalancing::LoadBalancer",
    AutoScalingGroup = "AWS::AutoScaling::AutoScalingGroup",
    LaunchConfiguration = "AWS::AutoScaling::LaunchConfiguration",
    ScalingPolicy = "AWS::AutoScaling::ScalingPolicy",
    ScheduledAction = "AWS::AutoScaling::ScheduledAction",
    Table = "AWS::DynamoDB::Table",
    Project = "AWS::CodeBuild::Project",
    RateBasedRule = "AWS::WAF::RateBasedRule",
    Rule = "AWS::WAF::Rule",
    RuleGroup = "AWS::WAF::RuleGroup",
    WebACL = "AWS::WAF::WebACL",
    RegionalRateBasedRule = "AWS::WAFRegional::RateBasedRule",
    RegionalRule = "AWS::WAFRegional::Rule",
    RegionalRuleGroup = "AWS::WAFRegional::RuleGroup",
    RegionalWebACL = "AWS::WAFRegional::WebACL",
    Distribution = "AWS::CloudFront::Distribution",
    StreamingDistribution = "AWS::CloudFront::StreamingDistribution",
    Function = "AWS::Lambda::Function",
    NetworkFirewallFirewall = "AWS::NetworkFirewall::Firewall",
    NetworkFirewallFirewallPolicy = "AWS::NetworkFirewall::FirewallPolicy",
    NetworkFirewallRuleGroup = "AWS::NetworkFirewall::RuleGroup",
    Application = "AWS::ElasticBeanstalk::Application",
    ApplicationVersion = "AWS::ElasticBeanstalk::ApplicationVersion",
    Environment = "AWS::ElasticBeanstalk::Environment",
    WebACLV2 = "AWS::WAFv2::WebACL",
    RuleGroupV2 = "AWS::WAFv2::RuleGroup",
    IPSetV2 = "AWS::WAFv2::IPSet",
    RegexPatternSetV2 = "AWS::WAFv2::RegexPatternSet",
    ManagedRuleSetV2 = "AWS::WAFv2::ManagedRuleSet",
    EncryptionConfig = "AWS::XRay::EncryptionConfig",
    AssociationCompliance = "AWS::SSM::AssociationCompliance",
    PatchCompliance = "AWS::SSM::PatchCompliance",
    Protection = "AWS::Shield::Protection",
    RegionalProtection = "AWS::ShieldRegional::Protection",
    ConformancePackCompliance = "AWS::Config::ConformancePackCompliance",
    ResourceCompliance = "AWS::Config::ResourceCompliance",
    Stage = "AWS::ApiGateway::Stage",
    RestApi = "AWS::ApiGateway::RestApi",
    StageV2 = "AWS::ApiGatewayV2::Stage",
    Api = "AWS::ApiGatewayV2::Api",
    Pipeline = "AWS::CodePipeline::Pipeline",
    CloudFormationProvisionedProduct = "AWS::ServiceCatalog::CloudFormationProvisionedProduct",
    CloudFormationProduct = "AWS::ServiceCatalog::CloudFormationProduct",
    Portfolio = "AWS::ServiceCatalog::Portfolio",
    Queue = "AWS::SQS::Queue",
    Key = "AWS::KMS::Key",
    QLDBLedger = "AWS::QLDB::Ledger",
    Secret = "AWS::SecretsManager::Secret",
    Topic = "AWS::SNS::Topic",
    FileData = "AWS::SSM::FileData",
    BackupPlan = "AWS::Backup::BackupPlan",
    BackupSelection = "AWS::Backup::BackupSelection",
    BackupVault = "AWS::Backup::BackupVault",
    BackupRecoveryPoint = "AWS::Backup::RecoveryPoint",
    ECRRepository = "AWS::ECR::Repository",
    ECSCluster = "AWS::ECS::Cluster",
    ECSService = "AWS::ECS::Service",
    ECSTaskDefinition = "AWS::ECS::TaskDefinition",
    EFSAccessPoint = "AWS::EFS::AccessPoint",
    EFSFileSystem = "AWS::EFS::FileSystem",
    EKSCluster = "AWS::EKS::Cluster",
    OpenSearchDomain = "AWS::OpenSearch::Domain",
    TransitGateway = "AWS::EC2::TransitGateway",
    KinesisStream = "AWS::Kinesis::Stream",
    KinesisStreamConsumer = "AWS::Kinesis::StreamConsumer",
    CodeDeployApplication = "AWS::CodeDeploy::Application",
    CodeDeployDeploymentConfig = "AWS::CodeDeploy::DeploymentConfig",
    CodeDeployDeploymentGroup = "AWS::CodeDeploy::DeploymentGroup",
    LaunchTemplate = "AWS::EC2::LaunchTemplate",
    ECRPublicRepository = "AWS::ECR::PublicRepository",
    GuardDutyDetector = "AWS::GuardDuty::Detector",
    EMRSecurityConfiguration = "AWS::EMR::SecurityConfiguration",
    SageMakerCodeRepository = "AWS::SageMaker::CodeRepository",
    Route53ResolverResolverEndpoint = "AWS::Route53Resolver::ResolverEndpoint",
    Route53ResolverResolverRule = "AWS::Route53Resolver::ResolverRule",
    Route53ResolverResolverRuleAssociation = "AWS::Route53Resolver::ResolverRuleAssociation",
    DMSReplicationSubnetGroup = "AWS::DMS::ReplicationSubnetGroup",
    DMSEventSubscription = "AWS::DMS::EventSubscription",
    MSKCluster = "AWS::MSK::Cluster",
    StepFunctionsActivity = "AWS::StepFunctions::Activity",
    WorkSpacesWorkspace = "AWS::WorkSpaces::Workspace",
    WorkSpacesConnectionAlias = "AWS::WorkSpaces::ConnectionAlias",
    SageMakerModel = "AWS::SageMaker::Model",
    ListenerV2 = "AWS::ElasticLoadBalancingV2::Listener",
    StepFunctionsStateMachine = "AWS::StepFunctions::StateMachine",
    BatchJobQueue = "AWS::Batch::JobQueue",
    BatchComputeEnvironment = "AWS::Batch::ComputeEnvironment",
    AccessAnalyzerAnalyzer = "AWS::AccessAnalyzer::Analyzer",
    AthenaWorkGroup = "AWS::Athena::WorkGroup",
    AthenaDataCatalog = "AWS::Athena::DataCatalog",
    DetectiveGraph = "AWS::Detective::Graph",
    GlobalAcceleratorAccelerator = "AWS::GlobalAccelerator::Accelerator",
    GlobalAcceleratorEndpointGroup = "AWS::GlobalAccelerator::EndpointGroup",
    GlobalAcceleratorListener = "AWS::GlobalAccelerator::Listener",
    TransitGatewayAttachment = "AWS::EC2::TransitGatewayAttachment",
    TransitGatewayRouteTable = "AWS::EC2::TransitGatewayRouteTable",
    DMSCertificate = "AWS::DMS::Certificate",
    AppConfigApplication = "AWS::AppConfig::Application",
    AppSyncGraphQLApi = "AWS::AppSync::GraphQLApi",
    DataSyncLocationSMB = "AWS::DataSync::LocationSMB",
    DataSyncLocationFSxLustre = "AWS::DataSync::LocationFSxLustre",
    DataSyncLocationS3 = "AWS::DataSync::LocationS3",
    DataSyncLocationEFS = "AWS::DataSync::LocationEFS",
    DataSyncTask = "AWS::DataSync::Task",
    DataSyncLocationNFS = "AWS::DataSync::LocationNFS",
    NetworkInsightsAccessScopeAnalysis = "AWS::EC2::NetworkInsightsAccessScopeAnalysis",
    EKSFargateProfile = "AWS::EKS::FargateProfile",
    GlueJob = "AWS::Glue::Job",
    GuardDutyThreatIntelSet = "AWS::GuardDuty::ThreatIntelSet",
    GuardDutyIPSet = "AWS::GuardDuty::IPSet",
    SageMakerWorkteam = "AWS::SageMaker::Workteam",
    SageMakerNotebookInstanceLifecycleConfig = "AWS::SageMaker::NotebookInstanceLifecycleConfig",
    ServiceDiscoveryService = "AWS::ServiceDiscovery::Service",
    ServiceDiscoveryPublicDnsNamespace = "AWS::ServiceDiscovery::PublicDnsNamespace",
    SESContactList = "AWS::SES::ContactList",
    SESConfigurationSet = "AWS::SES::ConfigurationSet",
    Route53HostedZone = "AWS::Route53::HostedZone",
    IoTEventsInput = "AWS::IoTEvents::Input",
    IoTEventsDetectorModel = "AWS::IoTEvents::DetectorModel",
    IoTEventsAlarmModel = "AWS::IoTEvents::AlarmModel",
    ServiceDiscoveryHttpNamespace = "AWS::ServiceDiscovery::HttpNamespace",
    EventsEventBus = "AWS::Events::EventBus",
    ImageBuilderContainerRecipe = "AWS::ImageBuilder::ContainerRecipe",
    ImageBuilderDistributionConfiguration = "AWS::ImageBuilder::DistributionConfiguration",
    ImageBuilderInfrastructureConfiguration = "AWS::ImageBuilder::InfrastructureConfiguration",
    DataSyncLocationObjectStorage = "AWS::DataSync::LocationObjectStorage",
    DataSyncLocationHDFS = "AWS::DataSync::LocationHDFS",
    GlueClassifier = "AWS::Glue::Classifier",
    Route53RecoveryReadinessCell = "AWS::Route53RecoveryReadiness::Cell",
    Route53RecoveryReadinessReadinessCheck = "AWS::Route53RecoveryReadiness::ReadinessCheck",
    ECRRegistryPolicy = "AWS::ECR::RegistryPolicy",
    BackupReportPlan = "AWS::Backup::ReportPlan",
    LightsailCertificate = "AWS::Lightsail::Certificate",
    RUMAppMonitor = "AWS::RUM::AppMonitor",
    EventsEndpoint = "AWS::Events::Endpoint",
    SESReceiptRuleSet = "AWS::SES::ReceiptRuleSet",
    EventsArchive = "AWS::Events::Archive",
    EventsApiDestination = "AWS::Events::ApiDestination",
    LightsailDisk = "AWS::Lightsail::Disk",
    FISExperimentTemplate = "AWS::FIS::ExperimentTemplate",
    DataSyncLocationFSxWindows = "AWS::DataSync::LocationFSxWindows",
    SESReceiptFilter = "AWS::SES::ReceiptFilter",
    GuardDutyFilter = "AWS::GuardDuty::Filter",
    SESTemplate = "AWS::SES::Template",
    AmazonMQBroker = "AWS::AmazonMQ::Broker",
    AppConfigEnvironment = "AWS::AppConfig::Environment",
    AppConfigConfigurationProfile = "AWS::AppConfig::ConfigurationProfile",
    Cloud9EnvironmentEC2 = "AWS::Cloud9::EnvironmentEC2",
    EventSchemasRegistry = "AWS::EventSchemas::Registry",
    EventSchemasRegistryPolicy = "AWS::EventSchemas::RegistryPolicy",
    EventSchemasDiscoverer = "AWS::EventSchemas::Discoverer",
    FraudDetectorLabel = "AWS::FraudDetector::Label",
    FraudDetectorEntityType = "AWS::FraudDetector::EntityType",
    FraudDetectorVariable = "AWS::FraudDetector::Variable",
    FraudDetectorOutcome = "AWS::FraudDetector::Outcome",
    IoTAuthorizer = "AWS::IoT::Authorizer",
    IoTSecurityProfile = "AWS::IoT::SecurityProfile",
    IoTRoleAlias = "AWS::IoT::RoleAlias",
    IoTDimension = "AWS::IoT::Dimension",
    IoTAnalyticsDatastore = "AWS::IoTAnalytics::Datastore",
    LightsailBucket = "AWS::Lightsail::Bucket",
    LightsailStaticIp = "AWS::Lightsail::StaticIp",
    MediaPackagePackagingGroup = "AWS::MediaPackage::PackagingGroup",
    Route53RecoveryReadinessRecoveryGroup = "AWS::Route53RecoveryReadiness::RecoveryGroup",
    ResilienceHubResiliencyPolicy = "AWS::ResilienceHub::ResiliencyPolicy",
    TransferWorkflow = "AWS::Transfer::Workflow",
    EKSIdentityProviderConfig = "AWS::EKS::IdentityProviderConfig",
    EKSAddon = "AWS::EKS::Addon",
    GlueMLTransform = "AWS::Glue::MLTransform",
    IoTPolicy = "AWS::IoT::Policy",
    IoTMitigationAction = "AWS::IoT::MitigationAction",
    IoTTwinMakerWorkspace = "AWS::IoTTwinMaker::Workspace",
    IoTTwinMakerEntity = "AWS::IoTTwinMaker::Entity",
    IoTAnalyticsDataset = "AWS::IoTAnalytics::Dataset",
    IoTAnalyticsPipeline = "AWS::IoTAnalytics::Pipeline",
    IoTAnalyticsChannel = "AWS::IoTAnalytics::Channel",
    IoTSiteWiseDashboard = "AWS::IoTSiteWise::Dashboard",
    IoTSiteWiseProject = "AWS::IoTSiteWise::Project",
    IoTSiteWisePortal = "AWS::IoTSiteWise::Portal",
    IoTSiteWiseAssetModel = "AWS::IoTSiteWise::AssetModel",
    IVSChannel = "AWS::IVS::Channel",
    IVSRecordingConfiguration = "AWS::IVS::RecordingConfiguration",
    IVSPlaybackKeyPair = "AWS::IVS::PlaybackKeyPair",
    KinesisAnalyticsV2Application = "AWS::KinesisAnalyticsV2::Application",
    RDSGlobalCluster = "AWS::RDS::GlobalCluster",
    S3MultiRegionAccessPoint = "AWS::S3::MultiRegionAccessPoint",
    DeviceFarmTestGridProject = "AWS::DeviceFarm::TestGridProject",
    BudgetsBudgetsAction = "AWS::Budgets::BudgetsAction",
    LexBot = "AWS::Lex::Bot",
    CodeGuruReviewerRepositoryAssociation = "AWS::CodeGuruReviewer::RepositoryAssociation",
    IoTCustomMetric = "AWS::IoT::CustomMetric",
    Route53ResolverFirewallDomainList = "AWS::Route53Resolver::FirewallDomainList",
    RoboMakerRobotApplicationVersion = "AWS::RoboMaker::RobotApplicationVersion",
    EC2TrafficMirrorSession = "AWS::EC2::TrafficMirrorSession",
    IoTSiteWiseGateway = "AWS::IoTSiteWise::Gateway",
    LexBotAlias = "AWS::Lex::BotAlias",
    LookoutMetricsAlert = "AWS::LookoutMetrics::Alert",
    IoTAccountAuditConfiguration = "AWS::IoT::AccountAuditConfiguration",
    EC2TrafficMirrorTarget = "AWS::EC2::TrafficMirrorTarget",
    S3StorageLens = "AWS::S3::StorageLens",
    IoTScheduledAudit = "AWS::IoT::ScheduledAudit",
    EventsConnection = "AWS::Events::Connection",
    EventSchemasSchema = "AWS::EventSchemas::Schema",
    MediaPackagePackagingConfiguration = "AWS::MediaPackage::PackagingConfiguration",
    KinesisVideoSignalingChannel = "AWS::KinesisVideo::SignalingChannel",
    AppStreamDirectoryConfig = "AWS::AppStream::DirectoryConfig",
    LookoutVisionProject = "AWS::LookoutVision::Project",
    Route53RecoveryControlCluster = "AWS::Route53RecoveryControl::Cluster",
    Route53RecoveryControlSafetyRule = "AWS::Route53RecoveryControl::SafetyRule",
    Route53RecoveryControlControlPanel = "AWS::Route53RecoveryControl::ControlPanel",
    Route53RecoveryControlRoutingControl = "AWS::Route53RecoveryControl::RoutingControl",
    Route53RecoveryReadinessResourceSet = "AWS::Route53RecoveryReadiness::ResourceSet",
    RoboMakerSimulationApplication = "AWS::RoboMaker::SimulationApplication",
    RoboMakerRobotApplication = "AWS::RoboMaker::RobotApplication",
    HealthLakeFHIRDatastore = "AWS::HealthLake::FHIRDatastore",
    PinpointSegment = "AWS::Pinpoint::Segment",
    PinpointApplicationSettings = "AWS::Pinpoint::ApplicationSettings",
    EventsRule = "AWS::Events::Rule",
    EC2DHCPOptions = "AWS::EC2::DHCPOptions",
    EC2NetworkInsightsPath = "AWS::EC2::NetworkInsightsPath",
    EC2TrafficMirrorFilter = "AWS::EC2::TrafficMirrorFilter",
    EC2IPAM = "AWS::EC2::IPAM",
    IoTTwinMakerScene = "AWS::IoTTwinMaker::Scene",
    NetworkManagerTransitGatewayRegistration = "AWS::NetworkManager::TransitGatewayRegistration",
    CustomerProfilesDomain = "AWS::CustomerProfiles::Domain",
    AutoScalingWarmPool = "AWS::AutoScaling::WarmPool",
    ConnectPhoneNumber = "AWS::Connect::PhoneNumber",
    AppConfigDeploymentStrategy = "AWS::AppConfig::DeploymentStrategy",
    AppFlowFlow = "AWS::AppFlow::Flow",
    AuditManagerAssessment = "AWS::AuditManager::Assessment",
    CloudWatchMetricStream = "AWS::CloudWatch::MetricStream",
    DeviceFarmInstanceProfile = "AWS::DeviceFarm::InstanceProfile",
    DeviceFarmProject = "AWS::DeviceFarm::Project",
    EC2EC2Fleet = "AWS::EC2::EC2Fleet",
    EC2SubnetRouteTableAssociation = "AWS::EC2::SubnetRouteTableAssociation",
    ECRPullThroughCacheRule = "AWS::ECR::PullThroughCacheRule",
    GroundStationConfig = "AWS::GroundStation::Config",
    ImageBuilderImagePipeline = "AWS::ImageBuilder::ImagePipeline",
    IoTFleetMetric = "AWS::IoT::FleetMetric",
    IoTWirelessServiceProfile = "AWS::IoTWireless::ServiceProfile",
    NetworkManagerDevice = "AWS::NetworkManager::Device",
    NetworkManagerGlobalNetwork = "AWS::NetworkManager::GlobalNetwork",
    NetworkManagerLink = "AWS::NetworkManager::Link",
    NetworkManagerSite = "AWS::NetworkManager::Site",
    PanoramaPackage = "AWS::Panorama::Package",
    PinpointApp = "AWS::Pinpoint::App",
    RedshiftScheduledAction = "AWS::Redshift::ScheduledAction",
    Route53ResolverFirewallRuleGroupAssociation = "AWS::Route53Resolver::FirewallRuleGroupAssociation",
    SageMakerAppImageConfig = "AWS::SageMaker::AppImageConfig",
    SageMakerImage = "AWS::SageMaker::Image",
    ECSTaskSet = "AWS::ECS::TaskSet",
    CassandraKeyspace = "AWS::Cassandra::Keyspace",
    SignerSigningProfile = "AWS::Signer::SigningProfile",
    AmplifyApp = "AWS::Amplify::App",
    AppMeshVirtualNode = "AWS::AppMesh::VirtualNode",
    AppMeshVirtualService = "AWS::AppMesh::VirtualService",
    AppRunnerVpcConnector = "AWS::AppRunner::VpcConnector",
    AppStreamApplication = "AWS::AppStream::Application",
    CodeArtifactRepository = "AWS::CodeArtifact::Repository",
    EC2PrefixList = "AWS::EC2::PrefixList",
    EC2SpotFleet = "AWS::EC2::SpotFleet",
    EvidentlyProject = "AWS::Evidently::Project",
    ForecastDataset = "AWS::Forecast::Dataset",
    IAMSAMLProvider = "AWS::IAM::SAMLProvider",
    IAMServerCertificate = "AWS::IAM::ServerCertificate",
    PinpointCampaign = "AWS::Pinpoint::Campaign",
    PinpointInAppTemplate = "AWS::Pinpoint::InAppTemplate",
    SageMakerDomain = "AWS::SageMaker::Domain",
    TransferAgreement = "AWS::Transfer::Agreement",
    TransferConnector = "AWS::Transfer::Connector",
    KinesisFirehoseDeliveryStream = "AWS::KinesisFirehose::DeliveryStream",
    AmplifyBranch = "AWS::Amplify::Branch",
    AppIntegrationsEventIntegration = "AWS::AppIntegrations::EventIntegration",
    AppMeshRoute = "AWS::AppMesh::Route",
    AthenaPreparedStatement = "AWS::Athena::PreparedStatement",
    EC2IPAMScope = "AWS::EC2::IPAMScope",
    EvidentlyLaunch = "AWS::Evidently::Launch",
    ForecastDatasetGroup = "AWS::Forecast::DatasetGroup",
    GreengrassV2ComponentVersion = "AWS::GreengrassV2::ComponentVersion",
    GroundStationMissionProfile = "AWS::GroundStation::MissionProfile",
    MediaConnectFlowEntitlement = "AWS::MediaConnect::FlowEntitlement",
    MediaConnectFlowVpcInterface = "AWS::MediaConnect::FlowVpcInterface",
    MediaTailorPlaybackConfiguration = "AWS::MediaTailor::PlaybackConfiguration",
    MSKConfiguration = "AWS::MSK::Configuration",
    PersonalizeDataset = "AWS::Personalize::Dataset",
    PersonalizeSchema = "AWS::Personalize::Schema",
    PersonalizeSolution = "AWS::Personalize::Solution",
    PinpointEmailTemplate = "AWS::Pinpoint::EmailTemplate",
    PinpointEventStream = "AWS::Pinpoint::EventStream",
    ResilienceHubApp = "AWS::ResilienceHub::App",
    ACMPCACertificateAuthority = "AWS::ACMPCA::CertificateAuthority",
    AppConfigHostedConfigurationVersion = "AWS::AppConfig::HostedConfigurationVersion",
    AppMeshVirtualGateway = "AWS::AppMesh::VirtualGateway",
    AppMeshVirtualRouter = "AWS::AppMesh::VirtualRouter",
    AppRunnerService = "AWS::AppRunner::Service",
    CustomerProfilesObjectType = "AWS::CustomerProfiles::ObjectType",
    DMSEndpoint = "AWS::DMS::Endpoint",
    EC2CapacityReservation = "AWS::EC2::CapacityReservation",
    EC2ClientVpnEndpoint = "AWS::EC2::ClientVpnEndpoint",
    KendraIndex = "AWS::Kendra::Index",
    KinesisVideoStream = "AWS::KinesisVideo::Stream",
    LogsDestination = "AWS::Logs::Destination",
    PinpointEmailChannel = "AWS::Pinpoint::EmailChannel",
    S3AccessPoint = "AWS::S3::AccessPoint",
    NetworkManagerCustomerGatewayAssociation = "AWS::NetworkManager::CustomerGatewayAssociation",
    NetworkManagerLinkAssociation = "AWS::NetworkManager::LinkAssociation",
    IoTWirelessMulticastGroup = "AWS::IoTWireless::MulticastGroup",
    PersonalizeDatasetGroup = "AWS::Personalize::DatasetGroup",
    IoTTwinMakerComponentType = "AWS::IoTTwinMaker::ComponentType",
    CodeBuildReportGroup = "AWS::CodeBuild::ReportGroup",
    SageMakerFeatureGroup = "AWS::SageMaker::FeatureGroup",
    MSKBatchScramSecret = "AWS::MSK::BatchScramSecret",
    AppStreamStack = "AWS::AppStream::Stack",
    IoTJobTemplate = "AWS::IoT::JobTemplate",
    IoTWirelessFuotaTask = "AWS::IoTWireless::FuotaTask",
    IoTProvisioningTemplate = "AWS::IoT::ProvisioningTemplate",
    InspectorV2Filter = "AWS::InspectorV2::Filter",
    Route53ResolverResolverQueryLoggingConfigAssociation = "AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation",
    ServiceDiscoveryInstance = "AWS::ServiceDiscovery::Instance",
    TransferCertificate = "AWS::Transfer::Certificate",
    MediaConnectFlowSource = "AWS::MediaConnect::FlowSource",
    APSRuleGroupsNamespace = "AWS::APS::RuleGroupsNamespace",
    CodeGuruProfilerProfilingGroup = "AWS::CodeGuruProfiler::ProfilingGroup",
    Route53ResolverResolverQueryLoggingConfig = "AWS::Route53Resolver::ResolverQueryLoggingConfig",
    BatchSchedulingPolicy = "AWS::Batch::SchedulingPolicy",
    ACMPCACertificateAuthorityActivation = "AWS::ACMPCA::CertificateAuthorityActivation",
    AppMeshGatewayRoute = "AWS::AppMesh::GatewayRoute",
    AppMeshMesh = "AWS::AppMesh::Mesh",
    ConnectInstance = "AWS::Connect::Instance",
    ConnectQuickConnect = "AWS::Connect::QuickConnect",
    EC2CarrierGateway = "AWS::EC2::CarrierGateway",
    EC2IPAMPool = "AWS::EC2::IPAMPool",
    EC2TransitGatewayConnect = "AWS::EC2::TransitGatewayConnect",
    EC2TransitGatewayMulticastDomain = "AWS::EC2::TransitGatewayMulticastDomain",
    ECSCapacityProvider = "AWS::ECS::CapacityProvider",
    IAMInstanceProfile = "AWS::IAM::InstanceProfile",
    IoTCACertificate = "AWS::IoT::CACertificate",
    IoTTwinMakerSyncJob = "AWS::IoTTwinMaker::SyncJob",
    KafkaConnectConnector = "AWS::KafkaConnect::Connector",
    LambdaCodeSigningConfig = "AWS::Lambda::CodeSigningConfig",
    NetworkManagerConnectPeer = "AWS::NetworkManager::ConnectPeer",
    ResourceExplorer2Index = "AWS::ResourceExplorer2::Index",
    AppStreamFleet = "AWS::AppStream::Fleet",
    CognitoUserPool = "AWS::Cognito::UserPool",
    CognitoUserPoolClient = "AWS::Cognito::UserPoolClient",
    CognitoUserPoolGroup = "AWS::Cognito::UserPoolGroup",
    EC2NetworkInsightsAccessScope = "AWS::EC2::NetworkInsightsAccessScope",
    EC2NetworkInsightsAnalysis = "AWS::EC2::NetworkInsightsAnalysis",
    GrafanaWorkspace = "AWS::Grafana::Workspace",
    GroundStationDataflowEndpointGroup = "AWS::GroundStation::DataflowEndpointGroup",
    ImageBuilderImageRecipe = "AWS::ImageBuilder::ImageRecipe",
    KMSAlias = "AWS::KMS::Alias",
    M2Environment = "AWS::M2::Environment",
    QuickSightDataSource = "AWS::QuickSight::DataSource",
    QuickSightTemplate = "AWS::QuickSight::Template",
    QuickSightTheme = "AWS::QuickSight::Theme",
    RDSOptionGroup = "AWS::RDS::OptionGroup",
    RedshiftEndpointAccess = "AWS::Redshift::EndpointAccess",
    Route53ResolverFirewallRuleGroup = "AWS::Route53Resolver::FirewallRuleGroup",
    SSMDocument = "AWS::SSM::Document",
    AppConfigExtensionAssociation = "AWS::AppConfig::ExtensionAssociation",
    AppIntegrationsApplication = "AWS::AppIntegrations::Application",
    AppSyncApiCache = "AWS::AppSync::ApiCache",
    BedrockGuardrail = "AWS::Bedrock::Guardrail",
    BedrockKnowledgeBase = "AWS::Bedrock::KnowledgeBase",
    CognitoIdentityPool = "AWS::Cognito::IdentityPool",
    ConnectRule = "AWS::Connect::Rule",
    ConnectUser = "AWS::Connect::User",
    EC2ClientVpnTargetNetworkAssociation = "AWS::EC2::ClientVpnTargetNetworkAssociation",
    EC2EIPAssociation = "AWS::EC2::EIPAssociation",
    EC2IPAMResourceDiscovery = "AWS::EC2::IPAMResourceDiscovery",
    EC2IPAMResourceDiscoveryAssociation = "AWS::EC2::IPAMResourceDiscoveryAssociation",
    EC2InstanceConnectEndpoint = "AWS::EC2::InstanceConnectEndpoint",
    EC2SnapshotBlockPublicAccess = "AWS::EC2::SnapshotBlockPublicAccess",
    EC2VPCBlockPublicAccessExclusion = "AWS::EC2::VPCBlockPublicAccessExclusion",
    EC2VPCBlockPublicAccessOptions = "AWS::EC2::VPCBlockPublicAccessOptions",
    EC2VPCEndpointConnectionNotification = "AWS::EC2::VPCEndpointConnectionNotification",
    EC2VPNConnectionRoute = "AWS::EC2::VPNConnectionRoute",
    EvidentlySegment = "AWS::Evidently::Segment",
    IAMOIDCProvider = "AWS::IAM::OIDCProvider",
    InspectorV2Activation = "AWS::InspectorV2::Activation",
    MSKClusterPolicy = "AWS::MSK::ClusterPolicy",
    MSKVpcConnection = "AWS::MSK::VpcConnection",
    MediaConnectGateway = "AWS::MediaConnect::Gateway",
    MemoryDBSubnetGroup = "AWS::MemoryDB::SubnetGroup",
    OpenSearchServerlessCollection = "AWS::OpenSearchServerless::Collection",
    OpenSearchServerlessVpcEndpoint = "AWS::OpenSearchServerless::VpcEndpoint",
    RedshiftEndpointAuthorization = "AWS::Redshift::EndpointAuthorization",
    Route53ProfilesProfile = "AWS::Route53Profiles::Profile",
    S3StorageLensGroup = "AWS::S3::StorageLensGroup",
    S3ExpressBucketPolicy = "AWS::S3Express::BucketPolicy",
    S3ExpressDirectoryBucket = "AWS::S3Express::DirectoryBucket",
    SageMakerInferenceExperiment = "AWS::SageMaker::InferenceExperiment",
    SecurityHubStandard = "AWS::SecurityHub::Standard",
    TransferProfile = "AWS::Transfer::Profile",
    CloudFormationStackSet = "AWS::CloudFormation::StackSet",
    MediaPackageV2Channel = "AWS::MediaPackageV2::Channel",
    S3AccessGrantsLocation = "AWS::S3::AccessGrantsLocation",
    S3AccessGrant = "AWS::S3::AccessGrant",
    S3AccessGrantsInstance = "AWS::S3::AccessGrantsInstance",
    EMRServerlessApplication = "AWS::EMRServerless::Application",
    ConfigAggregationAuthorization = "AWS::Config::AggregationAuthorization",
    BedrockApplicationInferenceProfile = "AWS::Bedrock::ApplicationInferenceProfile",
    ApiGatewayV2Integration = "AWS::ApiGatewayV2::Integration",
    SageMakerMlflowTrackingServer = "AWS::SageMaker::MlflowTrackingServer",
    SageMakerModelBiasJobDefinition = "AWS::SageMaker::ModelBiasJobDefinition",
    SecretsManagerRotationSchedule = "AWS::SecretsManager::RotationSchedule",
    DeadlineQueueFleetAssociation = "AWS::Deadline::QueueFleetAssociation",
    ECRRepositoryCreationTemplate = "AWS::ECR::RepositoryCreationTemplate",
    CloudFormationLambdaHook = "AWS::CloudFormation::LambdaHook",
    EC2SubnetNetworkAclAssociation = "AWS::EC2::SubnetNetworkAclAssociation",
    ApiGatewayUsagePlan = "AWS::ApiGateway::UsagePlan",
    AppConfigExtension = "AWS::AppConfig::Extension",
    DeadlineFleet = "AWS::Deadline::Fleet",
    EMRStudio = "AWS::EMR::Studio",
    S3TablesTableBucket = "AWS::S3Tables::TableBucket",
    CloudFrontRealtimeLogConfig = "AWS::CloudFront::RealtimeLogConfig",
    BackupGatewayHypervisor = "AWS::BackupGateway::Hypervisor",
    BCMDataExportsExport = "AWS::BCMDataExports::Export",
    CloudFormationGuardHook = "AWS::CloudFormation::GuardHook",
    CloudFrontPublicKey = "AWS::CloudFront::PublicKey",
    CloudTrailEventDataStore = "AWS::CloudTrail::EventDataStore",
    EntityResolutionIdMappingWorkflow = "AWS::EntityResolution::IdMappingWorkflow",
    EntityResolutionSchemaMapping = "AWS::EntityResolution::SchemaMapping",
    IoTDomainConfiguration = "AWS::IoT::DomainConfiguration",
    PCAConnectorADDirectoryRegistration = "AWS::PCAConnectorAD::DirectoryRegistration",
    RDSIntegration = "AWS::RDS::Integration",
    ConfigConformancePack = "AWS::Config::ConformancePack",
    RolesAnywhereProfile = "AWS::RolesAnywhere::Profile",
    CodeArtifactDomain = "AWS::CodeArtifact::Domain",
    BackupRestoreTestingPlan = "AWS::Backup::RestoreTestingPlan",
    ConfigStoredQuery = "AWS::Config::StoredQuery",
    SageMakerDataQualityJobDefinition = "AWS::SageMaker::DataQualityJobDefinition",
    SageMakerModelExplainabilityJobDefinition = "AWS::SageMaker::ModelExplainabilityJobDefinition",
    SageMakerModelQualityJobDefinition = "AWS::SageMaker::ModelQualityJobDefinition",
    SageMakerStudioLifecycleConfig = "AWS::SageMaker::StudioLifecycleConfig",
    SESDedicatedIpPool = "AWS::SES::DedicatedIpPool",
    SESMailManagerTrafficPolicy = "AWS::SES::MailManagerTrafficPolicy",
    SSMResourceDataSync = "AWS::SSM::ResourceDataSync",
    BedrockAgentCoreRuntime = "AWS::BedrockAgentCore::Runtime",
    BedrockAgentCoreBrowserCustom = "AWS::BedrockAgentCore::BrowserCustom",
    ElasticLoadBalancingV2TargetGroup = "AWS::ElasticLoadBalancingV2::TargetGroup",
    EMRContainersVirtualCluster = "AWS::EMRContainers::VirtualCluster",
    EntityResolutionMatchingWorkflow = "AWS::EntityResolution::MatchingWorkflow",
    IoTCoreDeviceAdvisorSuiteDefinition = "AWS::IoTCoreDeviceAdvisor::SuiteDefinition",
    EC2SecurityGroupVpcAssociation = "AWS::EC2::SecurityGroupVpcAssociation",
    EC2VerifiedAccessInstance = "AWS::EC2::VerifiedAccessInstance",
    KafkaConnectCustomPlugin = "AWS::KafkaConnect::CustomPlugin",
    NetworkManagerTransitGatewayPeering = "AWS::NetworkManager::TransitGatewayPeering",
    OpenSearchServerlessSecurityConfig = "AWS::OpenSearchServerless::SecurityConfig",
    RedshiftIntegration = "AWS::Redshift::Integration",
    RolesAnywhereTrustAnchor = "AWS::RolesAnywhere::TrustAnchor",
    Route53ProfilesProfileAssociation = "AWS::Route53Profiles::ProfileAssociation",
    SSMIncidentsResponsePlan = "AWS::SSMIncidents::ResponsePlan",
    TransferServer = "AWS::Transfer::Server",
    GlueDatabase = "AWS::Glue::Database",
    OrganizationsOrganizationalUnit = "AWS::Organizations::OrganizationalUnit",
    EC2IPAMPoolCidr = "AWS::EC2::IPAMPoolCidr",
    EC2VPCGatewayAttachment = "AWS::EC2::VPCGatewayAttachment",
    BedrockPrompt = "AWS::Bedrock::Prompt",
    ComprehendFlywheel = "AWS::Comprehend::Flywheel",
    DataSyncAgent = "AWS::DataSync::Agent",
    MediaTailorLiveSource = "AWS::MediaTailor::LiveSource",
    MSKServerlessCluster = "AWS::MSK::ServerlessCluster",
    IoTSiteWiseAsset = "AWS::IoTSiteWise::Asset",
    B2BICapability = "AWS::B2BI::Capability",
    CloudFrontKeyValueStore = "AWS::CloudFront::KeyValueStore",
    DeadlineMonitor = "AWS::Deadline::Monitor",
    GuardDutyMalwareProtectionPlan = "AWS::GuardDuty::MalwareProtectionPlan",
    LocationAPIKey = "AWS::Location::APIKey",
    MediaPackageV2OriginEndpoint = "AWS::MediaPackageV2::OriginEndpoint",
    PCAConnectorADConnector = "AWS::PCAConnectorAD::Connector",
    S3TablesTableBucketPolicy = "AWS::S3Tables::TableBucketPolicy",
    SecretsManagerResourcePolicy = "AWS::SecretsManager::ResourcePolicy",
    SSMContactsContact = "AWS::SSMContacts::Contact",
    IoTThingGroup = "AWS::IoT::ThingGroup",
    ImageBuilderLifecyclePolicy = "AWS::ImageBuilder::LifecyclePolicy",
    GameLiftBuild = "AWS::GameLift::Build",
    ECRReplicationConfiguration = "AWS::ECR::ReplicationConfiguration",
    EC2SubnetCidrBlock = "AWS::EC2::SubnetCidrBlock",
    ConnectSecurityProfile = "AWS::Connect::SecurityProfile",
    CleanRoomsMLTrainingDataset = "AWS::CleanRoomsML::TrainingDataset",
    AppStreamAppBlockBuilder = "AWS::AppStream::AppBlockBuilder",
    Route53DNSSEC = "AWS::Route53::DNSSEC",
    SageMakerUserProfile = "AWS::SageMaker::UserProfile",
    ApiGatewayMethod = "AWS::ApiGateway::Method",
}

M.AggregatorFilterType = {
    INCLUDE = "INCLUDE",
}

M.RecordingStrategyType = {
    ALL_SUPPORTED_RESOURCE_TYPES = "ALL_SUPPORTED_RESOURCE_TYPES",
    INCLUSION_BY_RESOURCE_TYPES = "INCLUSION_BY_RESOURCE_TYPES",
    EXCLUSION_BY_RESOURCE_TYPES = "EXCLUSION_BY_RESOURCE_TYPES",
}

M.RecordingFrequency = {
    CONTINUOUS = "CONTINUOUS",
    DAILY = "DAILY",
}

M.RecordingScope = {
    INTERNAL = "INTERNAL",
    PAID = "PAID",
}

M.ConfigurationItemStatus = {
    OK = "OK",
    ResourceDiscovered = "ResourceDiscovered",
    ResourceNotRecorded = "ResourceNotRecorded",
    ResourceDeleted = "ResourceDeleted",
    ResourceDeletedNotRecorded = "ResourceDeletedNotRecorded",
}

M.ChronologicalOrder = {
    Reverse = "Reverse",
    Forward = "Forward",
}

M.DeliveryStatus = {
    Success = "Success",
    Failure = "Failure",
    Not_Applicable = "Not_Applicable",
}

M.ConfigRuleState = {
    ACTIVE = "ACTIVE",
    DELETING = "DELETING",
    DELETING_RESULTS = "DELETING_RESULTS",
    EVALUATING = "EVALUATING",
}

M.MaximumExecutionFrequency = {
    One_Hour = "One_Hour",
    Three_Hours = "Three_Hours",
    Six_Hours = "Six_Hours",
    Twelve_Hours = "Twelve_Hours",
    TwentyFour_Hours = "TwentyFour_Hours",
}

M.Owner = {
    Custom_Lambda = "CUSTOM_LAMBDA",
    Aws = "AWS",
    Custom_Policy = "CUSTOM_POLICY",
}

M.EventSource = {
    Aws_Config = "aws.config",
}

M.MessageType = {
    ConfigurationItemChangeNotification = "ConfigurationItemChangeNotification",
    ConfigurationSnapshotDeliveryCompleted = "ConfigurationSnapshotDeliveryCompleted",
    ScheduledNotification = "ScheduledNotification",
    OversizedConfigurationItemChangeNotification = "OversizedConfigurationItemChangeNotification",
}

M.ConfigRuleComplianceSummaryGroupKey = {
    ACCOUNT_ID = "ACCOUNT_ID",
    AWS_REGION = "AWS_REGION",
}

M.ConfigurationRecorderFilterName = {
    RecordingScope = "recordingScope",
}

M.RecorderStatus = {
    Pending = "Pending",
    Success = "Success",
    Failure = "Failure",
    NotApplicable = "NotApplicable",
}

M.ConformancePackState = {
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_COMPLETE = "CREATE_COMPLETE",
    CREATE_FAILED = "CREATE_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    DELETE_FAILED = "DELETE_FAILED",
}

M.OrganizationConfigRuleTriggerTypeNoSN = {
    CONFIGURATION_ITEM_CHANGE_NOTIFICATION = "ConfigurationItemChangeNotification",
    OVERSIZED_CONFIGURATION_ITEM_CHANGE_NOTIFCATION = "OversizedConfigurationItemChangeNotification",
}

M.OrganizationConfigRuleTriggerType = {
    CONFIGURATION_ITEM_CHANGE_NOTIFICATION = "ConfigurationItemChangeNotification",
    OVERSIZED_CONFIGURATION_ITEM_CHANGE_NOTIFCATION = "OversizedConfigurationItemChangeNotification",
    SCHEDULED_NOTIFICATION = "ScheduledNotification",
}

M.OrganizationRuleStatus = {
    CREATE_SUCCESSFUL = "CREATE_SUCCESSFUL",
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_FAILED = "CREATE_FAILED",
    DELETE_SUCCESSFUL = "DELETE_SUCCESSFUL",
    DELETE_FAILED = "DELETE_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    UPDATE_SUCCESSFUL = "UPDATE_SUCCESSFUL",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.OrganizationResourceStatus = {
    CREATE_SUCCESSFUL = "CREATE_SUCCESSFUL",
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_FAILED = "CREATE_FAILED",
    DELETE_SUCCESSFUL = "DELETE_SUCCESSFUL",
    DELETE_FAILED = "DELETE_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    UPDATE_SUCCESSFUL = "UPDATE_SUCCESSFUL",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.ResourceValueType = {
    RESOURCE_ID = "RESOURCE_ID",
}

M.RemediationTargetType = {
    SSM_DOCUMENT = "SSM_DOCUMENT",
}

M.RemediationExecutionState = {
    QUEUED = "QUEUED",
    IN_PROGRESS = "IN_PROGRESS",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    UNKNOWN = "UNKNOWN",
}

M.RemediationExecutionStepState = {
    SUCCEEDED = "SUCCEEDED",
    PENDING = "PENDING",
    FAILED = "FAILED",
    IN_PROGRESS = "IN_PROGRESS",
    EXITED = "EXITED",
    UNKNOWN = "UNKNOWN",
}

M.ResourceEvaluationStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    FAILED = "FAILED",
    SUCCEEDED = "SUCCEEDED",
}

M.ResourceCountGroupKey = {
    RESOURCE_TYPE = "RESOURCE_TYPE",
    ACCOUNT_ID = "ACCOUNT_ID",
    AWS_REGION = "AWS_REGION",
}

M.MemberAccountRuleStatus = {
    CREATE_SUCCESSFUL = "CREATE_SUCCESSFUL",
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_FAILED = "CREATE_FAILED",
    DELETE_SUCCESSFUL = "DELETE_SUCCESSFUL",
    DELETE_FAILED = "DELETE_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    UPDATE_SUCCESSFUL = "UPDATE_SUCCESSFUL",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.OrganizationResourceDetailedStatus = {
    CREATE_SUCCESSFUL = "CREATE_SUCCESSFUL",
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS",
    CREATE_FAILED = "CREATE_FAILED",
    DELETE_SUCCESSFUL = "DELETE_SUCCESSFUL",
    DELETE_FAILED = "DELETE_FAILED",
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS",
    UPDATE_SUCCESSFUL = "UPDATE_SUCCESSFUL",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    UPDATE_FAILED = "UPDATE_FAILED",
}

M.ResourceConfigurationSchemaType = {
    CFN_RESOURCE_SCHEMA = "CFN_RESOURCE_SCHEMA",
}

M.SortBy = {
    SCORE = "SCORE",
}

M.SortOrder = {
    ASCENDING = "ASCENDING",
    DESCENDING = "DESCENDING",
}

return M
