-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.ExecutionAction = {
    ACTIVATE = "activate",
    DEACTIVATE = "deactivate",
    POST_RECOVERY = "postRecovery",
}

M.ExecutionState = {
    IN_PROGRESS = "inProgress",
    PAUSED_BY_FAILED_STEP = "pausedByFailedStep",
    PAUSED_BY_OPERATOR = "pausedByOperator",
    COMPLETED = "completed",
    COMPLETED_WITH_EXCEPTIONS = "completedWithExceptions",
    CANCELLED = "canceled",
    PLAN_EXECUTION_TIMED_OUT = "planExecutionTimedOut",
    PENDING_MANUAL_APPROVAL = "pendingManualApproval",
    FAILED = "failed",
    PENDING = "pending",
    COMPLETED_MONITORING_APPLICATION_HEALTH = "completedMonitoringApplicationHealth",
}

M.ExecutionMode = {
    GRACEFUL = "graceful",
    UNGRACEFUL = "ungraceful",
}

M.RecoveryApproach = {
    ACTIVE_ACTIVE = "activeActive",
    ACTIVE_PASSIVE = "activePassive",
}

M.AlarmCondition = {
    RED = "red",
    GREEN = "green",
}

M.AlarmType = {
    APPLICATION_HEALTH = "applicationHealth",
    TRIGGER = "trigger",
}

M.Approval = {
    APPROVE = "approve",
    DECLINE = "decline",
}

M.EvaluationStatus = {
    PASSED = "passed",
    ACTION_REQUIRED = "actionRequired",
    PENDING_EVALUATION = "pendingEvaluation",
    UNKNOWN = "unknown",
}

M.ResourceWarningStatus = {
    ACTIVE = "active",
    RESOLVED = "resolved",
}

M.FailedReportErrorCode = {
    INSUFFICIENT_PERMISSIONS = "insufficientPermissions",
    INVALID_RESOURCE = "invalidResource",
    CONFIGURATION_ERROR = "configurationError",
}

M.WorkflowTargetAction = {
    ACTIVATE = "activate",
    DEACTIVATE = "deactivate",
    POST_RECOVERY = "postRecovery",
}

M.RoutingControlStateChange = {
    ON = "On",
    OFF = "Off",
}

M.RegionToRunIn = {
    ACTIVATING_REGION = "activatingRegion",
    DEACTIVATING_REGION = "deactivatingRegion",
    ACTIVE_REGION = "activeRegion",
    INACTIVE_REGION = "inactiveRegion",
}

M.LambdaUngracefulBehavior = {
    SKIP = "skip",
}

M.DocumentDbDefaultBehavior = {
    SWITCHOVER_ONLY = "switchoverOnly",
    FAILOVER = "failover",
}

M.DocumentDbUngracefulBehavior = {
    FAILOVER = "failover",
}

M.Ec2AsgCapacityMonitoringApproach = {
    SAMPLED_MAX_IN_LAST_24_HOURS = "sampledMaxInLast24Hours",
    AUTOSCALING_MAX_IN_LAST_24_HOURS = "autoscalingMaxInLast24Hours",
}

M.EcsCapacityMonitoringApproach = {
    SAMPLED_MAX_IN_LAST_24_HOURS = "sampledMaxInLast24Hours",
    CONTAINER_INSIGHTS_MAX_IN_LAST_24_HOURS = "containerInsightsMaxInLast24Hours",
}

M.EksCapacityMonitoringApproach = {
    SAMPLED_MAX_IN_LAST_24_HOURS = "sampledMaxInLast24Hours",
}

M.GlobalAuroraDefaultBehavior = {
    SWITCHOVER_ONLY = "switchoverOnly",
    FAILOVER = "failover",
}

M.GlobalAuroraUngracefulBehavior = {
    FAILOVER = "failover",
}

M.ExecutionBlockType = {
    CUSTOM_ACTION_LAMBDA = "CustomActionLambda",
    EXECUTION_APPROVAL = "ManualApproval",
    AURORA = "AuroraGlobalDatabase",
    EC2_ASG = "EC2AutoScaling",
    ROUTING_CONTROL = "ARCRoutingControl",
    REGION_SWITCH = "ARCRegionSwitchPlan",
    PARALLEL = "Parallel",
    ECS = "ECSServiceScaling",
    EKS_RESOURCE_SCALING = "EKSResourceScaling",
    ROUTE53_HEALTH_CHECK = "Route53HealthCheck",
    DOCUMENTDB = "DocumentDb",
    RDS_PROMOTE_READ_REPLICA = "RdsPromoteReadReplica",
    RDS_CREATE_CROSS_REGION_REPLICA = "RdsCreateCrossRegionReplica",
}

M.StepStatus = {
    NOT_STARTED = "notStarted",
    RUNNING = "running",
    FAILED = "failed",
    COMPLETED = "completed",
    CANCELLED = "canceled",
    SKIPPED = "skipped",
    PENDING_APPROVAL = "pendingApproval",
}

M.ExecutionEventType = {
    UNKNOWN = "unknown",
    EXECUTION_PENDING = "executionPending",
    EXECUTION_STARTED = "executionStarted",
    EXECUTION_SUCCEEDED = "executionSucceeded",
    EXECUTION_FAILED = "executionFailed",
    EXECUTION_PAUSING = "executionPausing",
    EXECUTION_PAUSED = "executionPaused",
    EXECUTION_CANCELING = "executionCanceling",
    EXECUTION_CANCELED = "executionCanceled",
    EXECUTION_PENDING_APPROVAL = "executionPendingApproval",
    EXECUTION_BEHAVIOR_CHANGED_TO_UNGRACEFUL = "executionBehaviorChangedToUngraceful",
    EXECUTION_BEHAVIOR_CHANGED_TO_GRACEFUL = "executionBehaviorChangedToGraceful",
    EXECUTION_PENDING_CHILD_PLAN_MANUAL_APPROVAL = "executionPendingChildPlanManualApproval",
    EXECUTION_SUCCESS_MONITORING_APPLICATION_HEALTH = "executionSuccessMonitoringApplicationHealth",
    STEP_STARTED = "stepStarted",
    STEP_UPDATE = "stepUpdate",
    STEP_SUCCEEDED = "stepSucceeded",
    STEP_FAILED = "stepFailed",
    STEP_SKIPPED = "stepSkipped",
    STEP_PAUSED_BY_ERROR = "stepPausedByError",
    STEP_PAUSED_BY_OPERATOR = "stepPausedByOperator",
    STEP_CANCELED = "stepCanceled",
    STEP_PENDING_APPROVAL = "stepPendingApproval",
    STEP_EXECUTION_BEHAVIOR_CHANGED_TO_UNGRACEFUL = "stepExecutionBehaviorChangedToUngraceful",
    STEP_PENDING_APPLICATION_HEALTH_MONITOR = "stepPendingApplicationHealthMonitor",
    PLAN_EVALUATION_WARNING = "planEvaluationWarning",
}

M.Route53HealthCheckStatus = {
    HEALTHY = "healthy",
    UNHEALTHY = "unhealthy",
    UNKNOWN = "unknown",
}

M.UpdatePlanExecutionAction = {
    SWITCH_TO_GRACEFUL = "switchToGraceful",
    SWITCH_TO_UNGRACEFUL = "switchToUngraceful",
    PAUSE = "pause",
    RESUME = "resume",
}

M.UpdatePlanExecutionStepAction = {
    SWITCH_TO_UNGRACEFUL = "switchToUngraceful",
    SKIP = "skip",
}

return M
