-- Code generated by lua-client-codegen. DO NOT EDIT.

local awsjson_protocol = require("smithy.protocol.awsjson")
local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("bcmdashboards.endpoint_rules")
local schemas = require("bcmdashboards.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "AWSBCMDashboardsService"
    if not cfg.protocol then
        cfg.protocol = awsjson_protocol.new({ version = "1.0", service_id = cfg.service_id })
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "bcm-dashboards", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:createDashboard(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateDashboard, input, options)
end

function Client:createScheduledReport(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateScheduledReport, input, options)
end

function Client:deleteDashboard(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteDashboard, input, options)
end

function Client:deleteScheduledReport(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteScheduledReport, input, options)
end

function Client:executeScheduledReport(input, options)
    return self:invokeOperation(schemas.Service, schemas.ExecuteScheduledReport, input, options)
end

function Client:getDashboard(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetDashboard, input, options)
end

function Client:getResourcePolicy(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetResourcePolicy, input, options)
end

function Client:getScheduledReport(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetScheduledReport, input, options)
end

function Client:listDashboards(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListDashboards, input, options)
end

function Client:listScheduledReports(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListScheduledReports, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateDashboard(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateDashboard, input, options)
end

function Client:updateScheduledReport(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateScheduledReport, input, options)
end

return M
