-- Code generated by lua-client-codegen. DO NOT EDIT.

local M = {}

M.FulfillmentState = {
    FULFILLED = "Fulfilled",
    FAILED = "Failed",
    READY_FOR_FULFILLMENT = "ReadyForFulfillment",
}

M.MessageFormatType = {
    PLAIN_TEXT = "PlainText",
    CUSTOM_PAYLOAD = "CustomPayload",
    SSML = "SSML",
    COMPOSITE = "Composite",
}

M.DialogActionType = {
    ELICIT_INTENT = "ElicitIntent",
    CONFIRM_INTENT = "ConfirmIntent",
    ELICIT_SLOT = "ElicitSlot",
    CLOSE = "Close",
    DELEGATE = "Delegate",
}

M.ConfirmationStatus = {
    NONE = "None",
    CONFIRMED = "Confirmed",
    DENIED = "Denied",
}

M.DialogState = {
    ELICIT_INTENT = "ElicitIntent",
    CONFIRM_INTENT = "ConfirmIntent",
    ELICIT_SLOT = "ElicitSlot",
    FULFILLED = "Fulfilled",
    READY_FOR_FULFILLMENT = "ReadyForFulfillment",
    FAILED = "Failed",
}

M.ContentType = {
    GENERIC = "application/vnd.amazonaws.card.generic",
}

return M
