local M = {}

M.AccessDeniedReason = {
    IAM_AUTH = "IAM_AUTH",
    DIRECTORY_AUTH = "DIRECTORY_AUTH",
    DATA_DISABLED = "DATA_DISABLED",
}

M.DirectoryUnavailableReason = {
    INVALID_DIRECTORY_STATE = "INVALID_DIRECTORY_STATE",
    DIRECTORY_TIMEOUT = "DIRECTORY_TIMEOUT",
    DIRECTORY_RESOURCES_EXCEEDED = "DIRECTORY_RESOURCES_EXCEEDED",
    NO_DISK_SPACE = "NO_DISK_SPACE",
    TRUST_AUTH_FAILURE = "TRUST_AUTH_FAILURE",
}

M.ValidationExceptionReason = {
    INVALID_REALM = "INVALID_REALM",
    INVALID_DIRECTORY_TYPE = "INVALID_DIRECTORY_TYPE",
    INVALID_SECONDARY_REGION = "INVALID_SECONDARY_REGION",
    INVALID_NEXT_TOKEN = "INVALID_NEXT_TOKEN",
    INVALID_ATTRIBUTE_VALUE = "INVALID_ATTRIBUTE_VALUE",
    INVALID_ATTRIBUTE_NAME = "INVALID_ATTRIBUTE_NAME",
    INVALID_ATTRIBUTE_FOR_USER = "INVALID_ATTRIBUTE_FOR_USER",
    INVALID_ATTRIBUTE_FOR_GROUP = "INVALID_ATTRIBUTE_FOR_GROUP",
    INVALID_ATTRIBUTE_FOR_SEARCH = "INVALID_ATTRIBUTE_FOR_SEARCH",
    INVALID_ATTRIBUTE_FOR_MODIFY = "INVALID_ATTRIBUTE_FOR_MODIFY",
    DUPLICATE_ATTRIBUTE = "DUPLICATE_ATTRIBUTE",
    MISSING_ATTRIBUTE = "MISSING_ATTRIBUTE",
    ATTRIBUTE_EXISTS = "ATTRIBUTE_EXISTS",
    LDAP_SIZE_LIMIT_EXCEEDED = "LDAP_SIZE_LIMIT_EXCEEDED",
    LDAP_UNSUPPORTED_OPERATION = "LDAP_UNSUPPORTED_OPERATION",
}

M.GroupScope = {
    DOMAIN_LOCAL = "DomainLocal",
    GLOBAL = "Global",
    UNIVERSAL = "Universal",
    BUILTIN_LOCAL = "BuiltinLocal",
}

M.GroupType = {
    DISTRIBUTION = "Distribution",
    SECURITY = "Security",
}

M.MemberType = {
    USER = "USER",
    GROUP = "GROUP",
    COMPUTER = "COMPUTER",
}

M.UpdateType = {
    ADD = "ADD",
    REPLACE = "REPLACE",
    REMOVE = "REMOVE",
}

return M
