-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local endpoint = require("smithy.endpoint")
local endpoint_rules = require("chatbot.endpoint_rules")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("chatbot.schemas")
local sdk_defaults = require("aws.sdk_defaults")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "WheatleyOrchestration_20171011"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.endpoint_provider then
        cfg.endpoint_provider = function(params)
            return endpoint.resolve(endpoint_rules, params)
        end
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "chatbot", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    sdk_defaults.resolve_identity_resolver(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:associateToConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.AssociateToConfiguration, input, options)
end

function Client:createChimeWebhookConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateChimeWebhookConfiguration, input, options)
end

function Client:createCustomAction(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateCustomAction, input, options)
end

function Client:createMicrosoftTeamsChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateMicrosoftTeamsChannelConfiguration, input, options)
end

function Client:createSlackChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.CreateSlackChannelConfiguration, input, options)
end

function Client:deleteChimeWebhookConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteChimeWebhookConfiguration, input, options)
end

function Client:deleteCustomAction(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteCustomAction, input, options)
end

function Client:deleteMicrosoftTeamsChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteMicrosoftTeamsChannelConfiguration, input, options)
end

function Client:deleteMicrosoftTeamsConfiguredTeam(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteMicrosoftTeamsConfiguredTeam, input, options)
end

function Client:deleteMicrosoftTeamsUserIdentity(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteMicrosoftTeamsUserIdentity, input, options)
end

function Client:deleteSlackChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteSlackChannelConfiguration, input, options)
end

function Client:deleteSlackUserIdentity(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteSlackUserIdentity, input, options)
end

function Client:deleteSlackWorkspaceAuthorization(input, options)
    return self:invokeOperation(schemas.Service, schemas.DeleteSlackWorkspaceAuthorization, input, options)
end

function Client:describeChimeWebhookConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeChimeWebhookConfigurations, input, options)
end

function Client:describeSlackChannelConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeSlackChannelConfigurations, input, options)
end

function Client:describeSlackUserIdentities(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeSlackUserIdentities, input, options)
end

function Client:describeSlackWorkspaces(input, options)
    return self:invokeOperation(schemas.Service, schemas.DescribeSlackWorkspaces, input, options)
end

function Client:disassociateFromConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.DisassociateFromConfiguration, input, options)
end

function Client:getAccountPreferences(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetAccountPreferences, input, options)
end

function Client:getCustomAction(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetCustomAction, input, options)
end

function Client:getMicrosoftTeamsChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.GetMicrosoftTeamsChannelConfiguration, input, options)
end

function Client:listAssociations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListAssociations, input, options)
end

function Client:listCustomActions(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListCustomActions, input, options)
end

function Client:listMicrosoftTeamsChannelConfigurations(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListMicrosoftTeamsChannelConfigurations, input, options)
end

function Client:listMicrosoftTeamsConfiguredTeams(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListMicrosoftTeamsConfiguredTeams, input, options)
end

function Client:listMicrosoftTeamsUserIdentities(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListMicrosoftTeamsUserIdentities, input, options)
end

function Client:listTagsForResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.ListTagsForResource, input, options)
end

function Client:tagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.TagResource, input, options)
end

function Client:untagResource(input, options)
    return self:invokeOperation(schemas.Service, schemas.UntagResource, input, options)
end

function Client:updateAccountPreferences(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateAccountPreferences, input, options)
end

function Client:updateChimeWebhookConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateChimeWebhookConfiguration, input, options)
end

function Client:updateCustomAction(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateCustomAction, input, options)
end

function Client:updateMicrosoftTeamsChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateMicrosoftTeamsChannelConfiguration, input, options)
end

function Client:updateSlackChannelConfiguration(input, options)
    return self:invokeOperation(schemas.Service, schemas.UpdateSlackChannelConfiguration, input, options)
end

return M
