local M = {}

M.AdditionalConstraintsElement = {
    REQUIRE_DIGIT = "REQUIRE_DIGIT",
    REQUIRE_LOWERCASE = "REQUIRE_LOWERCASE",
    REQUIRE_SYMBOL = "REQUIRE_SYMBOL",
    REQUIRE_UPPERCASE = "REQUIRE_UPPERCASE",
}

M.Mode = {
    API_KEY = "API_KEY",
    AWS_IAM = "AWS_IAM",
    AMAZON_COGNITO_USER_POOLS = "AMAZON_COGNITO_USER_POOLS",
    OPENID_CONNECT = "OPENID_CONNECT",
}

M.ResolutionStrategy = {
    OPTIMISTIC_CONCURRENCY = "OPTIMISTIC_CONCURRENCY",
    LAMBDA = "LAMBDA",
    AUTOMERGE = "AUTOMERGE",
    NONE = "NONE",
}

M.AuthResources = {
    USER_POOL_ONLY = "USER_POOL_ONLY",
    IDENTITY_POOL_AND_USER_POOL = "IDENTITY_POOL_AND_USER_POOL",
}

M.Service = {
    COGNITO = "COGNITO",
}

M.DeliveryMethod = {
    EMAIL = "EMAIL",
    SMS = "SMS",
}

M.MFAMode = {
    ON = "ON",
    OFF = "OFF",
    OPTIONAL = "OPTIONAL",
}

M.MfaTypesElement = {
    SMS = "SMS",
    TOTP = "TOTP",
}

M.OAuthGrantType = {
    CODE = "CODE",
    IMPLICIT = "IMPLICIT",
}

M.OAuthScopesElement = {
    PHONE = "PHONE",
    EMAIL = "EMAIL",
    OPENID = "OPENID",
    PROFILE = "PROFILE",
    AWS_COGNITO_SIGNIN_USER_ADMIN = "AWS_COGNITO_SIGNIN_USER_ADMIN",
}

M.RequiredSignUpAttributesElement = {
    ADDRESS = "ADDRESS",
    BIRTHDATE = "BIRTHDATE",
    EMAIL = "EMAIL",
    FAMILY_NAME = "FAMILY_NAME",
    GENDER = "GENDER",
    GIVEN_NAME = "GIVEN_NAME",
    LOCALE = "LOCALE",
    MIDDLE_NAME = "MIDDLE_NAME",
    NAME = "NAME",
    NICKNAME = "NICKNAME",
    PHONE_NUMBER = "PHONE_NUMBER",
    PICTURE = "PICTURE",
    PREFERRED_USERNAME = "PREFERRED_USERNAME",
    PROFILE = "PROFILE",
    UPDATED_AT = "UPDATED_AT",
    WEBSITE = "WEBSITE",
    ZONE_INFO = "ZONE_INFO",
}

M.SignInMethod = {
    EMAIL = "EMAIL",
    EMAIL_AND_PHONE_NUMBER = "EMAIL_AND_PHONE_NUMBER",
    PHONE_NUMBER = "PHONE_NUMBER",
    USERNAME = "USERNAME",
}

M.AuthenticatedElement = {
    READ = "READ",
    CREATE_AND_UPDATE = "CREATE_AND_UPDATE",
    DELETE = "DELETE",
}

M.UnAuthenticatedElement = {
    READ = "READ",
    CREATE_AND_UPDATE = "CREATE_AND_UPDATE",
    DELETE = "DELETE",
}

M.ServiceName = {
    S3 = "S3",
}

M.Status = {
    LATEST = "LATEST",
    STALE = "STALE",
}

return M
