local M = {}

M.FeatureType = {
    TABLES = "TABLES",
    FORMS = "FORMS",
    QUERIES = "QUERIES",
    SIGNATURES = "SIGNATURES",
    LAYOUT = "LAYOUT",
}

M.AdapterVersionStatus = {
    ACTIVE = "ACTIVE",
    AT_RISK = "AT_RISK",
    DEPRECATED = "DEPRECATED",
    CREATION_ERROR = "CREATION_ERROR",
    CREATION_IN_PROGRESS = "CREATION_IN_PROGRESS",
}

M.ContentClassifier = {
    FREE_OF_PERSONALLY_IDENTIFIABLE_INFORMATION = "FreeOfPersonallyIdentifiableInformation",
    FREE_OF_ADULT_CONTENT = "FreeOfAdultContent",
}

M.BlockType = {
    KEY_VALUE_SET = "KEY_VALUE_SET",
    PAGE = "PAGE",
    LINE = "LINE",
    WORD = "WORD",
    TABLE = "TABLE",
    CELL = "CELL",
    SELECTION_ELEMENT = "SELECTION_ELEMENT",
    MERGED_CELL = "MERGED_CELL",
    TITLE = "TITLE",
    QUERY = "QUERY",
    QUERY_RESULT = "QUERY_RESULT",
    SIGNATURE = "SIGNATURE",
    TABLE_TITLE = "TABLE_TITLE",
    TABLE_FOOTER = "TABLE_FOOTER",
    LAYOUT_TEXT = "LAYOUT_TEXT",
    LAYOUT_TITLE = "LAYOUT_TITLE",
    LAYOUT_HEADER = "LAYOUT_HEADER",
    LAYOUT_FOOTER = "LAYOUT_FOOTER",
    LAYOUT_SECTION_HEADER = "LAYOUT_SECTION_HEADER",
    LAYOUT_PAGE_NUMBER = "LAYOUT_PAGE_NUMBER",
    LAYOUT_LIST = "LAYOUT_LIST",
    LAYOUT_FIGURE = "LAYOUT_FIGURE",
    LAYOUT_TABLE = "LAYOUT_TABLE",
    LAYOUT_KEY_VALUE = "LAYOUT_KEY_VALUE",
}

M.EntityType = {
    KEY = "KEY",
    VALUE = "VALUE",
    COLUMN_HEADER = "COLUMN_HEADER",
    TABLE_TITLE = "TABLE_TITLE",
    TABLE_FOOTER = "TABLE_FOOTER",
    TABLE_SECTION_TITLE = "TABLE_SECTION_TITLE",
    TABLE_SUMMARY = "TABLE_SUMMARY",
    STRUCTURED_TABLE = "STRUCTURED_TABLE",
    SEMI_STRUCTURED_TABLE = "SEMI_STRUCTURED_TABLE",
}

M.RelationshipType = {
    VALUE = "VALUE",
    CHILD = "CHILD",
    COMPLEX_FEATURES = "COMPLEX_FEATURES",
    MERGED_CELL = "MERGED_CELL",
    TITLE = "TITLE",
    ANSWER = "ANSWER",
    TABLE = "TABLE",
    TABLE_TITLE = "TABLE_TITLE",
    TABLE_FOOTER = "TABLE_FOOTER",
}

M.SelectionStatus = {
    SELECTED = "SELECTED",
    NOT_SELECTED = "NOT_SELECTED",
}

M.TextType = {
    HANDWRITING = "HANDWRITING",
    PRINTED = "PRINTED",
}

M.ValueType = {
    DATE = "DATE",
}

M.AutoUpdate = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.JobStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED",
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS",
}

return M
