local M = {}

M.ConflictType = {
    ANOTHER_ACTIVE_STREAM = "ANOTHER_ACTIVE_STREAM",
    DOMAIN_NOT_ACTIVE = "DOMAIN_NOT_ACTIVE",
    CANNOT_CHANGE_SPEAKER_AFTER_ENROLLMENT = "CANNOT_CHANGE_SPEAKER_AFTER_ENROLLMENT",
    ENROLLMENT_ALREADY_EXISTS = "ENROLLMENT_ALREADY_EXISTS",
    SPEAKER_NOT_SET = "SPEAKER_NOT_SET",
    SPEAKER_OPTED_OUT = "SPEAKER_OPTED_OUT",
    CONCURRENT_CHANGES = "CONCURRENT_CHANGES",
    DOMAIN_LOCKED_FROM_ENCRYPTION_UPDATES = "DOMAIN_LOCKED_FROM_ENCRYPTION_UPDATES",
    CANNOT_DELETE_NON_EMPTY_WATCHLIST = "CANNOT_DELETE_NON_EMPTY_WATCHLIST",
    FRAUDSTER_MUST_BELONG_TO_AT_LEAST_ONE_WATCHLIST = "FRAUDSTER_MUST_BELONG_TO_AT_LEAST_ONE_WATCHLIST",
}

M.ResourceType = {
    BATCH_JOB = "BATCH_JOB",
    COMPLIANCE_CONSENT = "COMPLIANCE_CONSENT",
    DOMAIN = "DOMAIN",
    FRAUDSTER = "FRAUDSTER",
    SESSION = "SESSION",
    SPEAKER = "SPEAKER",
    WATCHLIST = "WATCHLIST",
}

M.AuthenticationDecision = {
    ACCEPT = "ACCEPT",
    REJECT = "REJECT",
    NOT_ENOUGH_SPEECH = "NOT_ENOUGH_SPEECH",
    SPEAKER_NOT_ENROLLED = "SPEAKER_NOT_ENROLLED",
    SPEAKER_OPTED_OUT = "SPEAKER_OPTED_OUT",
    SPEAKER_ID_NOT_PROVIDED = "SPEAKER_ID_NOT_PROVIDED",
    SPEAKER_EXPIRED = "SPEAKER_EXPIRED",
}

M.DomainStatus = {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    SUSPENDED = "SUSPENDED",
}

M.ServerSideEncryptionUpdateStatus = {
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
}

M.FraudsterRegistrationJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS",
    FAILED = "FAILED",
}

M.DuplicateRegistrationAction = {
    SKIP = "SKIP",
    REGISTER_AS_NEW = "REGISTER_AS_NEW",
}

M.SpeakerStatus = {
    ENROLLED = "ENROLLED",
    EXPIRED = "EXPIRED",
    OPTED_OUT = "OPTED_OUT",
    PENDING = "PENDING",
}

M.ExistingEnrollmentAction = {
    SKIP = "SKIP",
    OVERWRITE = "OVERWRITE",
}

M.FraudDetectionAction = {
    IGNORE = "IGNORE",
    FAIL = "FAIL",
}

M.SpeakerEnrollmentJobStatus = {
    SUBMITTED = "SUBMITTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS",
    FAILED = "FAILED",
}

M.FraudDetectionDecision = {
    HIGH_RISK = "HIGH_RISK",
    LOW_RISK = "LOW_RISK",
    NOT_ENOUGH_SPEECH = "NOT_ENOUGH_SPEECH",
}

M.FraudDetectionReason = {
    KNOWN_FRAUDSTER = "KNOWN_FRAUDSTER",
    VOICE_SPOOFING = "VOICE_SPOOFING",
}

M.StreamingStatus = {
    PENDING_CONFIGURATION = "PENDING_CONFIGURATION",
    ONGOING = "ONGOING",
    ENDED = "ENDED",
}

return M
