local M = {}

M.OnboardingState = {
    CREATED = "CREATED",
    ONBOARDED = "ONBOARDED",
    ERROR = "ERROR",
}

M.OperationalState = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.UsageState = {
    IN_USE = "IN_USE",
    NOT_IN_USE = "NOT_IN_USE",
}

M.NsdOnboardingState = {
    CREATED = "CREATED",
    ONBOARDED = "ONBOARDED",
    ERROR = "ERROR",
}

M.NsdOperationalState = {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

M.NsdUsageState = {
    IN_USE = "IN_USE",
    NOT_IN_USE = "NOT_IN_USE",
}

M.DescriptorContentType = {
    TEXT_PLAIN = "text/plain",
}

M.VnfOperationalState = {
    STARTED = "STARTED",
    STOPPED = "STOPPED",
}

M.VnfInstantiationState = {
    INSTANTIATED = "INSTANTIATED",
    NOT_INSTANTIATED = "NOT_INSTANTIATED",
}

M.PackageContentType = {
    APPLICATION_ZIP = "application/zip",
}

M.NsState = {
    INSTANTIATED = "INSTANTIATED",
    NOT_INSTANTIATED = "NOT_INSTANTIATED",
    UPDATED = "UPDATED",
    IMPAIRED = "IMPAIRED",
    UPDATE_FAILED = "UPDATE_FAILED",
    STOPPED = "STOPPED",
    DELETED = "DELETED",
    INSTANTIATE_IN_PROGRESS = "INSTANTIATE_IN_PROGRESS",
    INTENT_TO_UPDATE_IN_PROGRESS = "INTENT_TO_UPDATE_IN_PROGRESS",
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
    TERMINATE_IN_PROGRESS = "TERMINATE_IN_PROGRESS",
}

M.LcmOperationType = {
    INSTANTIATE = "INSTANTIATE",
    UPDATE = "UPDATE",
    TERMINATE = "TERMINATE",
}

M.NsLcmOperationState = {
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLING = "CANCELLING",
    CANCELLED = "CANCELLED",
}

M.TaskStatus = {
    SCHEDULED = "SCHEDULED",
    STARTED = "STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    ERROR = "ERROR",
    SKIPPED = "SKIPPED",
    CANCELLED = "CANCELLED",
}

M.UpdateSolNetworkType = {
    MODIFY_VNF_INFORMATION = "MODIFY_VNF_INFORMATION",
    UPDATE_NS = "UPDATE_NS",
}

return M
